### ISSUE TITLE
Purpose, scope and road-map of this repository

### ISSUE THREAD

**Issue by mkaze** [keras-team/keras-nlp#1]
I just found this repository (and its CV counterpart, [keras-cv](https://github.com/keras-team/keras-cv)). Unfortunately, its one-line description, i.e. "Industry-strength Natural Language Processing workflows with Keras", is a bit vague and does not help to understand its scope and purpose. It would be great if you could kindly explain what this repository intends to cover exactly, and if there is any road-map for development? Further, would you consider outside contributions as well?

Thanks.

**Comment by bhack** [comment]
What will be the relationship with https://github.com/tensorflow/text?

**Comment by tanzhenyu** [comment]
I will get to this EOW, thanks for creating this issue!

**Comment by tanzhenyu** [comment]
https://github.com/keras-team/governance/pull/21

**Comment by tanzhenyu** [comment]
Closing this as RFC is merged
