### ISSUE TITLE
Implementing a Tweet Tokenizer

### ISSUE THREAD

**Issue by aflah02** [keras-team/keras-nlp#101]
Tweets are an vital data source in most NLP tasks especially those revolving around Social Media Analysis and hence Tweet Tokenizers already exist in libraries such as NLTK.
The difference in NLTK's Tweet Tokenizer's behavior from a normal tokenizer is illustrated [here](https://stackoverflow.com/a/61947145/13858953)
I think this can be a great to our current set of tokenizers

**Comment by mattdangerw** [comment]
I think we have support for this already.

For word level tokenization `keras.layers.TextVectorization` allows custom callables for `standardize` and `split` (which could allows keeping `#`). For subword tokenizers (wordpiece, sentencepiece), punctuation like that will be kept by default I believe.

An open question for me is whether we will at some point want to offer `keras.layers.TextVectorization` through the `Tokenizer` interface we defined in this library. But I don't think we will need a layer specifically for hashtag preserving. Feel free to re-open if I missed something!
