### ISSUE TITLE
Bring TFA EmbeddingBag to Keras NLP

### ISSUE THREAD

**Issue by AlexanderLavelle** [keras-team/keras-nlp#1017]
**Is your feature request related to a problem? Please describe.**

With the impending demise of tf-addons, it would be wonderful to port [EmbeddingBag](https://www.tensorflow.org/addons/api_docs/python/tfa/layers/EmbeddingBag), as this is a useful layer and belongs / should belong in this NLP library.

**Describe the solution you'd like**

I would like to see `EmbeddingBag` under the Keras NLP / TF NLP umbrella

**Describe alternatives you've considered**

All alternatives are worse, as a custom CUDA kernel is deployed here to merge the `take` and `sum` which otherwise results in low-to-no benefit by briefly persisting the large `take` matrix.

**Additional context**

N/a

**Comment by jbischof** [comment]
Thanks @AlexanderLavelle, is this already covered by https://keras.io/api/layers/core_layers/embedding/?

**Comment by jbischof** [comment]
Thanks for the clarification! Our main goal is to implement popular models and we haven't hit this so far. Are there any top architectures that would be unlocked by adding this layer?

**Comment by AlexanderLavelle** [comment]
@jbischof the EmbeddingBag can be very useful when dealing with sentence meaning, as you can highly increase the context length for transformers. Imagine going from a 128 batch x 1024 words to a 128 batch x1024 sentences x ragged words.

Very useful for NLP in terms of collecting a maximal amount of information.

**Comment by jbischof** [comment]
Apologies @AlexanderLavelle what I mean is that we aren't prioritizing layers unless they are needed for a specific model we want to offer---say T5. Right now our model offerings are quite limited and filling the gaps is the main priority for our users.

That said if you want to contribute a layer like this, let us know and we can assess the fit for our roadmap. Apologies again!
