### ISSUE TITLE
Keras_nlp.utils has no attribute top_p_search

### ISSUE THREAD

**Issue by SRDdev** [keras-team/keras-nlp#1023]
**Describe the bug**
The keras_nlp library has no attribute top_p_search. It is visible on the website and on GitHub but in Colab it does not work.

**To Reproduce**
https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/nlp/ipynb/neural_machine_translation_with_keras_nlp.ipynb

**Additional context**
![screenshot-colab research google com-2023 05 05-16_21_14](https://user-images.githubusercontent.com/84516626/236439329-408afa16-5b5b-4b8e-b7cc-5e3840b93ce9.png)

**Comment by Aliync** [comment]
> 

Hello,

Just wanted to let you know that the keras_nlp library has undergone changes recently, including renaming utils to samplers and top_p_search, top_k_search to top_p_sampler and top_k_sampler. The Keras API reference hasn't been updated yet. Hope this helps!

**Comment by SRDdev** [comment]
Thank you so much for this information !
This definitely helps.

Thanks

**Comment by jbischof** [comment]
@SRDdev yes we just released v0.5 and there are a couple steps to refreshing the docs on keras.io. Should be fixed by next week!
