### ISSUE TITLE
`shell/lint.sh` fails with exit code 1 without giving proper error

### ISSUE THREAD

**Issue by adhadse** [keras-team/keras-nlp#104]
**Describe the bug**
I think the bug has to do with improper exclusion of `venv` folder by both `shell/format.sh` and `shell/lint.sh`, since on running `format.sh` the script starts formatting code install in virtual environment installed packages, i.e., in `venv` folder. If terminal session is closed before this process, then leads to `lint.sh` failing to pass as it includes `venv` directory "unformatted" code.

**To Reproduce**
I am using Windows system to format my code, No WSL and using VirtualEnv environment created using PyCharm (doesn't matter).

**Expected behavior**
`format.sh` and `lint.sh` should exclude `venv` folder in the operation.

**Would you like to help us fix it?**
Definitely.

**Comment by mattdangerw** [comment]
A fix here makes sense, though I think we may want to whitelist the directories to format, rather than blacklist other directories. Thanks!

**Comment by abheesht17** [comment]
@adhadse, I'm curious here. I'm also using Windows, and I've been copy-pasting the commands (black, flake8, isort) from the shell script to the terminal in order to run them. How did you run the bash script on Windows without WSL? Is there some tool which you used?

**Comment by adhadse** [comment]
@abheesht17 No I don't think so. Currently I am on Windows 11, and bash scripts do run as you said by just copy pasting the commands. I have experienced no problem in running them. I do known of WSL, but no I am not using WSL.

Second I am defaulting to PowerShell as my default command line, instead of standard command prompt. Maybe that make the difference.

Sorry for the late response.😅

**Comment by abheesht17** [comment]
No issues, man :).

Currently, in Windows, we have to paste every line from the script to the terminal...so, I was wondering if there was a way which you were using to run it in one go (`sh bash_script.sh`, similar to Linux) instead of having to copy-paste.

**Comment by adhadse** [comment]
I just run it without any `sh` in the beginning, so like this in PowerShell,

``
shell/lint.sh
```
and for some god known reasons it work.😅

**Comment by abheesht17** [comment]
Thanks, man! Will try it out!

**Comment by adhadse** [comment]
This probably might definitely have to do with PowerShell on windows, but still leaves some questions yet to be answered.

- Switching from Windows to WSL, does definitely helps fixing `format.sh` to stop giving any error with proposed solution of whitelisting the intended files (`targets`). 
- **BUT** `isort` continues to fails with error, "Broken 1 Path", when it is given the same input `targets` as in `format.sh`.🤔

<details>
<summary><code>format.sh</code></summary>

```bash
#!/bin/bash -e

base_dir=$(dirname $(dirname $0))
target_dir="${base_dir}/examples/ ${base_dir}/keras_nlp/"
targets="${base_dir}/*.py ${base_dir}/examples/ ${base_dir}/keras_nlp/"

isort --sp "${base_dir}/setup.cfg" --sl ${targets}
black --line-length 80 ${targets}

for i in $(find ${target_dir} -name '*.py'); do
  if ! grep -q Copyright $i; then
    echo $i
    cat shell/copyright.txt $i >$i.new && mv $i.new $i
  fi
done

flake8 --config "${base_dir}/setup.cfg" ${targets}
```

</details>

<details>
<summary><code>lint.sh</code></summary>

```bash
#!/bin/bash -e

base_dir=$(dirname $(dirname $0))
target_dir="${base_dir}/examples/ ${base_dir}/keras_nlp/"
targets="${base_dir}/*.py ${base_dir}/examples/ ${base_dir}/keras_nlp/"

isort --sp "${base_dir}/setup.cfg" --sl -c "${targets}"
if ! [ $? -eq 0 ]; then
  echo "Please run \"./shell/format.sh\" to format the code."
  exit 1
fi

flake8 --config "${base_dir}/setup.cfg" "${targets}"
if ! [ $? -eq 0 ]; then
  echo "Please fix the code style issue."
  exit 1
fi

black --check --line-length 80 "${targets}"
if ! [ $? -eq 0 ]; then
  echo "Please run \"./shell/format.sh\" to format the code."
    exit 1
fi
for i in $(find "${target_dir}" -name '*.py'); do
  if ! grep -q Copyright  $i; then
    echo "Please run \"./shell/format.sh\" to format the code."
    exit 1
  fi
done
```

</details>

**Even more interestingly**, `isort` runs perfectly fine when ran directly from command line:
```bash
BASE_DIR=$(dirname $(dirname -- $0))
isort --sp $BASE_DIR/setup.cfg --sl -c $BASE_DIR/*.py $BASE_DIR/examples/ $BASE_DIR/keras_nlp/
```

**Comment by adhadse** [comment]
The above issue was resolved by switching from `"${targets}"` to `${targets}`.
