### ISSUE TITLE
Keras_nlp does not run on Apple Silicon Mac (MacBookPro M2 Max)

### ISSUE THREAD

**Issue by ramkumarkoppu** [keras-team/keras-nlp#1041]
Tried to run the working netbook from Colab to local M2 Max Mac. initially I had issues with the pip installing matching tensorflow-text for eras_nlp. after installing suitable package, gets tun time error, looks like it is making CUDA specific calls for half precision floating points which may not work on Apple silicon. 

The question is, any specific version of keras_nlp including tensorflow-text proven to be working on Apple Silicon Mac (MacBookPro M2)?

**Comment by abheesht17** [comment]
You can try using a `tensorflow-text` wheel from here, I guess: https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases. This is maintained by a third party, and not by Google

**Comment by ramkumarkoppu** [comment]
Hi @abheesht17, downloaded latest version of package and tried to install it but it's not successful. it complains,
pip install tensorflow_text-2.12.1-cp39-cp39-macosx_11_0_arm64.whl
ERROR: tensorflow_text-2.12.1-cp39-cp39-macosx_11_0_arm64.whl is not a supported wheel on this platform.

Following is my current environment:
conda list | grep -i tensorflow
tensorflow-deps           2.9.0                         0    apple
tensorflow-estimator      2.12.0                   pypi_0    pypi
tensorflow-macos          2.12.0                   pypi_0    pypi
tensorflow-metal          0.8.0                    pypi_0    pypi

python --version
Python 3.10.11

**Comment by jbischof** [comment]
@ramkumarkoppu unfortunately this is a `tensorflow-text` issue and not something we control directly.

**Comment by ramkumarkoppu** [comment]
without resolving dependency on tensorflow-text, can keras_nlp work?

**Comment by jbischof** [comment]
Not unless you handle the tokenization yourself which is a non-starter sadly.
