### ISSUE TITLE
Issue with BeamSampler

### ISSUE THREAD

**Issue by hakim770** [keras-team/keras-nlp#1047]
When I try to use BeamSampler (with num_beam=2) in this tutorial for example:
https://github.com/keras-team/keras-io/blob/master/examples/nlp/neural_machine_translation_with_keras_nlp.py

I got this error:

```
InvalidArgumentError: Exception encountered when calling layer 'cached_multi_head_attention_1' (type CachedMultiHeadAttention).

{{function_node __wrapped__Einsum_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Expected dimension 1 at axis 0 of the input shaped [2,40,8,32] but got dimension 2 [Op:Einsum]

Call arguments received by layer 'cached_multi_head_attention_1' (type CachedMultiHeadAttention):
  • query=tf.Tensor(shape=(2, 40, 256), dtype=float32)
  • value=tf.Tensor(shape=(1, 40, 256), dtype=float32)
  • key=None
  • attention_mask=tf.Tensor(shape=(1, 1, 40), dtype=int32)
  • cache=None
  • cache_update_index=None
```

Can you help me fixing that?

**Comment by jbischof** [comment]
@hakim770 thanks for the bug report! Could you please attach a colab gist reproducing the error? Thank you!

**Comment by hakim770** [comment]
> @hakim770 thanks for the bug report! Could you please attach a colab gist reproducing the error? Thank you!

@jbischof  Thanks. Yes, this is:

https://colab.research.google.com/drive/1HF0O5roM88KlLvrFmQh_TokVna7nTuWn?usp=sharing

**Comment by mattdangerw** [comment]
I think this issue may be resolve by discussion on https://github.com/keras-team/keras-io/issues/1373
