### ISSUE TITLE
Contribution: Adding Falcon Models

### ISSUE THREAD

**Issue by Ruqyai** [keras-team/keras-nlp#1072]
**Is your feature request related to a problem? Please describe.**

The feature request is related to contribution by adding the new pre-trained (Falcon LLM - 7b /40b) models  to KerasNLP.

**Describe the solution you'd like**

The feature request is related to contribute by adding Falcon (7b and 40b) to pre-trained models in KerasNLP.
In 7th June, 2023 , Falcon 40B, the world’s top-ranked open-source AI model on the Hugging Face leaderboard for large language models (LLMs).   
Falcon LLM models available under the Apache 2.0 software license.
More info here: https://huggingface.co/tiiuae

- [ ] Backbone #1081 
- [ ] Tokenizer  #1099 
- [ ] Presets #1100 
- [ ] Preprocessor
- [ ] Tasks

**"Google Cloud credits are provided for this project."**

**Comment by mattdangerw** [comment]
Thank you! I think you are already working on this correct? Just assigned you.

Looking forward to this!

**Comment by Ruqyai** [comment]
> Thank you! I think you are already working on this correct? Just assigned you.
> 
> Looking forward to this!

Yes I am already working.
Now I am following the documentation of how to convert the weights from PyTorch to TensorFlow
It sounds easy but I get it an error
Am I on the right way?

https://huggingface.co/docs/transformers/model_sharing#convert-a-model-for-all-frameworks
https://huggingface.co/transformers/v3.3.1/model_sharing.html#make-your-model-work-on-all-frameworks

**Comment by shivance** [comment]
@Ruqyai  Please follow https://github.com/keras-team/keras-nlp/tree/master/tools/checkpoint_conversion

**Comment by Ruqyai** [comment]
#1081 
To fix CLA issue, I removed the old PR.
