### ISSUE TITLE
Add Transformer-XL backbone

### ISSUE THREAD

**Issue by abuelnasr0** [keras-team/keras-nlp#1077]
Transformer-XL is a decoder model that enables learning dependency beyond the max sequence length of the model by dividing the input into segments. and storing the hidden states of previous segments.
it also uses relative position embedding instead of absolute position embedding.
PAPER: https://arxiv.org/abs/1901.02860

**Comment by susnato** [comment]
@abuelnasr0 are you working on this? If not then I would like to contribute this.

**Comment by abuelnasr0** [comment]
@susnato sorry but I am currently working in it. you can check out the huggingface documentation. there is a lot of models there, if you would like to contribute with a model.

**Comment by ghasem1987** [comment]
تست

**Comment by shivance** [comment]
#928 XLNet uses TransformerXL under the hood.
