### ISSUE TITLE
Text generation - Greedy approach

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#108]
Briefly, the “greedy” approach is that we always find the next token that has the maximum predicted probability given the current sequence. This [article](https://huggingface.co/blog/how-to-generate#greedy-search) has a detailed explanation on how the greedy approach works.

Before implementation, we will need to make a contract on our input/output format, and if we want it to be a standalone utility, or mixin like HuggingFace's [GenerationMixin](https://github.com/huggingface/transformers/blob/v4.17.0/src/transformers/generation_utils.py#L378).

**Comment by chenmoneygithub** [comment]
Update this issue with more detailed requirements.

The generation util will have the following signature:
```
def generate_text_greedy(
    get_next_token_probability_fn, seed, max_length, end_token):
  """
  Text generation utility based on greedy search.

  Greedy search always appends the token having the largest probability to 
  existing sequence.

  Args:
    get_next_token_probability_fn: a callable, which takes in input_sequence 
      and output the probability distribution of the next token.
    seed: list of int, the initial sequence to append generated tokens.
    max_length: int. The max length of generated text.
    decoder_only: bool, defaults to True. If True, the underlying text model is 
      a decoder-only structure, otherwise it is a encoder-decoder structure. 
    end_token: int, defaults to None. The token marking the end of sequence.
  """

```
Please check [this colab](https://colab.research.google.com/gist/chenmoneygithub/f21656925f783f66012b9c86b30c3de2/copy-of-kerasnlp-text-generation-greedy.ipynb) for an example implementation. Contributors can use this colab as a start, but it is incomplete, e.g., it does not respect the `end_token`. 

Note: the file layout would be `keras_nlp/utils/generate_text_greedy.py`.

**Comment by mattdangerw** [comment]
This is now fixed!
