### ISSUE TITLE
Add ragged support to SinePositionEncoding

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#109]
We should add support for ragged inputs to the `SinePositionEncoding` layer.

Our `PositionEmbedding` layer shows a rough example of how this can be done on [this line](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/position_embedding.py#L93)

**Comment by abheesht17** [comment]
@mattdangerw, I'd like to take this up. Thanks!

**Comment by mattdangerw** [comment]
Sure thing! Though for small issues like these, try to leave some of these available for newcomers to the project as well. Thanks!

**Comment by Neeshamraghav012** [comment]
I am interested.

**Comment by jayam30** [comment]
Hey i would like to take this

**Comment by jaygala223** [comment]
Hi @mattdangerw, I can see a merged PR. Is this still open? If not, I would like to work on this.

**Comment by mattdangerw** [comment]
Ah, this is indeed fixed! Thanks.
