### ISSUE TITLE
Error in loading model from the saved model in the disk

### ISSUE THREAD

**Issue by ramkumarkoppu** [keras-team/keras-nlp#1112]
**Describe the bug**
Couldn't load model from saved model into the disk using keras model save() and load_model() methods.

**To Reproduce**
https://colab.research.google.com/gist/ramkumarkoppu/39287e4e9be7ee2ad944fb7f22038494/gpt2-with-lora.ipynb#scrollTo=ahf3FH9rPHVj

**Expected behavior**
Able to save load model from the disk without any warning/error.

**Additional context**

**Would you like to help us fix it?**
I don't know how model save and load works.

**Comment by alvarobartt** [comment]
I guess this was already solved/patched at https://github.com/keras-team/keras-nlp/pull/1073, so installing from source should do the work 😄 Anyway, out of curiosity @jbischof which is the scoped date for either 0.5.3 or 0.6.0?

**Comment by jbischof** [comment]
We are expected a big release tomorrow!

**Comment by mattdangerw** [comment]
I believe this was temporary, old, and no longer an issue on recent version of KerasNLP + Keras. Closing, reopen if this reproducible on latest versions.
