### ISSUE TITLE
`SetuptoolsDeprecationWarning`: `setup.py` install is deprecated. Use build and pip and other standards-based tools.

### ISSUE THREAD

**Issue by adhadse** [keras-team/keras-nlp#112]
**Describe the bug**
Not necessarily a bug, but a deprecation warning faced while running `py setup.py develop`. We need to move away from `setup.py` to pip. Needs more discussion.

**To Reproduce**
Just run the procedures given in [setup guide](https://github.com/keras-team/keras-nlp/blob/master/CONTRIBUTING.md#setup-environment)

**Expected behavior**
Install without any deprecation warning.

**Would you like to help us fix it?**
Yes, definitely!

**Comment by mattdangerw** [comment]
Thanks for this!

Would just doing `pip install -e ".[tests]"` work?

Definitely feel free to test out solutions and add a PR for our contributing guide.
