### ISSUE TITLE
Add a utility to detokenize as lists of python strings

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#113]
Going from tf.Tensor strings back to python string is confusing. We should add a utility to do that to the base tokenizer class.

We can discuss the exact name of the PR, suggest `.detokenize_to_strings()` as a starting point.

Usages:
```
>>> keras_nlp.layers.ByteTokenizer().detokenize_to_strings([104, 101, 108, 108, 111])
'hello'
>>> keras_nlp.layers.ByteTokenizer().detokenize_to_strings([[104, 101, 108, 108, 111]])
['hello']
```

**Comment by mattdangerw** [comment]
@aflah02 can you comment anything on this issue? I can't assign you until you are a participant :)

**Comment by mattdangerw** [comment]
I think the flow for this utility will need to be something like...

For ragged tensors, call `x.to_list()`. For dense tensors, call `x.numpy().tolist()`. Then recursively walk all elements and convert byte strings to python strings.

**Comment by aflah02** [comment]
Thanks for creating this, I'll get to work on this!

**Comment by aflah02** [comment]
@mattdangerw I think I've got it down roughly
You can see the demo [here](https://colab.research.google.com/gist/aflah02/df745134ff33053334653e7d8992108b/detokenizing.ipynb)
The only change was to add a method in the Base Class which is implemented there itself and used by all Classes which Inherit From it Right? Here's the code for the [same](https://github.com/aflah02/keras-nlp/blob/b98837ef4a1d349baf646294395fa5dca920f552/keras_nlp/tokenizers/tokenizer.py#L133)
If this works I'll write some tests for the same

**Comment by mattdangerw** [comment]
That looks good!

Yeah, we should only need to add this to the base class. I'm still not 100% sure about the name, but let's make a PR and we can discuss there.

Things to test:
 - ragged ouputs
 - dense outputs
 - scalar dense outputs (outputting a single string)

We should have a unit test for each of those cases.
