### ISSUE TITLE
Issue with Loading Models in Keras NLPv0.6.0 

### ISSUE THREAD

**Issue by Aliync** [keras-team/keras-nlp#1131]
hello
3 hours ago a new update came out for Keras nlp and we are so happy but this update made a bug (I think):
I saved a model with Keras format previously which included  Keras nlp TransformerDecoder layers in it I can load the model without any problem with version [0.5.2] but in the current version in loading the model it says:

TypeError: Error when deserializing class 'TransformerDecoder' using config={'name': 'transformer_layer_0', 'trainable': True, 'dtype': 'float32', 'intermediate_dim': 3072, 'num_heads': 16, 'dropout': 0.01, 'activation': {'class_name': 'SwiGLU', 'config': {'name': 'swi_glu', 'trainable': True, 'dtype': 'float32'}}, 'layer_norm_epsilon': 1e-05, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': 256}, 'shared_object_id': 1}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'normalize_first': True, 'build_input_shape': [None, None, 1280], 'has_cross_attention': False}.

Exception encountered: ('Keyword argument not understood:', 'build_input_shape')

I downgraded my Keras nlp and the model loaded without any issue 
best regards

**Comment by abheesht17** [comment]
Can you please share a Colab/minimal reproducible example?

**Comment by Aliync** [comment]
I'm using Kaggle but I just tried to reproduce this error in google colab and it seems fine! it doesn't have a problem with loading previously saved models maybe it's because of the Tensorflow version installed on the Kaggle notebook, idk
