### ISSUE TITLE
Replace Layernorm with Atex ?

### ISSUE THREAD

**Issue by dathudeptrai** [keras-team/keras-nlp#1132]
is it a good idea to use Atex (https://github.com/NVIDIA/atex/tree/release) for better performance of layernorm ?

**Comment by mattdangerw** [comment]
This looks like a compilation speedup specifically for layernorm on tensorflow? I think in general, our approach is to focus on XLA compilation as the default approach, rather then all the explicit op fusion that is done in non-XLA `tf.functions`. By and large, letting XLA do it's thing is both simpler, and a general performance boost.

Do we have any number on how much this would speed up an overall transformer train_step, compared to whatever XLA does by default? The [numbers here](https://github.com/NVIDIA/atex/tree/release/atex/nv_norms) look like they are comparing to non-XLA, and don't give a sense of how much this would affect the overall train-time of a LLM.

**Comment by dathudeptrai** [comment]
Tag @kaixih here to better understanding the `Atex` but AFAIK, `Atex` is xla-compatible. @mattdangerw

**Comment by mattdangerw** [comment]
Compilation speedups like this are going to be a big focus for us in the coming months, but not with tensorflow and GPU specific additions like this. We will want solutions we can apply with Keras 3 to tf, torch and jax on GPU and TPU (with XLA as a common ground).

Closing this for now!
