### ISSUE TITLE
The weblink to https://keras.io/keras_core/ in the latest release notes throws error 404: page not found

### ISSUE THREAD

**Issue by ramkumarkoppu** [keras-team/keras-nlp#1133]
Are these webpages not yet ready to be viewed?

**Comment by abheesht17** [comment]
Yeah, they'll be available from tomorrow morning PST

**Comment by ramkumarkoppu** [comment]
Sorry. My question seem to be premature. I will wait for few more days before ask follow-up questions.

**Comment by ramkumarkoppu** [comment]
Sorry. My question seem to be premature. I will wait for few more days before ask follow-up questions.
