### ISSUE TITLE
Port the Getting Started Guide to multi-bakend Keras

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#1134]
For https://keras.io/guides/keras_nlp/getting_started/

We should take a pass over the whole guide, and rewrite it so it can be run on tf, jax and torch.

**Comment by shivance** [comment]
Hi @mattdangerw @fchollet I am thinking of taking on these tutorials to port

- [ ] https://keras.io/guides/keras_nlp/transformer_pretraining/
- [ ] https://keras.io/examples/generative/text_generation_gpt/

**Comment by mattdangerw** [comment]
@shivance sounds good! I was thinking we could just open up a quick issue for each. If you can do so that would be great!

**Comment by shivance** [comment]
@mattdangerw Shall I open this on keras-io?

**Comment by mattdangerw** [comment]
Fixed!
