### ISSUE TITLE
Port metrics to multi-backend

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#1136]

**Comment by mattdangerw** [comment]
I think as an initial version, we can do something like this.

- Re-enable tests on all backends.
- Make sure all input data gets converted to tensors.
- Mark "compiled" metrics tests as tf only. Compiled tests would require string inputs to a model, which does not make sense for jax/torch (no string dtype).
- For perplexity in particular, we can probably leave compilation testing on all backends, as it works in int/float space.

The goal would be to have code like this still work on all backends...
```python
rouge_2 = keras_nlp.metrics.RougeN(order=2)
rouge_2(reference_sentence, translated_sentence)
```

**Comment by shivance** [comment]
I think I can take this up ! Will update on this soon. Currently onto couple of examples.

**Comment by mattdangerw** [comment]
Fixed on https://github.com/keras-team/keras-nlp/pull/1186
