### ISSUE TITLE
Migrate tfa.optimizers.LAMB to keras_nlp

### ISSUE THREAD

**Issue by schistyakov** [keras-team/keras-nlp#1138]
tfa.optimizers.LAMB helps to train Encoder based model quicker by using significant large batch size. Due to limited support of tfa it is not possible anymore to mix tfa.optimizers.LAMB with recent TF and keras_nlp model

Migrate tfa.optimizers.LAMB from TFA to keras_nlp
https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers/LAMB

**Comment by abheesht17** [comment]
Hi, @schistyakov! I think all optimisers go in the original Keras repo: https://github.com/keras-team/keras/

Documentation: https://keras.io/api/optimizers/

**Comment by mattdangerw** [comment]
Agreed, generally optimizers are not really domain specific (not NLP only things), so we would probably land these in core Keras in anywhere.

@chenmoneygithub do you know anything about this optimizer and if we have considered it for Keras in the past?

**Comment by mattdangerw** [comment]
Let's consider this as an addition to the main keras package if anywhere. If this is still of interest, please open an issue on github.com/keras-team/keras !
