### ISSUE TITLE
[TF Backend] Decode error with `generate()` [non-multi-precision]

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#1145]
Reproduced the error here: https://colab.research.google.com/drive/1aJkc_RjfGoFlXvWG89MZA-eHoubJg0Yo?usp=sharing.

See the last cell. Ran this example twice, hit the same decode error.

**Comment by mattdangerw** [comment]
I think this should be fixed with https://github.com/keras-team/keras-nlp/pull/1150 ?

**Comment by abheesht17** [comment]
Hmmm, correct. But why do we not hit this error with Keras 2.0? Why is the model producing gibberish?

**Comment by mattdangerw** [comment]
Should we track that on #1149. What is the difference between #1145 and #1149?

**Comment by abheesht17** [comment]
Yeah, let's track it on the other issue
