### ISSUE TITLE
Port BeamSampler to multi-backend keras

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#1156]
This was not included in 0.6.0, but we should port it from `tf.xx` -> `ops.xx`.

**Comment by shivance** [comment]
https://github.com/keras-team/keras-nlp/blob/18dde27a4624ad68b7f80f22db52754d9925701c/keras_nlp/samplers/beam_sampler.py#L219-L224

@mattdangerw  What is core alternative for tf.gather ?

**Comment by mattdangerw** [comment]
`ops.take_along_axis`!
