### ISSUE TITLE
Add LLaMa v2 to KerasNLP

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#1162]
https://twitter.com/ylecun/status/1681336284453781505

I'm up for contributing this.

**Comment by shivance** [comment]
Putting roadmap

- [ ] Llama Backbone
- [ ] Tokenizer and Preprocessor
- [ ] Tasks
- [ ] Presets

**Comment by sahusiddharth** [comment]
@shivance

I would like to work on this

**Comment by mattdangerw** [comment]
This is done!
