### ISSUE TITLE
Tests are broken due to ALBERT ?

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#1167]
Realized that CI at #1110 is broken due to some ALBERT changes.

**Comment by mattdangerw** [comment]
https://github.com/keras-team/keras-nlp/pull/1168 for now

**Comment by mattdangerw** [comment]
Just posting an update. This is still an issue as of keras-core 0.1.2, but fixed on the main branch. We should be able to go back to the latest keras-core after the next release.

**Comment by mattdangerw** [comment]
Fixed
