### ISSUE TITLE
New Keras Core like elegant, colorful model.summary() for KerasNLP

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#1182]

**Comment by abheesht17** [comment]
Don’t we already have this as a result of porting to Keras Core?

**Comment by shivance** [comment]
I'm running a colab with keras-core and keras-nlp, it gives old summary

![image](https://github.com/keras-team/keras-nlp/assets/51750587/92e7981d-e588-4621-9c38-f7e275b816eb)

**Comment by abheesht17** [comment]
Probably because you haven’t set the backend, because of which it is defaulting to tf.keras?

**Comment by shivance** [comment]
Great find @abheesht17

**Comment by mostafamdy** [comment]
Hi @abheesht17 
Do you know how we can print the full summary?
"Connected to" column is truncated 
![Screenshot 2024-04-22 155025](https://github.com/keras-team/keras-nlp/assets/76405917/c3ccf4e0-983f-4f1a-bc81-b3fcfae14b2d)
