### ISSUE TITLE
tackling unknown problem

### ISSUE THREAD

**Issue by pure-rgb** [keras-team/keras-nlp#1194]
In this https://www.kaggle.com/competitions/kaggle-llm-science-exam/overview comp. most of the solutions are provided in hugging face transformers.  I like to explore keras-nlp but have no idea where to start. I also looked at some guide in keras-io but there is not much guidance though there are plenty of language model available in keras-nlp.

**Comment by jbischof** [comment]
cc @martin-gorner, our Kaggle competition expert

**Comment by martin-gorner** [comment]
Two KerasNLP starter notebooks have just landed:
* https://www.kaggle.com/code/alexia/kerasnlp-starter-notebook-contradictory-dearwatson
* https://www.kaggle.com/code/alexia/kerasnlp-starter-notebook-disaster-tweets

And please read the [KerasNLP getting started guide](https://keras.io/guides/keras_nlp/getting_started/). It's very well put together by @jbischof himself.

Enjoy!
