### ISSUE TITLE
`XLNet` tests failing

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#1205]
The CI of currently open PRs fails with `tuple index out of range` for XLNet

cc: @susnato

**Comment by susnato** [comment]
Hi @shivance thanks for informing me! investigating the issue now.
 

By the way when I am running the tests on my machine they seem to be totally fine. 

![image](https://github.com/keras-team/keras-nlp/assets/56069179/e19661db-3a8d-45ce-b0e6-616956226fe5)
(the `torch` backend one)

**Comment by susnato** [comment]
I just upgraded the `keras-core` to 0.1.4 and the tests seems to be failing now!

**Comment by shivance** [comment]
#1200 #1202
