### ISSUE TITLE
TransformerDecoder with CrossAttention does not work when query and key have different dimensionality

### ISSUE THREAD

**Issue by fdtomasi** [keras-team/keras-nlp#1235]
**Describe the bug**
`self._cross_attention_layer` is built with `query_shape=encoder_sequence_shape` instead of `query_shape=decoder_sequence_shape` and it does not work when `query` and `key` do not have the same dimensionality.

**To Reproduce**
https://colab.research.google.com/drive/1pTUWH7TIHeLpgWGXvRFdV7x4Z0Q5ASGn?usp=sharing

**Expected behavior**
Cross attention should work when query and key have different dimensionality.

**Additional context**
The culprit may be the last `Dense` which is not supposed to be initialised with the dimensions of `key` but `query`
https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/modeling/transformer_decoder.py#L198

**Comment by mattdangerw** [comment]
True! We don't have any models currently that are seq2seq with different hidden dims for the encooder vs decoder, but this would for sure be good to support at the layer lever. Are you interested in fixing?

**Comment by fdtomasi** [comment]
Thank you for confirming! Just to double check, the replacement of the build with `query_shape=decoder_sequence_shape` rather than `query_shape=encoder_sequence_shape` should already fix that, right? Are there cases where one should use `query_shape=encoder_sequence_shape` instead?

**Comment by mattdangerw** [comment]
Yeah I think you got it. `query_shape=decoder_sequence_shape` is always correct in `build` for cross attention, given that the query passed to the cross attention always will have the decode sequence input shape. There are no config options on the layer to change that.

We would just need the `build` fix and a unit test for the decoder layer where the encoder sequence has a different feature dim.
