### ISSUE TITLE
ValueError: Unable to create dataset (name already exists)

### ISSUE THREAD

**Issue by Alwaysadil** [keras-team/keras-nlp#1239]
import matplotlib.pyplot as plt

from tensorflow.keras.callbacks import Callback

import os

checkpoint_dir = '/model/checkpoints_m_1'

if not os.path.exists(checkpoint_dir):
    os.makedirs(checkpoint_dir)
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss', patience=3)
# Set up the model checkpoint callback
checkpoint_call = ModelCheckpoint(filepath=checkpoint_dir+"/checkpoint_{epoch}.hdf5",
                                  monitor='val_loss',
                                  save_best_only=True,
                                  save_weights_only=False,
                                  mode='min',
                                  save_freq='epoch')
transformer.fit(train_ds, epochs=EPOCHS, validation_data=val_ds,batch_size=BATCH_SIZE,callbacks=[early_stop, checkpoint_call)

Epoch 1/10
1/1 [==============================] - ETA: 0s - loss: 6.8405 - accuracy: 0.3250
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-865e41f45523> in <cell line: 1>()
----> 1 transformer.fit(train_ds, epochs=EPOCHS, validation_data=val_ds,batch_size=BATCH_SIZE,callbacks=[early_stop, checkpoint_call, plot_losses])

2 frames
/usr/local/lib/python3.10/dist-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, name, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times, external, track_order, dcpl, dapl, efile_prefix, virtual_prefix, allow_unknown_filter, rdcc_nslots, rdcc_nbytes, rdcc_w0)
    161         sid = h5s.create_simple(shape, maxshape)
    162 
--> 163     dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl, dapl=dapl)
    164 
    165     if (data is not None) and (not isinstance(data, Empty)):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.create()

ValueError: Unable to create dataset (name already exists)

**Comment by jbischof** [comment]
@Alwaysadil would you be willing to share your example as a colab notebook? This makes debugging much easier on our end.

**Comment by Alwaysadil** [comment]
Hi @jbischof 
Thanks for your response

I have cleared that issue by replacing .hdf5 to .tf

Thanks
