### ISSUE TITLE
`Tokenizer.compute_output_shape` uses undefined `self.sequence_length`

### ISSUE THREAD

**Issue by jackd** [keras-team/keras-nlp#1241]
**Describe the bug**
[Tokenizer.comput_output_shape](https://github.com/keras-team/keras-nlp/blob/60af93f596863f51dee73228c04d1b27d00415d0/keras_nlp/tokenizers/tokenizer.py#L128) uses `self.sequence_length` which is not defined in this class. While AFAIK all concrete implementations assign the property, there is no indication that concrete implementations should.

**To Reproduce**
```python
from keras_nlp.tokenizers import Tokenizer
tokenizer = Tokenizer().compute_output_shape((3,))
```

**Expected behavior**
If `Tokenizer`'s behaviour depends on `sequence_length` it should require it as a constructor arg or be documented as a required property to be implemented by descendent classes.

**Would you like to help us fix it?**
Sure, just don't know how to do it without introducing a breaking change / what breaking changes are allowed.

**Comment by mattdangerw** [comment]
True. And thanks for filing! I think we have probably two options here.

1) Just remove it. `compute_output_shape` should be optional generally for layers. And our main use case is calling these layers with tf.data which is going to trace the call graph (not use `compute_output_shape`). Does anything break if we just delete it?
2) Move `compute_output_shape` to all subclasses. We don't have too many, so this isn't too bad.

**Comment by sahusiddharth** [comment]
@mattdangerw  

## Is this issue fixed? If not can I take a look into it?

**Comment by jackd** [comment]
Sorry, I got distracted. Either of those options sound good to me - or rather, option 1 and possibly option 2. I'm still not entirely sure when `compute_output_shape` gets called, so if @sahusiddharth wants to take this up it's fine by me :)

**Comment by sahusiddharth** [comment]
Gone with option 1 proposed by @mattdangerw have created a PR [https://github.com/keras-team/keras-nlp/pull/1245]

**Comment by mattdangerw** [comment]
Thanks both of you! Left a comment on the PR, but plan sounds good to me.

**Comment by mattdangerw** [comment]
Fixed in https://github.com/keras-team/keras-nlp/pull/1245
