### ISSUE TITLE
Add WSL related setup guide for VSCode and PyCharm

### ISSUE THREAD

**Issue by adhadse** [keras-team/keras-nlp#125]
**Is your feature request related to a problem? Please describe.**
Contributors might not be familiar with WSL and how to setup the project as per WSL, since our BASH scripts relies on bash to run as discussed in #104. 

**Describe the solution you'd like**
Add guides/documentation links  to setup WSL environment for VSCode and PyCharm.
As described [here](https://www.jetbrains.com/help/pycharm/using-wsl-as-a-remote-interpreter.html) and [here](https://code.visualstudio.com/docs/remote/wsl)

**Comment by mattdangerw** [comment]
Totally makes sense to add a section for Windows to our contributing guide, but let's keep it very brief.

We should just say that given that shell scripts in this repo will not support windows shell/powershell, we recommend WSL as the preferred way to develop from windows. And then link to official resources on how to set up WSL.

We should not include any IDE setup instructions, as we don't want to maintain a list of per IDE setup tips in our contributor guide.
