### ISSUE TITLE
Add Mistral.AI's Transformer Model to KerasNLP

### ISSUE THREAD

**Issue by tirthasheshpatel** [keras-team/keras-nlp#1275]
**Is your feature request related to a problem? Please describe.**

Mistral.AI recently released their 7B transformer model with the implementation of the model in PyTorch here: https://github.com/mistralai/mistral-src

**Describe the solution you'd like**

It would be nice to have the model implemented in Keras Core.

**Comment by mattdangerw** [comment]
Thanks for taking this on @tirthasheshpatel !

**Comment by shivance** [comment]
This is great! if @tirthasheshpatel is planning to contribute this model, he could reuse the RoPE layer we already have!
