### ISSUE TITLE
Error with tf.data and MLMMaskGenerator for dense inputs

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#128]
When using the MLMMaskGenerator for to map over dense, batched inputs in a tf.data.Dataset, we get the following error...

`TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`

This colab has a reproduction https://colab.research.google.com/gist/mattdangerw/4596df85105ff6e6731128fc79d16bf3/mlmmaskgenerator-bug.ipynb

tf.data + dense, batched inputs might be the most common use case for this layer, so this is an important one to fix.

**Comment by chenmoneygithub** [comment]
Did some investigation, and the cause is MLMMaskGenerator has unexpected behavior in graph mode. Need more debugging to figure out how to fix it.
