### ISSUE TITLE
XLMRobertaTokenizer.detokenize method is not wokring

### ISSUE THREAD

**Issue by onting** [keras-team/keras-nlp#1282]
**Describe the bug**

detokenize method is not available for XLMRobertaTokenizer class

**To Reproduce**

```
tokenizer = keras_nlp.models.XLMRobertaTokenizer.from_preset("xlm_roberta_base_multi")
for sentence in tokenizer.detokenize(tokenizer(["한국어 토크나이즈", "This is a bug example"])).numpy():
  print(sentence.decode())
```

**Expected behavior**

```
한국어 토크나이즈
This is a bug example
```

**Additional context**

The decode method has been worked with code like below.
```
def detokenize(self, ids):
        ids = tf.ragged.boolean_mask(ids, tf.not_equal(ids, self.mask_token_id))
        ids = tf.subtract(ids, 1)
        return super().detokenize(ids)
```
So, it must be related with index mishaps. And it seems like list concatenation mishap like below
https://github.com/keras-team/keras-nlp/blob/2b02bff6d7395898f0ab53476662a972c913f39b/keras_nlp/models/xlm_roberta/xlm_roberta_tokenizer.py#L107-L114
The concatenation increase all indices in previous vocabulary, and it affects on super().detokenize(ids).

**Comment by mattdangerw** [comment]
Good catch! Valid bug, and indeed it looks like we are just not properly reversing the index remapping that is done after sentepiece tokenization.

Are you interested in working on a fix? If not will find an owner soon.

**Comment by onting** [comment]
@mattdangerw I'm not confident in fixing. Other people should manage this one better.
Thank you.
