### ISSUE TITLE
Add a keras.io guide for pretraining a transformer with keras-nlp

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#130]
Working on a keras.io guide for pretraining a keras-nlp transformer model from scratch, using word piece tokenizer, transformer encoder, embedding layers, and our MLM layer helpers.

Will link a draft of this for keras.io when it is up, opening this so we can track for the 0.2.0 release.

**Comment by mattdangerw** [comment]
Guide is incoming https://github.com/keras-team/keras-io/pull/859

**Comment by ddofer** [comment]
Is it maybe relevant to add "load a pretrained (BERT) model" to this task?

**Comment by mattdangerw** [comment]
@ddofer this is incoming! And top priority for us actually.
