### ISSUE TITLE
Introduce `knlp` as an alias for `keras_nlp`

### ISSUE THREAD

**Issue by adhadse** [keras-team/keras-nlp#134]
Would love to know the views of maintainers and contributor on this.

@mattdangerw, @chenmoneygithub.

**Comment by chenmoneygithub** [comment]
I feel `knlp` is too vague to be a good alias, let's just keep `keras_nlp`.

**Comment by mattdangerw** [comment]
Hmm, yeah I think `keras_nlp` should be the status quo for now. Really we need need to make this decisions in tandem with `keras_cv` if we were to change.

But we do have a `kt` alias for `keras_tuner`, so it might make sense to sync up here.

@fchollet do you have thoughts?

Status quo:
```
from tensorflow import keras
import keras_cv
import keras_nlp
import keras_tuner as kt
```

A potential shortcut version:
```
from tensorflow import keras
import keras_cv as kc
import keras_nlp as kn
import keras_tuner as kt
```

Or we could consider dropping `kt` as the canonical import for keras_tuner in our guides.

**Comment by chenmoneygithub** [comment]
I am a bit surprised that `keras_tuner` has an alias `kt`... - -"

**Comment by adhadse** [comment]
@chenmoneygithub  Even Pandas has `pd` and seaborn goes with `sns`, so the vague feeling might just be a matter of time...🤔

**Comment by chenmoneygithub** [comment]
@adhadse That comes with a tradeoff between convenience and vagueness - pandas is of a low level, which gets called lots of times within one file. Thus, the benefits of having `pd` alias beats the vagueness it comes with. Differently, for our Keras ecosystem libraries, e.g., KerasNLP, KerasCV and KerasTuner are at a high level, which won't be called lots of times in one file. 

Another bad thing about abbreviation is potential conflict with other packages, so personally I feel unless a package already has a wide user group and it is expected to get called frequently, it does not make too much sense to make an alias. But this is just my personal takes, different opinions are welcome!

**Comment by mattdangerw** [comment]
Confirmed with @fchollet the other day. We should prefer `keras_cv` and `keras_nlp`, and consider removing `kt` for keras_tuner from our documentation.

Anyone is of course free to import the libraries however they would like, but we should try to keep the link to keras clear in our own code/docs/guides.
