### ISSUE TITLE
Add `Falcon` Model

### ISSUE THREAD

**Issue by SamanehSaadat** [keras-team/keras-nlp#1372]
Falcon is a family of language models created by the [Technology Innovation Institute (TII)](https://www.tii.ae/). Falcon family has multiple base models: [Falcon-180b](https://huggingface.co/tiiuae/falcon-180B), [Falcon-40B](https://huggingface.co/tiiuae/falcon-40b), [Falcon-7B](https://huggingface.co/tiiuae/falcon-7b), and [Falcon-rw-1b](https://huggingface.co/tiiuae/falcon-rw-1b). Instruction tuned version of some of the models is available as well: [Falcon-7B-Instruct](https://huggingface.co/tiiuae/falcon-7b-instruct) and [Falcon-40B-Instruct](https://huggingface.co/tiiuae/falcon-40b-instruct). Since this is a high quality model, it would be a good addition to the collection of KerasNLP models. I will be working on adding this model.

The following components should be implemented:

- [x] Backbone
- [x] Tokenizer
- [x] Presets
- [x] Preprocessors
- [x] Task

**Comment by simeetnayan81** [comment]
Hi @SamanehSaadat. This seems a good enhancement project and I would also like to collaborate with you on this.

**Comment by SamanehSaadat** [comment]
Hi @simeetnayan81! Thanks for your interest in this project. We appreciate you offering to collaborate. The scope of this project is pretty small and I'm handling it for now. But I'll definitely reach out if we need your help.
If you're interested in contributing to Keras, please take a look at [issues with `contributions-welcome` label](https://github.com/keras-team/keras-nlp/issues?q=is%3Aopen+is%3Aissue+label%3A%22contributions+welcome%22).
