### ISSUE TITLE
Likely misbehaving keras.ops.triu()

### ISSUE THREAD

**Issue by gtikhonov** [keras-team/keras-nlp#1396]
**Describe the bug**
`keras.ops.triu(x, k)` nullifies only elements below main diagonal as if it always treats the `k` argument as if it is negative.

**To Reproduce**
https://colab.research.google.com/drive/1B4mVWSOtnP6H7fRhXwBbTdLJgLKhFkAE?usp=sharing

**Expected behavior**
`keras.ops.triu(x, k)` would act according to its documentation for all integer `k` values.

**Additional context**
Numpy v1.23.5 
Keras v3.0.2

**Would you like to help us fix it?**
Possible.

**Comment by mattdangerw** [comment]
Thanks for filing, but I believe this is a keras-team/keras issue not keras-nlp.

Could you open this at https://github.com/keras-team/keras/issues and we can track it there? Thanks!
