### ISSUE TITLE
i installed keras-nlp in pycharm IDE , when in run 

### ISSUE THREAD

**Issue by said-ml** [keras-team/keras-nlp#1426]

**Comment by said-ml** [comment]
i install a keras-nlp in pycharm ide: import keras_nlp , run correctly , but when i run:classifier = keras_nlp.models.DebertaV3Classifier.from_preset(
    "deberta_v3_base_en",
    num_classes=4,
)
i get the following error:
Traceback (most recent call last):
  File "C:\Users\LG\AppData\Roaming\JetBrains\PyCharmCE2023.1\scratches\DeBERTaV3.py", line 9, in <module>
    classifier = keras_nlp.models.DebertaV3Classifier.from_preset(
                 ^^^^^^^^^^^^^^^^
AttributeError: module 'keras_nlp' has no attribute 'models'

**Comment by langit** [comment]
Same problem in a plain python session invoked on the command line.

**Comment by said-ml** [comment]
langit , i think is the problem of OS windows system, that why always linux  is a better option

**Comment by amacanovic** [comment]
Same problem here on Windows using pycharm and installing using:
```
! pip install --upgrade keras-nlp
! pip install --upgrade keras
```

**Comment by horrylala** [comment]
same issue here, my OS:
Windows 11 professional, version:22621

when i install keras-nlp ,its version is  allways  
`Name: keras-nlp`
`Version: 0.0.2`
`
Summary: Keras Natural Language Processing Library`
`
Home-page: https://github.com/keras-team/keras-nlp`
`
Author: The Keras authors`
`
Author-email: keras-team@google.com`
`
License: Apache License 2.0`
`
Location: [C:\ProgramData\miniconda3\Lib\site-packages](file:///C:/ProgramData/miniconda3/Lib/site-packages)
Requires: numpy, tf-nightly`

whatever i use:
`!pip install -U keras-nlp>=0.8`

it's kinda wired.

**Comment by SuryanarayanaY** [comment]
Hi @said-ml ,

I have tested the sample code and it works fine on colab.Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/0dd6ea4ffa4119f15081e0a682bc9eb5/nlp_1426.ipynb). I have installed latest version of keras_nlp i.e 0.8.2 by following the instructions [here](https://github.com/keras-team/keras-nlp?tab=readme-ov-file#keras-3-installation).

I would recommend to install Keras3 version and Tensorflow >=2.15v as these are dependencies for `keras_nlp` for TF backend. 

I believe the issue might be related to the dependencies. Please check requirements.txt files. 

Thanks!

**Comment by ducknificient** [comment]
same issue in fedora linux too
```
PyCharm 2023.2.2 (Professional Edition)
Build #PY-232.9921.89, built on October 1, 2023
Licensed to 
Subscription is active until September 26, 2024.
For educational use only.
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.7.6-200.fc39.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    ide.experimental.ui=true


Current Desktop: GNOME
```

**Comment by turgut090** [comment]
Because keras-nlp depends on tensorflow-text and tensorflow-text team does not support Windows. 
https://github.com/tensorflow/text/issues/1140#issuecomment-1579391859

**Comment by xuse2008** [comment]
> ensorflow-text

你真解惑，我搞了半天没搞明白，感谢 感谢。就是不知道windows上如何安装keras-nlp了，头大

**Comment by said-ml** [comment]
SuryanarayanaY, yes the code works fine in Google Colab but not locally in Windows OS , turgut090 mentioned 'Because keras-nlp depends on tensorflow-text and tensorflow-text team does not support Windows.'

**Comment by maximilian22x** [comment]
They should put the info in the docs, that it does not work with windows
