### ISSUE TITLE
Gemma discrepancies

### ISSUE THREAD

**Issue by awsaf49** [keras-team/keras-nlp#1494]
**Describe the bug**
Recently [unsloth.ai](https://unsloth.ai/blog/gemma-bugs) has pointed out some discrepancies in **Gemma** model implementations. I think it would be nice to have them verified and addressed. 

Specially, they mentioned **Keras mixed_bfloat16 RoPE is wrong**. According to their findings, TPUs on Colab cast RoPE positions in int32, whilst in Keras, they’re cast to compute_dtype (bfloat16), causing [8190, 8191] to become [8192, 8192]

[Keras’s incorrect line casting positions to bfloat16](https://github.com/keras-team/keras-nlp/blob/v0.8.2/keras_nlp/models/gemma/gemma_attention.py#L159)
[Deepmind uses int32 for positions and I also verified on TPUs its int32](https://github.com/google-deepmind/gemma/blob/main/gemma/sampler_test.py#L102)

![RoPE_Precision_qQH2lVYi4pol4uB136Iuo](https://github.com/keras-team/keras-nlp/assets/36858976/4bd55335-ef9a-44dc-b41d-d1fce2967217)

**Comment by grasskin** [comment]
Hi @awsaf49, thank you for bringing this up! We've actually fixed this in #1497 and #1508. Thank you!
