### ISSUE TITLE
Random Deletion Layer - Data Augmentation

### ISSUE THREAD

**Issue by aflah02** [keras-team/keras-nlp#152]
I've created this issue to specifically discuss the Random Deletion Layer while we figure out how to incorporate WordNet for Synonym Replacement

I've adapted the design mentioned by @mattdangerw [here](https://github.com/keras-team/keras-nlp/issues/94#issuecomment-1104490120) for the same
```
class RandomDeletion(keras.layers.Layer):
    """Augments input by randomly deleting words

    Args:
        probability: probability of a word being chosen for deletion
        max_replacements: The maximum number of words to replace
        stop_word_only: Only deletes stopwords

    Examples:

    Basic usage.
    >>> augmenter = keras_nlp.layers.RandomDeletion(
    ...     probability = 0.3,
    ... )
    >>> augmenter(["dog dog dog dog dog"])
    <tf.Tensor: shape=(), dtype=string, numpy=b'dog dog dog dog'>
    """
    pass
```

**Comment by mattdangerw** [comment]
Thanks, this looks good to me!

A few things we should consider...
 - We may want to offer a character or a word level version of this. Random deleted characters could be good for simulating typos.
 - For the word level splitting, we may want to make split points configurable (we could support regex splitting like WordPieceTokenizer for example). `split_pattern: A regex pattern to match delimiters to split.`

**Comment by mattdangerw** [comment]
I think so yeah, input could be a scalar dense tensor or a batched dense tensor.

We could also consider supporting pre-split ragged inputs (in WordPiece we do this for example), if even a configurable split regex is not enough your splitting needs. Probably not something for a first version though.

**Comment by aflah02** [comment]
Thanks, I'll keep this at the back of my mind and maybe take this up as a next step once an initial layer is ready!

**Comment by aflah02** [comment]
Hey @mattdangerw 
I've been thinking about this issue for some days now and I'm not quite sure what's the best way to approach this. Should I go for a recursive approach? So when I reach to the level which has strings I'll treat that as my base case? or Should I create a function and map it to the tensor in the call? or am I missing something and there's a better way out of this?

**Comment by aflah02** [comment]
Hey @mattdangerw 
I've been working on this and I have an implementation [here](https://colab.research.google.com/gist/aflah02/46175c2534eec94db3333b9889313c85/random-deleter.ipynb)
I am stuck currently at the part where I need to handle non scalar inputs would be great if you can check this out and share any suggestions

**Comment by mattdangerw** [comment]
@aflah02 yeah, definitely we need to support the bached 2D case at a minimum. Potentially this could be done with RaggedTensor and no map function? Something like...

```python
inputs = tf.constant(["this is a test", "this is another test"])
ragged_words = tf.strings.split(inputs)
mask = tf.random.uniform(ragged_words.flat_values.shape) > 0.25
mask = ragged_words.with_flat_values(mask)
deleted = tf.ragged.boolean_mask(ragged_words, mask)
deleted = tf.strings.reduce_join(deleted, axis=-1, separator=" ")
```

Would that work?

**Comment by aflah02** [comment]
@mattdangerw 
Thanks for the reviews
In regards to this [comment](https://github.com/keras-team/keras-nlp/pull/214#discussion_r887190121) for random character deletions I feel separate layers makes more sense as at the end of the day the layers can be stacked by the user. Having them together would essentially mean having 2 separate logics operating in the same file having them separate would also make it more maintainable but I guess that's just my preference. What do you think?

**Comment by mattdangerw** [comment]
@aflah02 that makes sense to me. In that case, let's call this `RandomWordDeletion`, it's more specific to what we are doing here, and leave us room to grow our offering.

**Comment by mattdangerw** [comment]
@aflah02 here's a tracable set of ragged tensor ops based on the TF Text `RandomItemSelector`.

https://colab.sandbox.google.com/gist/mattdangerw/efdf506bd1719192e93be371d6eb68c6/tracable-delete-fn.ipynb

**Comment by aflah02** [comment]
@mattdangerw Thanks a ton! This looks great and will the work much easier. I'll make sure to go through these ragged tensor ops for future use as well!!
