### ISSUE TITLE
`SentencePieceTokenizer` inside a `keras.models.Model` fails to be reconstructed during `keras.saving.load_model()`

### ISSUE THREAD

**Issue by briango28** [keras-team/keras-nlp#1522]
**Describe the bug**

When a [`SentencePieceTokenizer`](https://keras.io/api/keras_nlp/tokenizers/sentence_piece_tokenizer/) is integrated into a model using the functional API, a.k.a. [`keras.models.Model`](https://keras.io/api/models/model/), it cannot be properly reconstructed from a saved `model.keras` file.

While untested, I would expect any other custom keras object that relies on `load_assets()` to be able to compute an output spec for a given input tensor to exhibit the same behavior.

**To Reproduce**

https://colab.research.google.com/drive/1XMNYLQrJo25_BkIv8GT02bMJZMjw5RoC?usp=sharing
Refer to cell no. 6

**Expected behavior**

Proper reconstruction of `SentencePieceTokenizer`.

**Additional context**

When [`keras.saving.load_model()`](https://keras.io/api/models/model_saving_apis/model_saving_and_loading/#loadmodel-function) is called on a saved Functional model, the model is reconstructed by running a KerasTensor through the model. Because this happens before the vocabulary is loaded via [`SentencePieceTokenizer.load_assets()`](https://github.com/keras-team/keras-nlp/blob/v0.8.2/keras_nlp/tokenizers/sentence_piece_tokenizer.py#L137), an error is raised upon encountering the tokenizer in the model.

The above functionality can be found in [`keras.saving.saving_lib`](https://github.com/keras-team/keras/blob/v3.1.1/keras/saving/saving_lib.py).
[`_load_state()`](https://github.com/keras-team/keras/blob/v3.1.1/keras/saving/saving_lib.py#L378), which is responsible for calling `load_assets()` is called on L178, later than [`deserialize_keras_object()`](https://github.com/keras-team/keras/blob/v3.1.1/keras/saving/serialization_lib.py#L394) on [L155](https://github.com/keras-team/keras/blob/v3.1.1/keras/saving/saving_lib.py#L155).

**Would you like to help us fix it?**
Defining `SentencePieceTokenizer.compute_output_spec()` seems to be sufficient to construct the model graph, allowing the loading function to continue to `_load_state()`.

Cell no. 3 in the colab notebook is a working example.

**Comment by briango28** [comment]
After a quick skim of the repository, [`BytePairTokenizer`](https://keras.io/api/keras_nlp/tokenizers/byte_pair_tokenizer/), [`WordPieceTokenizer`](https://keras.io/api/keras_nlp/tokenizers/word_piece_tokenizer/), and [`SentencePieceTokenizer`](https://keras.io/api/keras_nlp/tokenizers/sentence_piece_tokenizer/) seem to have vocabularies saved & loaded with `save_assets()` & `load_assets()` and are affected by this issue.

The aforementioned `compute_output_spec()` method (copied below) should work for each of them.

```python
def compute_output_spec(self, input_spec) -> keras.KerasTensor:
    return keras.KerasTensor(input_spec.shape + (self.sequence_length,),
                             dtype=self.compute_dtype,
                             sparse=not self.sequence_length)
```

**Comment by mattdangerw** [comment]
@briango28 can this be marked as fixed?

**Comment by Zynyste** [comment]
Sure thing!
