### ISSUE TITLE
Add a vocabulary_size argument to UnicodeCharacterTokenizer

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#155]
We should add a `vocabulary_size` argument to the `UnicodeCharacterTokenizer` layer that clamps the output code point values to be in the range `[0, vocabulary_size)`.

We should also add a `vocabulary_size()` method as with other tokenizers that returns this value if it has been set, and return `None` otherwise.

Potential docstring:

```
        vocabulary_size: Set the vocabulary `vocabulary_size`,
            by clamping all codepoints to the range [0, vocabulary_size).
            Effectively this will make the `vocabulary_size - 1` id the
            the OOV token.
```

**Comment by aflah02** [comment]
Hey Matt, if no one else is interested I can take this up!

**Comment by mattdangerw** [comment]
Go for it! Thanks!
