### ISSUE TITLE
Add a vocabulary_size argument to WordPieceTokenizer

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#156]
We should add a `vocabulary_size` argument to the WordPieceTokenizer layer that forces the vocabulary size by truncating the passed in vocabulary if necessary.

Potential docstring:
```
        vocabulary_size: Force the vocabulary to be exactly `vocabulary_size`,
            by truncating the input vocabulary if necessary. This is not
            equivalent to retraining a word piece vocabulary from scratch, but
            can be useful for quick hyperparameter tuning.
```

**Comment by mattdangerw** [comment]
Some other notes:
 - If the `vocabulary_size` argument is passed, calling `layer.vocabulary_size()` should always match what was passed.
 - If the vocabulary file is shorted that the forced vocabulary size, we can log a warning. `Warning: Setting vocab size to a larger value than the input vocabulary file. Some token ids will never be output from the tokenizer.`

**Comment by mattdangerw** [comment]
Thank you!

**Comment by blackhat-coder** [comment]
I'm sorry for the delay, been busy with school work. Would send in a PR asap.

**Comment by mattdangerw** [comment]
Thank you! Let me know if there are any question I can help with.

**Comment by blackhat-coder** [comment]
Hi @mattdangerw , how do I run tests ?
currently written testcases

**Comment by mattdangerw** [comment]
Check out the environment and test running sections of our contributing guide.

https://github.com/keras-team/keras-nlp/blob/master/CONTRIBUTING.md#setting-up-an-environment

If something is broken or unclear there, let us know!

**Comment by aflah02** [comment]
Hey @blackhat-coder, are you still working on this?

**Comment by lordgavy01** [comment]
Hey @mattdangerw, can I contribute to this?

**Comment by jayam30** [comment]
Hey I would like to take this,

**Comment by atharvapurdue** [comment]
I would like to contribute to this

**Comment by progs2002** [comment]
Hey, @mattdangerw some of the tests are failing as vocabualry_size has a method of the same name. Should I change the attribute name from `vocabulary_size` to `_vocabulary_size`?

**Comment by sahusiddharth** [comment]
@mattdangerw, I would like to contribute on this

**Comment by jbischof** [comment]
@sahusiddharth you probably want approach #1, otherwise there's no way to use this argument to load a vocabulary file too large to fit in memory.

**Comment by sahusiddharth** [comment]
@jbischof 
# Context: you have asked to add vocabulary size argument and there is a method with the same name in WordPieceTokenizer and that is causing error  
`   
def vocabulary_size(self) -> int:
                 """Get the size of the tokenizer vocabulary."""
                 return len(self.vocabulary)

`
# Question : Can i change the name of vocabulary_size argument to vocab_size ?

**Comment by man0045** [comment]
hi there is this issue still open ,i love to conteibute init

**Comment by sahusiddharth** [comment]
Hi @man0045,  

this issue is already [closed](https://github.com/keras-team/keras-nlp/issues/155).
