### ISSUE TITLE
Broken Imports

### ISSUE THREAD

**Issue by aflah02** [keras-team/keras-nlp#159]
I think I broke the library as now there are errors due to the utils directory added in the last PR. I think this is because I forgot to add a `__init__` file for the utils folder. I'll create a PR to fix this as locally this seems to fix the issue.

Demo for what's broken is [here](https://colab.research.google.com/gist/aflah02/7f06a9bf29dd0edc5d2aeff9e55c4633/untitled16.ipynb)

**Comment by aflah02** [comment]
@mattdangerw I'm not entirely sure how to fix this as if I add a `__init__` file then tests fail citing 
```
keras_nlp/utils/tensor_utils_test.py:16: in <module>
    from tensor_utils import tensor_to_string_list
E   ModuleNotFoundError: No module named 'tensor_utils'
```

**Comment by mattdangerw** [comment]
I think adding a __init__ file to the utils directory would be correct. We probably do not need to add the `tensor_to_string_list` function directly to that init file yet.

We may very well want to, but we should answer the question of how we want to use this with a tokenizer first. For now, it can be unexported.

**Comment by mattdangerw** [comment]
Re why you are getting that, you need to do imports relative the to base of the library. `from keras_nlp.utils.tensor_utils import tensor_to_string_list`, but as I mentioned above, we don't need to add that line quite yet.

**Comment by aflah02** [comment]
Thanks @mattdangerw 
Oh got it so should I leave the file empty then right? Apart from putting in the license details

**Comment by mattdangerw** [comment]
yep!
