### ISSUE TITLE
403 KaggleApiHTTPError while running GemmaCausalLM

### ISSUE THREAD

**Issue by nashschool** [keras-team/keras-nlp#1625]
**Describe the bug**

I was trying to run the keras_nlp notebook for Kaggle AIMO ([link](https://www.kaggle.com/code/awsaf49/aimo-kerasnlp-starter)). This uses keras_nlp to generate GemmaCausalLM. 
`gemma_lm = keras_nlp.models.GemmaCausalLM.from_preset(CFG.preset)
`
I get the following error:

> 
> HTTPError                                 Traceback (most recent call last)
> [/usr/local/lib/python3.10/dist-packages/kagglehub/exceptions.py](https://localhost:8080/#) in kaggle_api_raise_for_status(response, resource_handle)
>      57     try:
> ---> 58         response.raise_for_status()
>      59     except requests.HTTPError as e:
> 
> 9 frames
> HTTPError: 403 Client Error: Forbidden for url: https://www.kaggle.com/api/v1/models/keras/gemma/keras/gemma_1.1_instruct_2b_en/3/download/config.json
> 
> The above exception was the direct cause of the following exception:
> 
> KaggleApiHTTPError                        Traceback (most recent call last)
> [/usr/local/lib/python3.10/dist-packages/kagglehub/exceptions.py](https://localhost:8080/#) in kaggle_api_raise_for_status(response, resource_handle)
>      78 
>      79         # Default handling
> ---> 80         raise KaggleApiHTTPError(message, response=response) from e
>      81 
>      82 
> 
> KaggleApiHTTPError: 403 Client Error.
> 
> You don't have permission to access resource at URL: https://www.kaggle.com/models/keras/gemma/keras/gemma_1.1_instruct_2b_en/3
> Please make sure you are authenticated if you are trying to access a private resource or a resource requiring consent.
> 

**To Reproduce**
[Link for notebook](https://colab.research.google.com/drive/12JsxcySoDLNgAU5t4gRptW9aqsx18AGu?usp=sharing)

**Expected behavior**
I expect to use the Gemma model without issues. I have kaggle json linked to correctly - this does not seem an authentication issue.

**Would you like to help us fix it?**
Yes please!

**Comment by sachinprasadhs** [comment]
@nashschool , I just checked and verified that everything is working as expected.

![image](https://github.com/keras-team/keras-nlp/assets/73069040/1c5910dd-85b6-44bc-848c-92c98a730daa)

**Comment by nashschool** [comment]
Sorry my bad, I had not requested for permission to use Gemma from Kaggle.

**Comment by venakgerardfaabshir-sys** [comment]
Hi, I get the same problem, and have consented to the license for Gemma, is there any other request for permission to use Gemma from Kaggle?
