### ISSUE TITLE
unable to diagnose OOM

### ISSUE THREAD

**Issue by josharian** [keras-team/keras-nlp#1628]
This is less a bug report than a cry for help. 😅 

I'm attempting a full (not lora) fine tune of gemma 2b, using 4x 4090s (and `keras.distribution.ModelParallel`), using the jax backend.

Each GPU has 24gb of ram, so 96gb total.

I can fine tune at sequence lengths up to ~4k with a batch size of 1 using SGD. I can't fine tune at all using AdamW, no matter how small I set `model.preprocessor.sequence_length`.

My (possibly wrong) back of the envelope suggests I should be able to use AdamW and/or increase my batch size and/or do gradient accumulation and/or use the full 8k sequence length.

I have attempted to diagnose the problem using the [jax memory profiler](https://jax.readthedocs.io/en/latest/device_memory_profiling.html). It claims I've only allocated 9.34gb, despite clearly being on the edge of OOMing, and no matter how I adjust the other parameters.

```
$ go tool pprof mem.pprof 
Type: space
(pprof) top10
Showing nodes accounting for 9.34GB, 100% of 9.34GB total
Dropped 64 nodes (cum <= 0.05GB)
      flat  flat%   sum%        cum   cum%
    9.34GB   100%   100%     9.34GB   100%  fit
         0     0%   100%     9.34GB   100%  <unknown>
         0     0%   100%     9.34GB   100%  error_handler
```

[jax-smi](https://pypi.org/project/jax-smi/) shows that being spread evenly across the 4 GPUs.

It appears that it is only accounting for the model's memory usage, not the optimizer's.

I've gone through all the [jax OOM debugging steps](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html), with no impact.

It appears that gradient checkpointing might (?) not be working well, as I see this logged:

```
W external/xla/xla/service/hlo_rematerialization.cc:2946] Can't reduce memory use below 15.59GiB (16741107601 bytes) by rematerialization; only reduced to 44.60GiB (47886805196 bytes), down from 44.85GiB (48159918356 bytes) originally
```

Anyway...I don't know what to try next, and I don't seem to have any tools I can use to tell me what allocations of what sizes are happening where and why. I vaguely suspect that the optimizer state is not being sharded across the GPUs...but I don't have any way to tell.

Any advice would be most welcome. ❤️

**Comment by SuryanarayanaY** [comment]
Hi @josharian ,

Just to understand more is this issue specific to only Jax backend ?

**Comment by josharian** [comment]
> Just to understand more is this issue specific to only Jax backend ?

Yes, insofar as I have only been able to try it with the Jax backend.

When I tried the tensorflow backend, I found that it didn't work with `keras.distribution.ModelParallel`, at least not out of the box:

```
Traceback (most recent call last):
  File "finetune_gemma.py", line 80, in <module>
    model_parallel = keras.distribution.ModelParallel(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/keras/src/distribution/distribution_lib.py", line 573, in __init__
    self._num_process = distribution_lib.num_processes()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'keras.src.backend.tensorflow.distribution_lib' has no attribute 'num_processes'
```

**Comment by mattdangerw** [comment]
@josharian is correct, model parallelism is only supported on the Jax backend.

One important thing to note is that Jax preallocates memory on GPU, so appearing to be on the verge of OOMing does not necessarily mean anything is wrong. https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

Using jax tools for debugging should give accurate actually GPU usage (the parts of the preallocation Jax is actually using), whereas things like `nvidia-smi` will just show the whole preallocation block.

However, all of that said, if things are OOMing when back of napkin math is showing things should easily fit, that's a sign something might be going wrong here. @josharian can you say any more about when thing OOM? Can you ever run fit without an OOM?

**Comment by josharian** [comment]
> jax tools for debugging should give accurate actually GPU usage

FWIW, they did not. See the pprof output in the OP.

> can you say any more about when thing OOM? Can you ever run fit without an OOM?

I have given up on keras for now. If/when I return to it, I'll add more detail.

I'll close this in the meantime, I guess.
