### ISSUE TITLE
Minor refactoring: cached MHA reimplements code already in base MHA

### ISSUE THREAD

**Issue by apehex** [keras-team/keras-nlp#1683]
Hey there!

I have a small improvement for the `CachedMultiHeadAttention` class.

The attention score and output calculations have been recoded in the child class while available in the base `MultiHeadAttention`.

For the sake of simplicity / maintainability / etc etc I propose to just call `_compute_attention`.

More specifically:

- lines [131](https://github.com/keras-team/keras-nlp/blob/v0.12.1/keras_nlp/src/layers/modeling/cached_multi_head_attention.py#L131) - 145 in C-MHA
- are implemented in [382](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/layers/attention/multi_head_attention.py#L382) - 434 of MHA

**Comment by apehex** [comment]
Also there are a few missing functionalities:

- add the missing arguments: `query_mask, value_mask, key_mask, attention_mask, return_attention_scores`
- update the `attention_mask` with `_compute_attention_mask`
- return the scores if the matching flag is on

Is there a compatibility issue?
Can I add them too?

**Comment by mattdangerw** [comment]
We still have a few users that are doing some weird Keras 2 stuff, and I think the signatures of `_compute_attention_mask` do not match across Keras 2 and Keras 3. So probably we can't land `query_mask, value_mask, key_mask, attention_mask` args and `_compute_attention_mask` right now (but soon!).

`return_attention_scores` should be fine to add.
