### ISSUE TITLE
cannot create URI for a fine-tuned Gemma model for Kaggle upload

### ISSUE THREAD

**Issue by wkambale** [keras-team/keras-nlp#1697]
When running the code below in Google Colab to fine-tune the Gemma 2B model, the runtime (A100 GPU on High-RAM) keeps disconnecting and keeps the cell running for forever:
```python
kaggle_username = userdata.get('KAGGLE_USERNAME')
model_name = "gemma"
variation_name = "new_variation_name" # new_variation_name is a placeholder

uri = f"kaggle://{kaggle_username}/{model_name}/keras/{variation_name}"
uri
```

This [Colab Notebook](https://colab.research.google.com/github/nkovela1/keras/blob/master/Kaggle_Keras_Gemma_I_O.ipynb) reproduces this bug. At the moment, I'm running a copy with a new dataset to fine-tune a new model.

The code above is expected to run successfully to be able to upload the new model to Kaggle with the code below:
```python
keras_nlp.upload_preset(uri, preset)
```

Note: The preset is saved a cell before the above code here:
```python
preset = "./new_variation_name"
gemma_lm.save_to_preset(preset)
```

**Comment by SamanehSaadat** [comment]
Hi @wkambale!

Thanks for reporting the issue and thanks for sharing a repro colab.

When I ran your colab, the upload cell completed successfully and printed these logs:
![image](https://github.com/user-attachments/assets/33284bd3-4606-4892-9cf5-b6e1c89af9a4)

The model is uploaded here: https://www.kaggle.com/models/smnsdt/gemma/keras/medical_gemma
(I only trained on a small subset of data (100 samples) but that shouldn't have any impact on the upload.)

Does that upload cell print logs at all? (I want to see if I can understand where it gets stuck! e.g. is it before the upload starts or in the middle of the upload?)

**Comment by SamanehSaadat** [comment]
Another thing that might be worth trying is to try to upload to Hugging Face Hub to see if the same issue happens. That can help us understand if the issue is on the Keras side or Kaggle side. 

To upload to Hugging Face, you can change your URI to `hf://<HF_USERNAME>/<MODEL>`.

**Comment by wkambale** [comment]
hi @SamanehSaadat,

i think (or realize) that the issue coud be [this](https://github.com/googlecolab/colabtools/issues/4701) and [this](https://github.com/googlecolab/colabtools/issues/4698). it seems Colab Pro and Colab Pro + users are experiencing runtime issues.

like i said, my hosted runtime (A100 GPU on High-RAM) keeps disconnecting and does not automatically reconnect which keeps the cell running for forever.

i'll try HF and see. thanks 👍

**Comment by SamanehSaadat** [comment]
I see! Thanks for sharing the links! If the issue is on Colab side, maybe we should wait for their response and test again when the issue is fixed.

**Comment by wkambale** [comment]
yeah, sure. thanks. i will share an update as soon as there's one.
