### ISSUE TITLE
Docstring improvements for 0.2 release

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#170]
We are getting ready to release an 0.2 version of the library along with public documentation on keras.io. Any improvements to our docstrings before launch is appreciated!

You can preview documentation that will launch with the following (this make a venv and keras-io clone in your current directory):

```shell
python3 -m venv keras-io-venv
source keras-io-venv/bin/activate
git clone https://github.com/keras-team/keras-io.git
cd keras-io
git fetch origin pull/859/head:keras-nlp-docs
git checkout keras-nlp-docs
pip install -r requirements.txt
cd scripts
python autogen.py make && python autogen.py serve
```

api docs: http://localhost:8000/api/keras_nlp/
landing page: http://localhost:8000/keras_nlp/

If you spot something in our API documentation that is incorrect or unclear, leave a comment here or open a PR to fix!

**Comment by aflah02** [comment]
Hey @mattdangerw 
This looks great!
There's something I noticed when I was checking out the Unicode Character Tokenizer the example corresponding to Detokenization with invalid bytes seems wrongly formatted and displayed. Not quite sure why though

<img width="425" alt="image" src="https://user-images.githubusercontent.com/72096386/167249661-2d4d40e3-31e3-46fb-b95b-dff60932c07e.png">

**Comment by mattdangerw** [comment]
This is a funny bug, but seems to be with keras.io rendering and not specific to our docs.

https://github.com/keras-team/keras-io/issues/874

**Comment by mattdangerw** [comment]
We can track that rendering bug on the linked issue. For now, 0.2 is out!
