### ISSUE TITLE
TransformerDecoder should support single inputs

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#182]
Currently TransformerDecoder must have both `encoder_inputs` and `decoder_inputs`, while for models like GPT2, only `decoder_inputs` is required. We should make a change to mark `encoder_inputs` as optional.

**Comment by chenmoneygithub** [comment]
@jessechancy Thanks!

**Comment by shivance** [comment]
Is this issue still looking for contributions ?
@chenmoneygithub @mattdangerw

**Comment by mattdangerw** [comment]
This is fixed!
