### ISSUE TITLE
Use preallocated buffer for text generation

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#188]
The current text generation implementation relies on tf.concat, which is not XLA compatible. Instead we can use a pre-allocated buffer to hold generated tokens. 

As we are currently using generation util mainly for demo/guide, we can revisit this issue when we decide to bake this util into model.

**Comment by mattdangerw** [comment]
This has been done in
https://github.com/keras-team/keras-nlp/pull/271
https://github.com/keras-team/keras-nlp/pull/300

Closing.
