### ISSUE TITLE
Add type annotations for TransformerEncoder and TransformerDecoder

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#19]
We would like to use type annotations in KerasNLP. We should add them for the encoder/decoder blocks...

https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/transformer_decoder.py
https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/transformer_encoder.py

**Comment by howl-anderson** [comment]
I am familiar with TensorFlow/Keras and the transformer theory and implementations (from the TensorFlow Model Garden). I would like to take this task and will send a PR later.

**Comment by mattdangerw** [comment]
Thank you! Please tag me for review!

**Comment by Stealth-py** [comment]
Hey! Is this issue still open?

**Comment by howl-anderson** [comment]
Yes, I'm still working on it. My city is on lockdown for more than one month because of COVID-19. It makes me have less time for this job. I'm sorry for the slow process. I will work hard for this, hopefully, send a PR within two weeks.

**Comment by Stealth-py** [comment]
Ah, alright. Stay safe!
