### ISSUE TITLE
Add a translation example on keras.io

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#190]
We should write a example very similar to the [Spanish English translation example](https://keras.io/examples/nlp/neural_machine_translation_with_transformer/) already on keras.io.

We can use the same dataset, and same basic model structure, but we should use KerasNLP components for tokenization, embedding, encoder and decoder blocks.

Also once we have translations metrics (Rogue and Bleu), this would be a great place to showcase using them.

**Comment by abheesht17** [comment]
Hello, @mattdangerw! As discussed, I'd be glad to take this up. Thanks! :)

**Comment by abheesht17** [comment]
Linking the PR here: https://github.com/keras-team/keras-io/pull/890

**Comment by abheesht17** [comment]
Completed: https://github.com/keras-team/keras-io/pull/890.

**Comment by abheesht17** [comment]
Completed: https://github.com/keras-team/keras-io/pull/890.
