### ISSUE TITLE
Why does the docstring say vocab size should be no larger than 999?

### ISSUE THREAD

**Issue by kvarekamp** [keras-team/keras-nlp#193]
https://github.com/keras-team/keras-nlp/blob/e3adddaa98bbe1aee071117c01678fe3017dae80/keras_nlp/layers/token_and_position_embedding.py#L30

Seems like a very small vocab to me

**Comment by mattdangerw** [comment]
Thanks, good catch! Yeah that's not a real requirement. The guide we just published uses the layer with a 30k vocabulary (and there is not hard limit that I'm aware of, just memory constraints).

Not sure how that got there but let's remove!
