### ISSUE TITLE
Integrate TransformerEncoder into the BERT example

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#20]
We should update https://github.com/keras-team/keras-nlp/tree/master/examples/bert to use `keras_nlp.layers.TransformerEncoder`.

**Comment by mattdangerw** [comment]
This is open for contributions if anyone would like to pick it up!

**Comment by mattdangerw** [comment]
@chenmoneygithub assigning you again as it sound like you are actively working on this!

**Comment by jayam30** [comment]
hey i want to take this up
