### ISSUE TITLE
Add a `special_tokens` argument in WordPieceTokenizer (and potentially, other tokenizers)

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#209]
Consider the following code snippet:

```
input_text = "[CLS] KerasNLP is awesome! [SEP]"
eng_tokenizer = keras_nlp.tokenizers.WordPieceTokenizer(
    vocabulary="eng_vocab.txt",
    lowercase=False, split_pattern=" ",
    sequence_length=3)
eng_tokenizer(input_text)
```

```
>>> <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 101,  100, 2003], dtype=int32)>
```

```
eng_tokenizer.detokenize(eng_tokenizer(input_text))
```

```
<tf.Tensor: shape=(), dtype=string, numpy=b'[CLS] [UNK] is'>
```

The `[SEP]` token gets chopped off. While it is fine that other tokens got chopped off (since we have set maximum sequence length as 3), the `[SEP]` token should remain since it is a special token. Maybe, if we add an argument `special_tokens`, we can be mindful of the tokens to be preserved during truncation.

**Comment by chenmoneygithub** [comment]
To me the purpose of this `special_tokens` is unclear - basically in your use case, `special_tokens` are those tokens we want to keep even if out of the range of `sequence_length`. Imagine you have a batch with two sequences ["Have a nice day [SEP]", "You too [SEP]" ], and we set `sequence_length=3` and `special_tokens=["[SEP]"]`, then we will end up with ["Have a nice [SEP]", "You too [SEP]"] because for the first sequence we explicitly want to keep "[SEP]". 

Personally I would rely on users to set the right `sequence_length`. @mattdangerw Matt, your idea?

**Comment by abheesht17** [comment]
We will end up with `["Have a [SEP]", "You too [SEP]"]` if we have a sequence length of 3.


The reason for preserving `special_tokens` this is as follows:
```
>>> vocabulary = ["[UNK]", "[START]", "[END]", "it", "is", "fun", "contributing", "to", "keras_nlp", "loads", "of",]
>>> wp = keras_nlp.tokenizers.WordPieceTokenizer(vocabulary=vocabulary, sequence_length=5, split_pattern=" ", lowercase=False)
```

We have two cases. If the length of the tokenised sequence is less than the desired length, the `[END]` token will be preserved. 
```
>>> sentence = "[START] it is [END]"
>>> wp(sentence)
<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 4, 2, 0], dtype=int32)>
>>> wp.detokenize(wp(sentence))
<tf.Tensor: shape=(), dtype=string, numpy=b'[START] it is [END] [UNK]'>
```


However, if the length of the tokenised sequence is greater than the desired length, the `[END]` token will be chopped off.

```
>>> sentence = "[START] it is fun contributing to keras_nlp [END]"
>>> wp(sentence)
<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 4, 5, 6], dtype=int32)>
>>> wp.detokenize(wp(sentence))
<tf.Tensor: shape=(), dtype=string, numpy=b'[START] it is fun contributing'>
```

Now, the above examples just have one sample. Usually, users will pass a batch at a time:

```
>>> sentences = ["[START] it is [END]", "[START] it is fun contributing to keras_nlp [END]"]
>>> wp(sentences)
<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 3, 4, 2, 0],
       [1, 3, 4, 5, 6]], dtype=int32)>
>>> wp.detokenize(wp(sentences))
<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'[START] it is [END] [UNK]', b'[START] it is fun contributing'],
      dtype=object)>
```

Won't it be a bit of a hassle for the user to loop over every batch, check whether `[END]` has been preserved, and if it hasn't been, **replace** the last token with `[END]`? The user can't add `[END]` directly; the last token has to be replaced in order to preserve sequence length.

As for why the user may not be able to set the correct sequence length - suppose the model which the user is using has a token limit of 512 [like BERT]. In that case, the user cannot set the sequence length to `max([len(sequence) for sequence in all_sequences_in_dataset])` and will have to set it to 512, in which case, the user will have to write additional logic for preserving special tokens.

**Comment by mattdangerw** [comment]
See also https://github.com/keras-team/keras-nlp/issues/181

In general I don't think we should be trying to support string manipulation like this to do start end token packing or padding. It is always going to be fragile. It is generally a better idea to add ids after tokenization. The [BERT packer layer](https://github.com/keras-team/keras-nlp/pull/88/files), which is blocked on a bug in TFText, show's the idea here.

This is a key point for our guides and examples. We need to make sure we aren't promoting string manipulation like this which lands you in the questions in the linked issue above. Why are brackets being split? How do I do a regex to avoid this, what about bracket used normally in regular English?

For the reverse, detokenization, I think we should just make it easy to specify what tokens you would like to strip. By default, that's probably the padding token. But you could also want to string start and end tokens before detokenization as well.

Do we have a use case where the "packing" cannot be done post tokenization? If we do that might be a more concrete place to design around.

**Comment by abheesht17** [comment]
This issue has been solved after adding "Packer" layers. Let's close this.

**Comment by mattdangerw** [comment]
Sounds good! Thanks.
