### ISSUE TITLE
Adding Docs for Util Functions to keras.io

### ISSUE THREAD

**Issue by aflah02** [keras-team/keras-nlp#210]
Currently the docs for the util functions aren't displayed on keras.io, is there a reason for this?
I think it would be great if they can be displayed [here](https://keras.io/api/keras_nlp/) as well!

**Comment by abheesht17** [comment]
I think the docs are updated with every release. Not sure though.

**Comment by mattdangerw** [comment]
We should only document the utils that we are exporting in an `__init__.py`. Anything not can really be considered package private currently. That's true for the utility to convert tensors to strings. We aren't really sure how we want to expose that (in tokenizer or separately), so we have not included it in `__init__.py` yet.

That's not true of `greedy_search` though, as soon as we cut our next release, we should make sure to document that!
