### ISSUE TITLE
Stop Word Dropout Layer - Data Augmentation

### ISSUE THREAD

**Issue by aflah02** [keras-team/keras-nlp#215]
This is an extension to the [Random Deletion Layer](https://github.com/keras-team/keras-nlp/issues/152). I currently plan to use this issue to link the next PR which will add Stop Word Deletion specifically to the Random Deletion Layer as a parameter. I can also see this being a stand alone layer but probably the former is better!

**Comment by mattdangerw** [comment]
Can you explain more of how this will work? This will be a layer that randomly deletes stop words? Or deterministically drops stopwords?
