### ISSUE TITLE
StartEndPacker and MultiSegmentPacker should support 2D tensors

### ISSUE THREAD

**Issue by jessechancy** [keras-team/keras-nlp#238]
**Describe the bug**
StartEndPacker and MultiSegmentPacker should support 2D tensors, in addition to 1D and RaggedTensors. It currently gives an error message for 2D tensors.

**Expected behavior**
Packers should have their desired behaviors work on 2D tensors too.

**Would you like to help us fix it?**
Yes

**Comment by abheesht17** [comment]
Hello, @jessechancy! Discussed this error with @mattdangerw and @chenmoneygithub yesterday. Basically, the error which you are talking about is thrown when we execute the layer eagerly. This line is the cause: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/start_end_packer.py#L109. I tried replacing this line with `inputs = tf.ragged.constant(inputs)` but it threw some other error.

**Comment by jessechancy** [comment]
The tf.shape(tf.ragged.constant(...)) only throws an error in tf 2.8, it's fixed in tf 2.9. Also, the packers have been updated to support 2D dense tensors, so I will close this issue.
