### ISSUE TITLE
Add type annotations to the bert example

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#24]
We would like to use type annotations in KerasNLP. We should add them to the BERT example code in https://github.com/keras-team/keras-nlp/tree/master/examples/bert

**Comment by howl-anderson** [comment]
I am familiar with TensorFlow/Keras and the BERT theory and implementations (from the TensorFlow Model Garden). I would like to take this task and will send a PR later.

**Comment by mattdangerw** [comment]
Thank you! Please tag me for review!

**Comment by aflah02** [comment]
Hey
Is this issue still open?

**Comment by howl-anderson** [comment]
Hi @aflah02, sorry for the slow progress. I am still working on adding type annotations to the BERT.

**Comment by aflah02** [comment]
Hey @howl-anderson 
That's cool, no need to say sorry I was just looking around :) and must've missed that you're already assigned

**Comment by mattdangerw** [comment]
Keras as a whole is not pursuing type annotations at the moment.
