### ISSUE TITLE
Use Graph Ops to Implement BLEU Score

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#247]
Currently, we use `tf.py_function` to implement BLEU score. This is because the graph mode implementation which we tried out wasn't very efficient. This notebook compares the two approaches: https://colab.research.google.com/drive/1TZ8XnrmMcU8ZE2J-3amb44p-U-hxER53?usp=sharing.

We believe that the slowdown is mainly because of the code snippet which finds the common n-grams between the reference and the translation, and the part which finds the union of the sets of n-grams of all references per sample. In graph mode, we don't have a hashmap/dictionary-like data structure. We do have [`tf.lookup.experimental.MutableHashTable`](https://www.tensorflow.org/api_docs/python/tf/lookup/experimental/MutableHashTable), but when we tried using it, we noticed that keys persist across different model instances! We resorted to using a combination of `tf.sets.intersection` and `tf.gather` to implement the above operation.

Roughly speaking, the graph implementation takes 3-5 seconds, whereas the Python implementation takes 0.3-0.6 seconds (for a batch of two samples). Going forward, the plan is to implement BLEU in TF Text.

CC: @mattdangerw, @chenmoneygithub

**Comment by mattdangerw** [comment]
Closing, as these tf metrics are no longer a focus for us. Can always re-open if need be!
