### ISSUE TITLE
Add a model proto training utility for sentence piece

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#249]
Along with https://github.com/keras-team/keras-nlp/issues/248, we should add a utility to train a model proto for sentence piece. This can leverage the sentencepiece pip package to run their trainer.

We should not expose most of the option the sentencepiece trainer has, the goal will be for this to cover the majority of use cases, with advanced users till using the sentencepiece pip package directly.

**Comment by mattdangerw** [comment]
@aflah02 here is the sentencepiece one!

**Comment by aflah02** [comment]
Thanks @mattdangerw 😁
