### ISSUE TITLE
Add a discussion tab to `keras-nlp`?

### ISSUE THREAD

**Issue by innat** [keras-team/keras-nlp#257]
**Is your feature request related to a problem? Please describe.**

I think it would be nice to open a discussion tab for keras-nlp, (like we've in [keras-cv](https://github.com/keras-team/keras-cv/discussions)). Through this contributors can share ideas for the improvement of the API.

**Comment by mattdangerw** [comment]
That sounds good to me! Let me check with some other folk and enable this if everyone is onboard.

**Comment by chenmoneygithub** [comment]
I like the idea too, let's make it!
