### ISSUE TITLE
Decoding Functions Not Working when `jit_compile = True`

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#277]
When `jit_compile` is set to True, the decoding functions do not work. We wish to add support for the same in the future.

Error: https://p.ip.fi/2TNt

**Comment by mattdangerw** [comment]
Thanks for opening!

**Comment by chenmoneygithub** [comment]
Once you pushed the new version, we may want to test on TPU as well. I will add some tests.

**Comment by mattdangerw** [comment]
This is mostly done, we just need some changes for beam search @abheesht17 is currently working on. Once beam search gains support, we can close this.
