### ISSUE TITLE
Add warning about Conda in our README

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#298]
I recently found out that hard way that `tensorflow-text` is incompatible with Conda (see [issue](https://github.com/tensorflow/text/issues/644)). Sitting downstream of this library makes `keras-nlp` also incompatible with Conda. We should add a note to our README warning users to use `pyenv` for version management.

**Comment by jaygala223** [comment]
Hi @jbischof, I have submitted a PR for this issue. Please let me know if there's anything that should be added/deleted. Thanks!

**Comment by mattdangerw** [comment]
Actually @jbischof I think this is a common misconception! Conda is both a tool for setting up a python environment, and also packages things directly. The thing to be careful about is installing `tensorflow` from a conda source, and `tensorflow_text` from pip. This leads to binary incompatibilities. The recommend approach is actually to install `tensorflow` and `tensorflow_text` from pip, and only use conda for the lower level dependencies such as CUDA.

Basically the approach we follow is the same as core TensorFlow (https://www.tensorflow.org/install/pip), and we should continue to follow the upstream guidance here.

For anyone interested, the reason to use conda is mainly CUDA libraries. With conda, you can only carry NVIDIA drivers on your base system, and run different versions of CUDA to match your tf, pytorch or jax install. With pyenv you can't! So you need to reinstall CUDA whenever you flip between frameworks and framework versions. A big pain.
