### ISSUE TITLE
StartEndPacker Errror failed to use

### ISSUE THREAD

**Issue by GLOMQuyet** [keras-team/keras-nlp#301]
**Describe the bug**

ValueError: Exception encountered when calling layer "start_end_packer_14" (type StartEndPacker).

TypeError: object of type 'RaggedTensor' has no len()

**To Reproduce**

https://colab.research.google.com/drive/1y7JifaoLkNmLymyHV96MwkzcH53TImf9?usp=sharing
**Expected behavior**

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
    array([[ 1,  5,  6,  7,  2,  0],
           [ 1,  8,  9, 10, 11,  2]], dtype=int32)>
**Additional context**

**Would you like to help us fix it?**

**Comment by abheesht17** [comment]
@GLOMQuyet, I believe this is happening because Colab has an older version of TensorFlow (2.8.2) installed. We need to uninstall it first.

Please check out this notebook: https://colab.research.google.com/drive/1_owl3mwP7VwSsfeLKFKiBmVHqu0DoL4A?usp=sharing

Hope this solves your issue! :)

**Comment by GLOMQuyet** [comment]
thankyou !
