### ISSUE TITLE
Support CJK character splitting for WorkPiece tokenizer

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#307]
Looking at the original BERT tokenizer code for [chinese characters](https://github.com/google-research/bert/blob/master/tokenization.py#L251), we should be able to add support for CJK languages by splitting on these characters as a pre-tokenization for WordPiece.

We need to do a little thinking on whether this can reasonably by added to the default split behavior for the word piece tokenizer, or if we need to gate this behind a flag (`split_on_cjk=True`).

Adding this feature to our tokenizer will unblock supporting Chinese language BERT.

**Comment by abheesht17** [comment]
Would like to take this up!
