### ISSUE TITLE
Rename `models.Bert()` to `models.BertCustom()`

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#309]
### Discussed in https://github.com/keras-team/keras-nlp/discussions/305

<div type='discussions-op-text'>

<sup>Originally posted by **jbischof** August 23, 2022</sup>
When prototyping our model API in PR #288 we were following the example of `keras-cv`. They have `DenseNet` and `DenseNet121` and we have `Bert` and `BertBase`. Unfortunately the convention of naming an architecture "base" in NLP makes these names confusing so @mattdangerw and I have discussed changing `models.Bert()` to `models.BertCustom()` for clarity.

I think "custom" is a reasonable modifier to indicate that `BertCustom` is customizable in contrast to `BertBase` and upcoming arches like `BertLarge`. Thoughts?</div>

**Comment by mattdangerw** [comment]
Sounds good to me!

Everything feels slightly awkward, but overall I think this is better than the symbol named `Bert` being the niche use case compared to `BertBase` and `BertLarge`.
