### ISSUE TITLE
[Tracking] Performance optimizations for library

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#323]
### Discussed in https://github.com/keras-team/keras-nlp/discussions/322

* [`mixed_precision`](https://www.tensorflow.org/guide/mixed_precision)
* [`xla`](https://www.tensorflow.org/xla/tutorials/jit_compile)
* Documentation for performance optimizations

**Comment by mattdangerw** [comment]
Opened two more specific issue for this w.r.t. our BERT/RoBERTa models.

 - xla testing for bert - https://github.com/keras-team/keras-nlp/issues/325
 - mixed precision for bert - https://github.com/keras-team/keras-nlp/issues/326
