### ISSUE TITLE
Add XLA testing for BERT and RoBERTa models

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#325]
We should check that BERT and RoBERTa models we have just checked in work with XLA compilation today.

We should add a unit test for both models which:
 - Compiles a model with both jit_compile true/false in a parameterized test
 - Calls `model.predict()` on some random inputs.

**Comment by mattdangerw** [comment]
This goes along with the meta tracking issue https://github.com/keras-team/keras-nlp/issues/323

**Comment by mattdangerw** [comment]
@abheesht17 this is a small one, but would you be interested in knocking this out? As you just did the same type of test for our generative utils?

**Comment by abheesht17** [comment]
Will do!
