### ISSUE TITLE
Validate bert pretraining on new code changes

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#362]
We have made a number of changes to our bert modeling code of late.

Primary changes are https://github.com/keras-team/keras-nlp/pull/288 and https://github.com/keras-team/keras-nlp/pull/360

We should re-run an entire pretraining job for the base variant, and make sure we are still converging with good performance.

**Comment by jbischof** [comment]
Would love to see this incorporated with our new preprocessors as well (#343)!

**Comment by jbischof** [comment]
Long term BERT should also be our first e2e pretraining example using the model API rather than a bunch of custom code.
