### ISSUE TITLE
Specify vocabulary to BertPreprocessing using a checkpoint name

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#364]
Currently the vocabulary is specified directly to BertPreprocessor, for example `'uncased_en'`. However, going forward we want to request the vocabulary associated with a checkpoint rather than knowing what vocab the checkpoint used.

See discussion on #361

**Comment by mattdangerw** [comment]
This is fixed!

**Comment by jbischof** [comment]
Yes, fixed by #390
