### ISSUE TITLE
Create single mid-level API `Bert()` for architecture routing

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#369]
As the BERT API is reaching maturity we can see that much of our functionality relies on a architecture having a config-in-code like `BertTiny` ([gh](https://github.com/keras-team/keras-nlp/blob/e7889d65d708b44905ef8181377d702ef8163e02/keras_nlp/models/bert.py#L668)). Most critically, it is not possible for us to load weights from the user or one of our checkpoints unless we know which arch class to use.

In #361 we introduce unique string names for each model, but the responsibility to instantiate right class for a requested backbone is left to the original caller like `BertClassifier`. Instead let's make a mid-level API to handle all class routing and expose it in the API.

Example usage:
```python
# Load the 'bert_base_uncased_en' checkpoint into the BertBase class
Bert('bert_base_uncased_en')
# Give a random graph with the Base arch
Bert(arch='BertBase')
# Load weights that I trained/fine-tuned using the Base arch
Bert('mycheckpoint.h5', arch='BertBase')
```

This function will be called by 
```python
BertClassifier('bert_base_uncased_en', num_classes=4)
```
to get a backbone class with the requested weights loaded.

Finally, with this exposed as `keras_nlp.models.Bert` let's remove the symbol `keras_nlp.models.BertCustom` from the init since it is not very useful to the end user.

**Comment by mattdangerw** [comment]
Part of me would be tempted to hold off on this for now. I don't really like `Bert(arch='BertBase')`--it feels like an anti-pattern to expose a classname as a parameter in an exposed API. Fine if we are doing that behinds the scenes, but signing up for that in user facing code makes me a little more wary.

It also seems unclear what level to expose something like this. If we head down the checkpoint ID path, it seems just as defined to have a `BackboneModel('bert_base_uncased_en')` or  `GenericModel('bert_base_uncased_en')` class that infers any model's classname from an ID. Why do it at the Bert level?

**Comment by mattdangerw** [comment]
One thing that seems unclear above... If we are removing `BertCustom` does that mean that `keras_nlp.models.Bert` would contain all the hyperparameters like `num_layers`? Or are you proposing we remove entirely the ability to make a `Bert` with custom hypers?

**Comment by jbischof** [comment]
Good point about this potentially working at many levels with the single string id. Why not `GetMeThatModel('bert_base_uncased_en')? I think this needs more thought.

Part of the confusion is the (in my book) unfortunate pattern of wanting the user to be able to load their own model as well. This leads to silly patterns like the `arch` argument. But I digress.

I may add this as a private util later as we add more tasks, but not urgent. Closing for now.
