### ISSUE TITLE
Remove `tensorflow/text` as hard dependency

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#381]
While critical for most of our usecases, `tf-text` requires custom tf ops that make installation impossible on non-linux devices and is making simple tasks like compiling API docs more challenging than it needs to be.

Instead, we will ask the user to install the dependency if it is not available.

NOTE: we've had stability issues in the past when the version of `tf-text` and `tensorflow` does not agree. We will need to a way to enforce this.

**Comment by mattdangerw** [comment]
Put up a solution that I think represents the best setup we can have right now.

This fixes building keras.io on MacOS, give an experimental path to developing KerasNLP on MacOS, and fix stability issues with continuous testing by pinning tf versions.

Hopefully, as M1 becomes better supported by the entire tf ecosystem, we can drop any special casing on MacOS in the future.
