### ISSUE TITLE
BertPreprocessor has confusing behavior on lists of strings

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#396]
Now `BertPreprocessor` has confusing UX on batch input, mainly because we combine strings together (like NSP). We should be clear on our user journey on the following input types:
1) a string: "This is a string"
2) a list of string: ["holy", "geez"]
3) a list of list of strings [["holy"], ["geez"]]
4) a 1D tensor: tf.Tensor(b"This is a string")
5) a 2D tensor of shape batch * 1: tf.Tensor([["holy"], ["geez"]])
6) a 2D tensor of shape batch * 2: tf.Tensor([["holy", "geez"], ["holy", "geez"]])

One question we need to resolve is - do we default to string combination, or default to treat input as batch data?

**Comment by mattdangerw** [comment]
What we are currently doing now is probably the simplest code wise. We assume the outermost `list` or `tuple` always indicates multiple sequences. Here's the current code
```python
if not isinstance(inputs, (list, tuple)):
    inputs = [inputs]
inputs = [self.tokenizer(x) for x in inputs]
```

However, I agree it's confusing. What we probably want is this.

```python
# Always convert raw inputs to tensors first.
preprocessor = BertPreprocessor(...)
preprocessor("hi there") == preprocessor(tf.consant("hi there"))
preprocessor(["foo", "bar"]) == preprocessor(tf.consant(["foo", "bar"]))
# If you want multiple sequences, convert to multiple tensors yourself.
preprocessor((tf.constant("foo"), tf.constant("bar"))  # Single combined sequence.
preprocessor((np.array("foo"), np.array("bar"))  # Single combined sequence.
```

This will require a little more code I think. But is nicely parallel with things like the `tf.nest` module. And gives a simple user model. Raw inputs will first be converted to tensor, then passed to your layer. Tensorized inputs will not be touched.

**Comment by mattdangerw** [comment]
BTW, I don't like the idea of adding an explicit argument indicating multiple sequences, e.g. `BertPreprocessor(..., pack_multiple=True)`, because we should also apply the same fix we do here to the `MulitSegmentPacker` layer for consistency.

`MultiSegmentPacker(..., pack_multiple=True)` would be just weird.
