### ISSUE TITLE
Typo in TransformerEncoder doc-string

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#41]
Noticed a minor issue (typo) in the doc-string of the TransformerEncoder Layer: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/transformer_encoder.py.

[Line 46](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/transformer_encoder.py#L46)
[Line 50](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/transformer_encoder.py#L50)
[Line 55](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/transformer_encoder.py#L55)

It should be "encoder" instead of "decoder". I've opened a PR.

P.S. Not exactly a feature request, but not exactly a bug either...so, didn't know which category to put this issue under :P

**Comment by chenmoneygithub** [comment]
Thanks for reporting the issue and writing the PR! PR is approved.
