### ISSUE TITLE
Add a RoBERTa preprocessing layer

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#411]
Now that we have landed the `BytePairTokenizer`, we should be able to land the preprocessing for the RoBERTa model, modeled after the `BertPreprocessor` layer.

**Comment by mattdangerw** [comment]
See these files as a template:

https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_preprocessing.py
https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_preprocessing_test.py

Since we are not yet distributing weights for RoBERTa, the `from_preset` static constructor can simple return a `NotImplementedError`.

**Comment by abheesht17** [comment]
Blocked on #417.

**Comment by abheesht17** [comment]
Working on this. Will stack the PR on top of #417.
