### ISSUE TITLE
Add a GPT-2 preprocessing layer

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#412]
Now that we have landed the BytePairTokenizer, we should be able to land the preprocessing for the GPT-2 model.

**Comment by mattdangerw** [comment]
The BERT preprocessing layers can offer a rough inspiration. The "packing" will likely have to be slightly different, as GPT will generally be used generatively for a single sequence.

https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_preprocessing.py
https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_preprocessing_test.py

Since we are not yet distributing weights for GPT-2, the from_preset static constructor can simple return a NotImplementedError.

**Comment by abheesht17** [comment]
Blocked on #418.

**Comment by abheesht17** [comment]
Starting work on this. Will create a stacked PR on top of #418.

**Comment by mattdangerw** [comment]
Fixed!
