### ISSUE TITLE
Add a DistilBertClassifier model

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#413]
We should add a `DistilBertClassifier` based on the `BertClassifier` model. This will wrap the `DistilBert` model with a classification head.

**Comment by mattdangerw** [comment]
See the following as a template:

https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_tasks.py
https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_tasks_test.py

It will probably be easier to base any work for this on top of https://github.com/keras-team/keras-nlp/pull/406, or wait for it to land.

**Comment by abheesht17** [comment]
Taking this up
