### ISSUE TITLE
Add a XLMRobertaClassifier model

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#414]
We should add an `XLMRobertaClassifier` based on the `BertClassifier` model. This will wrap the `XLMRoberta` model with a classification head.

**Comment by mattdangerw** [comment]
See the following as a template:

https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_tasks.py
https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_tasks_test.py

It might be easiest to wait for https://github.com/keras-team/keras-nlp/issues/405 to start on this.

**Comment by abheesht17** [comment]
Working on this.
