### ISSUE TITLE
Naming inconsistency between Gpt2 and XLMRoberta

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#416]
We handle case differently in our current naming for `Gpt2` and `XLMRoberta`. We should align on either:
 - `XLMRoberta` and `GPT2`
 - `XlmRoberta` and `Gpt2`

Once we decided on the naming we want, this can just be a simple rename. We should probably do this before the next major release.

**Comment by mattdangerw** [comment]
This also applies to `MLMMaskGenerator` and `MLMHead`.

I actually somewhat like the camel case always approach, it is more readable. In `MLMMaskGenerator` it is really hard to tell where the acronym ends the next word begins. And the mapping to a `under_score.py`  filename is unclear.

So I might propose:
 - `XlmRoberta`
 - `Gpt2`
 - `MlmHead`
 - `MlmMaskGenerator`
 - `DistilBert`
 - `Deberta`

This would require updating the current symbols:`XLMRoberta`, `XLMRobertaPreprocessor`, `MLMMaskGenerator` and `MLMHead`.

**Comment by jbischof** [comment]
Good call @mattdangerw! This is also consistent with `keras_nlp.models.Bert` instead of `keras_nlp.models.BERT`. Why are you SHOUTING!?

Great candidate for a "good first issue"

**Comment by sampathweb** [comment]
I can take this.
