### ISSUE TITLE
Please release a new version of keras-nlp with BPE tokenizer to pypi.

### ISSUE THREAD

**Issue by piEsposito** [keras-team/keras-nlp#442]
That would help unblock some projects that depend on it without having to copy-paste code or installing from Github master.

**Comment by chenmoneygithub** [comment]
@piEsposito Hi! We are working on 0.4 release, which is expected to happen in several weeks from now. Please stay tuned!

**Comment by chenmoneygithub** [comment]
@piEsposito Plan changed! We are fine with cutting a branch specifically to release the BPE, but there is a concern from our side. I replied to this thread: https://github.com/huggingface/transformers/issues/19992

**Comment by mattdangerw** [comment]
I think we can close this, as the release is now out. But any other bugs found with the tokenizer, please do open an issue here! Thank you!
