### ISSUE TITLE
BERT fails on TPU when jit_compile=True

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#443]
See this gist for the repro.
https://colab.sandbox.google.com/gist/mattdangerw/7b8ba7f942ea9e8e912b4e21cdf9bbf9/tpu-bug-jit_compile-true.ipynb

TPU training works fine when `jit_compile=False`. When `jit_compile=True` we hit a weird bug.

```
InvalidArgumentError: 9 root error(s) found.
  (0) INVALID_ARGUMENT: {{function_node __inference_train_function_16010}} Reshape's input dynamic dimension is decomposed into multiple output dynamic dimensions, but the constraint is ambiguous and XLA can't infer the output dimension %reshape.21 = f32[16,128,512]{2,1,0} reshape(f32[2048,512]{1,0} %transpose.6), metadata={op_type="Reshape" op_name="bert_classifier/backbone/transformer_layer_0/dense/Tensordot"}. 
	 [[{{node TPUReplicate/_compile/_8571286824872389582/_6}}]]
```

**Comment by mattdangerw** [comment]
It looks like this is an issue with our `TransformerEncoder`, if so this is definitely worth a look, as it would affect every model we have release today.

**Comment by chenmoneygithub** [comment]
A hacky way is to do `drop_remainder=True` to force the batch dim to be stable.

Actually it is a bit weird to do `jit_compile` on TPU jobs, as it always turns on XLA. It could cause unexpected behavior to explicitly do `jit_compile` on TPU. I tried the same code on GPU and it works well.

**Comment by chenmoneygithub** [comment]
Followup - checking with TPU/XLA team, a general approach is not to have `jit_compile` annotation for TPU training, as it creates strange behavior. I will go ahead and make a fix on core Keras.

**Comment by mattdangerw** [comment]
@chenmoneygithub thanks! So basically we can always pass `jit_compile=True` here, and the option will be ignored by core Keras?

**Comment by chenmoneygithub** [comment]
Yes, we should be good!
