### ISSUE TITLE
Expose the standalone tokenizer for XLM-Roberta

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#459]
Following on with https://github.com/keras-team/keras-nlp/pull/449, we would like to expose a standalone, pure string -> int sequence tokenizer for our models. This will allow for any possible packing and padding, de-tokenization, etc.

We actually recently added a tokenizer for XLM-Roberta in https://github.com/keras-team/keras-nlp/pull/428, but we should now expose it.

A few steps:
 - Add the `XLMRobertaTokenizer` to `models/__init__.py`.
 - Have `XLMRobertaPreprocessor` take in a tokenizer, and serialize it properly in get_config/from_config (https://github.com/keras-team/keras-nlp/pull/449 shows this).
 - Add a documented property to access the tokenizer from the preprocessor layer.
 - Track the special token ids on the tokenizer class, and use these ids from the preprocessor like `self.tokenizer.start_token_id`.
 - Add documentation and tests!

**Comment by abheesht17** [comment]
Working on this.
