### ISSUE TITLE
Add a byte pair encoding (BPE) tokenizer layer

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#46]
We would like to add a BPE tokenizer (used by gpt-2, roberta and others). This ideally should be configurable to be compatible with the actual tokenization used by gpt-2 and roberta, and run inside a tensorflow graph.

**Comment by abheesht17** [comment]
Nice! Should I draw up a rough implementation and share a Colab notebook?

**Comment by mattdangerw** [comment]
@abheesht17 you are definitely welcome to help with this! This will require some diving into other libraries, to understand the support we have today.

**Comment by abheesht17** [comment]
Great, will do 👍🏼

**Comment by abheesht17** [comment]
Hey, @mattdangerw. I went through this [issue](https://github.com/tensorflow/text/issues/763). So, essentially, this is what you want me to do:

1. Use the [SentencePiece library](https://github.com/google/sentencepiece), and configure it so as to train a byte-level BPE tokeniser. Use a small text corpus for training.
2. Use the `.model` file obtained after training and pass it to [TensorFlow Text's SentencePiece tokeniser](https://github.com/tensorflow/text/blob/master/tensorflow_text/python/ops/sentencepiece_tokenizer.py) class.
3. Now, use the same corpus and train Hugging Face's GPT-2 Tokeniser, and check whether the vocabulary obtained is similar, and check the output on a few input samples.

Is this correct?

**Comment by mattdangerw** [comment]
I'm not sure we need to actually train a sentence piece model, though that might help understand things.

Basically, the public API we can rely on that might give us the op support we need is tf text's [SentencepieceTokenizer](https://www.tensorflow.org/text/api_docs/python/text/SentencepieceTokenizer), but that takes a sentence piece [model proto](https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto) as input.

End users will want probably want to use this layer with "vocab json" and "merges txt" files provided by official gpt/roberta githubs or huggingface. We can keep thinking about the file format we would want, but asking end users to construct a sentence piece model is probably a non-starter.

So, the question we could try to answer is can we manually construct a sentence piece model proto from gpt vocab and merge files in a way that's compatible. If so, we could build this layer on top of the existing tf text API, and not rule out more direct support from tf text in the future. If not, we will need to go back to the drawing board a little bit and figure out how to get op level support here.

So putting that into a list:
  1. Start with a vocab and merges files for say gpt2.
  2. Generate some correct output for some sample text (probably easiest to use huggingface here? could also try using the tokenizer impl from gpt2 github)
  3. Try building a tf text SentencepieceTokenizer from those files that matches the real tokenizer output.

It may turn out we are more blocked here than we think from https://github.com/tensorflow/text/issues/763, but this would be the way to find out.

**Comment by abheesht17** [comment]
Ah, understood. Thanks for clarifying!

**Comment by abheesht17** [comment]
Some useful articles about how Hugging Face tokenises the input text (given `vocab.txt` and `merges.txt`):

https://github.com/huggingface/transformers/issues/1083#issuecomment-524303077
https://github.com/huggingface/transformers/issues/4777

**Comment by abheesht17** [comment]
Hey, @mattdangerw. Sorry for the delay, forgot about it. I opened an issue on the SentencePiece repository: https://github.com/google/sentencepiece/issues/739. The author of the repo mentions this: "manual model modification/creation is totally unsupported."

However, Looks like we may be able to add tokens from the vocab to the `pieces` attribute. I don't think they have Python wrappers/APIs for adding "pieces". However, they do have a function in C++, `AddPieces`. See this unit test: https://github.com/google/sentencepiece/blob/bc53923a9147dc8ffa54034c8ed774de78cc4d39/src/bpe_model_test.cc#L52. I'll try to use this function, and reproduce the output we get using HF. Give me a day or two.

**Comment by aleemkhan62** [comment]
Hi All,

Just curious if anyone has found any sort of work around for this issue. My conclusion after reading related issues is that its not currently possible to incorporate popular BPE tokenizers (roberta/GPT2) within tensorflow-text pipelines?

**Comment by chenmoneygithub** [comment]
@aleemkhan62 Currently you can use BPE via tf_text.SentencePieceTokenizer only if you have a pretrained model proto. We are looking into a better solution on it! please stay tuned, thanks!

**Comment by mattdangerw** [comment]
To add a little more color for others finding this issue, you can train a BPE-style vocabulary with [sentecepiece](https://github.com/google/sentencepiece) today, and a sentencpiece model can be used with tensorflow text, or the [SentencePieceTokenizer](https://keras.io/api/keras_nlp/tokenizers/sentence_piece_tokenizer/) in this library. However than might not have the exact behavior as roberta/gpt2 tokenization.

We are currently working on a way to support the actual vocabulary files used by roberta/gpt2 (merges.txt and vocab.json), with exactly equivalent tokenization, running inside the tf graph.

**Comment by piEsposito** [comment]
Any updates here?

**Comment by abheesht17** [comment]
> Any updates here?

https://github.com/keras-team/keras-nlp/pull/303

**Comment by mattdangerw** [comment]
Closing this! We have an implementation released -> https://keras.io/api/keras_nlp/tokenizers/byte_pair_tokenizer/

If anyone encounters issue with the tokenizer, please file a bug!
