### ISSUE TITLE
Add a standalone tokenizer for Distilbert

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#461]
Following on with https://github.com/keras-team/keras-nlp/pull/449, we would like to expose a standalone, pure string -> int sequence tokenizer for our models. This will allow for any possible packing and padding, de-tokenization, etc.

This will be a new class wrapping the `WordPieceTokenizer`.

A few steps:

 - Add the `DistilBertTokenizer` class subclassing `WordPieceTokenizer` following the example in https://github.com/keras-team/keras-nlp/pull/449
 - Have `DistilBertPreprocessor` take in a `tokenizer` as an argument, and serialize it properly in get_config/from_config.
 - Add a documented property to access the tokenizer from the preprocessor layer.
 - Track the special token ids on the tokenizer class, and use these ids from the preprocessor like `self.tokenizer.cls_token_id`.
 - Expose `DistilBertTokenizer` in `models/__init__.py`.
 - Add documentation and tests!

**Comment by abheesht17** [comment]
Working on this.
