### ISSUE TITLE
Add a standalone tokenizer for GPT-2

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#462]
We don't yet have a clear picture of all the preprocessing we would like to add for for GPT-2, but it should be relatively simpler to add a standalone tokenizer class based on https://github.com/keras-team/keras-nlp/pull/449

This will be a new class wrapping the `BytePairTokenizer`.

A few steps:

 - Add the `GPT2Tokenizer` class subclassing `BytePairTokenizer` following the example in https://github.com/keras-team/keras-nlp/pull/449
 - Check for the `<|endoftext|>` token in the vocabulary and expose it as `self.end_token_id`.
 - Expose `GPT2Tokenizer` in `models/__init__.py`.
 - Add documentation and tests!

**Comment by abheesht17** [comment]
Working on this.
