### ISSUE TITLE
Add initializer arguments to TransformerEncoder/TransformerDecoder

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#48]
We should add `kernel_initializer` and `bias_initializer` arguments to the TransformerEncoder/TransformerDecoder. These initializer should be passed to the dense and multi head attention layers with the encoder/decoder, and saved in the config.

**Comment by mattdangerw** [comment]
New contributors should feel free to pick this up! Ping if more details are required.

**Comment by aflah02** [comment]
Hey
I'd like to take this up. I'll have look at the relevant code base and get back if I face any issues

**Comment by mattdangerw** [comment]
Thanks!

**Comment by aflah02** [comment]
Hey 
Just wished to confirm a few things

- I've used `initializers` from `keras.initializers` as that is what's used in all other places so I thought that's what we'll be using here as well
- I'm also adding some tests, is there anything else I should do too? I've added relevant docstrings to the encoder and decoder files

**Comment by chenmoneygithub** [comment]
I just dropped some comments on your PR, overall looks good. Thanks for your contributions!

**Comment by aflah02** [comment]
I think we can close this now @mattdangerw

**Comment by chenmoneygithub** [comment]
Thanks for your contribution!

**Comment by aflah02** [comment]
Your Welcome!
