### ISSUE TITLE
Tokenizer should not always pad with 0

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#487]
Now for our tokenizers, if we set the `sequence_length`, it will pad the output by 0.  This could lead to wrong behavior because 0 is not always meaningless, e.g., in GPT2 tokenizer 0 means "!". There are two approaches:
1. We still pad by `0`, but also return a `padding_mask`.
2. Add an argument to specify the `pad_token_id`, so for different models we can change its value.

**Comment by mattdangerw** [comment]
I don't think that `keras_nlp.tokenizers` should return a padding mask. A few reasons...

 - This would break the default usage of all tokenizers today; it would be about as major a compat breakage as I could think of.
 - The default output and main use cases for tokenizers today is ragged outputs (with trimming and padding happening later for most modeling code). `padding_mask` would not make much sense for ragged outputs.

Some sort of padding value argument to the tokenizer classes could make sense. It might make sense to solve this in tandem with https://github.com/keras-team/keras-nlp/issues/451.

**Comment by chenmoneygithub** [comment]
Breaking workflow is fine since we don't have backward compatibility issue, we can leave `padding_mask=None` when returning a ragged tensor. But I agree that `pad_token_id` solution is better, the only issue I foresee is users are required to generate the right mask using `pad_token_id` on their own.
