### ISSUE TITLE
Text generation utility needs mask support

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#489]
In the current text generation utility, e.g., [`keras_nlp.utils.greedy_search`](https://github.com/keras-team/keras-nlp/blob/883273f57d6afa8e3d033fb236386a39ed3c429f/keras_nlp/utils/text_generation.py#L98), the `token_probablity_fn` is expected to take in a single arg `inputs`. This is not enough because the model needs to be aware of the mask information. We cannot make the assumption that `0` means padding in the `inputs`, because some models don't use `0` for masking, e.g., GPT2, where `0` matches `!`. 

One potential fix is to pass a `mask` arg to `token_probablity_fn`. 

This is a blocking issue for GPT2 text generation story.

**Comment by mattdangerw** [comment]
This has been fixed.
