### ISSUE TITLE
Bump accelerator testing to use tensorflow 2.11

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#491]
As a follow on to https://github.com/keras-team/keras-nlp/pull/490, we should update our docker image used for accelerator testing to also use tensorflow 2.11.

**Comment by mattdangerw** [comment]
@chenmoneygithub this needs a manual push of a new docker image right?

**Comment by chenmoneygithub** [comment]
Will make it today.

**Comment by chenmoneygithub** [comment]
Changes made, I will make a PR to write guides on how to do such upgrade.

**Comment by mattdangerw** [comment]
done!
