### ISSUE TITLE
Better error messages for preset overrides

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#493]
We currently allow arbitrary overrides in preset config in our `from_preset` constructor (e.g., [link](https://github.com/keras-team/keras-nlp/blob/409adfdc2e6de38af230e785b6e358a0c89b4683/keras_nlp/models/bert/bert_models.py#L274)). If `load_weights=False` there's no issue here but if `load_weights=True` and the size is changed for any tensor with weights, the user will get a cryptic error like:
```
E         ValueError: Cannot assign value to variable ' logits/kernel:0': Shape mismatch.The variable shape (128, 4), and the assigned value shape (128, 2) are incompatible.   
```

We should consider catching these `ValueError`s and suggesting that the user check overrides if `kwargs` is not empty.

**Comment by shivance** [comment]
@jbischof is this issue looking for contributions?
