### ISSUE TITLE
Add getting started guide for KerasNLP on keras.io

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#498]
This will be a guide that shows a cross section of workflows in KerasNLP, and links out to more in depth guides for specific topics.

We need this for the 0.4 release!

**Comment by shivance** [comment]
Is this issue still open for contribution?

**Comment by jbischof** [comment]
Whoops forgot to close! Finished with the 0.4 launch. See https://keras.io/guides/keras_nlp/getting_started/
