### ISSUE TITLE
Add a Basic README for Conversion Scripts

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#505]
- Short introduction to what we aim to do with conversion scripts.
- Instructions on how to set up and install libraries, etc.
- Instructions on how to run the script.

**Comment by mattdangerw** [comment]
This would be awesome to have. Maybe we should frame it even a little more broadly as a doc on how to contribute models?

It could talk about first adding the basic model code, then attempting to convert weights and fix errors, the creating presets.

I think we can have a contribution flow where a contributor goes all the way to having preset files that list public google drive links for the weights downloads. Then we can fully test the model as is, and add to the bucket straight from the PR.

Anyway like this idea!

**Comment by jaygala223** [comment]
Hi @mattdangerw, I would like to work on this issue. Is it beginner-friendly?
