### ISSUE TITLE
Update preexisting guides and examples and for 0.4 release

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#508]
We have had a few backwards incompatible changes since the 0.3 release, e.g. flipping the default of `lowercase` in our word piece tokenizer in #289

We should run through all the existing keras.io guides and examples and make a PR updating them so they run on 0.4.

**Comment by chenmoneygithub** [comment]
I am taking care of this one. Will do a draft PR before our actual cut.
