### ISSUE TITLE
Add a keras.io page which enumerates all model preset ids

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#509]
We would like a page on keras.io that enumerates all model preset ids that can be used in a given release of keras.

**Comment by mattdangerw** [comment]
We have discussed generating this page programmatically, which could be done by iterating `keras_nlp.models.Foo.presets` when rendering keras.io. This would mean some changes to the keras.io rendering code.

One option would be to keep this information on keras.io/api/keras_nlp/models/, which will be a root page we control that will link to all our model symbols.

**Comment by shivance** [comment]
Is this issue welcoming contributions?

**Comment by mattdangerw** [comment]
Fixed https://keras.io/api/keras_nlp/models/
