### ISSUE TITLE
Update model and file names for DistilBert

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#510]
Given our new [naming guidelines](https://github.com/keras-team/keras-nlp/blob/master/STYLE_GUIDE.md#naming-of-layers-and-models), "distil" and "bert" are both segments in the DistilBert class name. This means the filenames and preset ids should look like `distil_bert_xx.py` and `distil_bert_base_xx`. Current we have `distilbert_xx.py`.

This would also be more consistent with XMLRoberta. E.g. `distil_bert` and `xlm_roberta`.

**Comment by ADITYADAS1999** [comment]
I am a new contributor .

**Comment by ADITYADAS1999** [comment]
Hey [mattdangerw](https://github.com/mattdangerw) I made the necessary changes, can I raise a PR ?



![after](https://user-images.githubusercontent.com/58718316/205811599-28b86f94-f381-48d9-a794-e5cb91fac6ba.PNG)

**Comment by mattdangerw** [comment]
@ADITYADAS1999 nice to meet you! Please do and thank you!

**Comment by ADITYADAS1999** [comment]
Hey [mattdangerw](https://github.com/mattdangerw) can you review the PR https://github.com/keras-team/keras-nlp/pull/541
