### ISSUE TITLE
Add T5 to pretrained model collections

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#519]
There are a few things we need to consider about T5.

# Structure

From the paper, T5 mostly shares the same structure as the original encoder-decoder structure proposed in Attention is All You Need, with the following variations:
1. No bias for layer norm.
2. Layer norm happens outside residual connection.
3. Relative positional embedding.

To handle these 3 facts:
1. We can use `constraint` in `tf.keras.layers.LayerNormalization` to force `beta=0`, which is a little hacky but we should be good.
2. This is simple.
3. Unsure how this can be achieved, seems we need to touch the internal logic of MultiHeadAttention.

The tough part is we cannot use `keras_nlp.layers.TransformerEncoder`, even worse, `tf.keras.layers.MultiHeadAttention` may not be suitable due to relative positional embedding. 

# Checkpoint

The official repo is using JAX: https://github.com/google-research/text-to-text-transfer-transformer, but we since it's also in python, technically we should be able to read the value of each variable and do manual assignment.

# Preprocessing

T5 treats everything as text to text, and uses prefix to "tell" the model what it is doing, e.g, "translate English to German: That is good". For our provided presets, we need to reflect this special preprocessing. For custom finetuning, we need to inform users to set the correct prefix. But according to the paper, "prefix does not change too much", so I am confused how should the prefix be set...?

**Comment by mattdangerw** [comment]
I think @abheesht17 may have been planning to look at checkpoint conversion on this at some point, but I believe has not started yet. You two should sync up when starting work!

**Comment by mattdangerw** [comment]
One interesting wrinkle we will have to deal with here is the the latest t5 checkpoints do not have a shared embedding for token->model space and reversed. They used a separately parameterized embedding!

This leads to an interesting conundrum where out "backbone" presets will not have all weights they need to do normal t5 inference. There is some discussion on this issue https://github.com/keras-team/keras-nlp/issues/415
