### ISSUE TITLE
Standardize on "backbone" naming for BERT

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#526]
We've settled on "backbone" as the name for the pretraining submodel reused in task models (even generative models like GPT)! I propose two changes to help reduce confusion for users:
1. `bert_models.py` -> `bert_backbone.py`
2. `Bert` -> `BertBackbone`

This should make it more clear when we refer to a "backbone" model in our user guides.

Note: I dropped the plural in the filename since I think the backbone has to be unique.

**Comment by mattdangerw** [comment]
Like this change a lot!
