### ISSUE TITLE
Allow XMLRobertaClasssifier to operate directly on raw strings

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#529]
We should mirror the change in https://github.com/keras-team/keras-nlp/pull/485 for XLMRobertaClassifier, and allow fit/predict/evaluate to take in raw strings.

**Comment by ADITYADAS1999** [comment]
Hey [mattdangerw](https://github.com/mattdangerw) , can I take this issue ?
/assign

**Comment by mattdangerw** [comment]
> Can I make the changes right now

No need to rush too much!

This is just time sensitive because we are lining up our 0.4 release. If you think you have time to take this on between now and this Wednesday (the 14th), please go ahead! If not, this issue might be best left for someone else to to grab.

Thanks!

**Comment by mattdangerw** [comment]
Going to take this on! We will open up more contributions welcome issue soon!
