### ISSUE TITLE
Consider reworking how classification presets are created

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#531]
We currently allow presets for classification models, e.g. `bert_base_uncased_en_sst2`. However the way we build up the model object in `from_preset` is somewhat confusing:

 - We restore the backbone from a config dictionary, to allow a separate (even non-standard) configuration for the model architecture.
 - We restore the preprocessor by calling `from_preset` directly, and then pass that object into `from_config()` on the class.

It might be better is we restored our preset either by calling `from_preset` on all sub-layers, or by restoring via a config dictionary on all sub-layers.

However this is made complicated by the fact that the vocabulary is technically part of the config for preprocessing layers, and the only method that knows how to download a vocabulary is `BertTokenizer.from_preset()`.

**Comment by mattdangerw** [comment]
It may be that our answer is what we have is totally reasonable, but I do think this could use a little more though.

There might be some benefits to having a "config all the way down" preset for task level checkpoints, because this would give us a mechanism to ship the exact preprocessing config we used to fine-tune the preset checkpoint.

More discussion on this here:
https://github.com/keras-team/keras-nlp/pull/485#discussion_r1036381166

**Comment by jbischof** [comment]
As long as `vocabulary` is part of the config for a preset, I think we're stuck. This data is just too large to store in the repo.

The direct analogy to the backbone would be to consider the `vocabulary` a "state" of a preprocessor like weights are for the backbone. In this world you could create a preprocessor without a vocab and then `adapt` it to the data like a KPL or load in the vocab from a file. @mattdangerw you are the KPL guru WDYT?

**Comment by jbischof** [comment]
Talked to @mattdangerw offline and it seems we want to keep `vocabulary` in the config. Is there some other way around the problem of it being too big to store in the API? Otherwise we should close the task.

**Comment by mattdangerw** [comment]
Yeah, I think keeping the vocabulary in the config is going to save off a lot of headaches (at least this was a clear lesson from preprocessing layers).

I was still thinking of playing around if there were other ways to get what is essentially a nested config for our presets, but not actually requiring sticking the whole asset in our config. I might leave this open to try a few more things out, and close if nothing clear is presenting itself.

**Comment by mattdangerw** [comment]
Stale.
