### ISSUE TITLE
Replicate #536 changing `GPT2` -> `GPT2Backbone`

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#539]
1. `gpt2_models.py` -> `gpt2_backbone.py`
2. `gpt2_models_test.py` -> `gpt2_backbone_test.py`
3. `GPT2` -> `GPT2Backbone`

See #526 for more background.

**Comment by ADITYADAS1999** [comment]
Hi [jbischof](https://github.com/jbischof) can I fix this. I am new here 😊

**Comment by jbischof** [comment]
Awesome @ADITYADAS1999, excited to onboard you! See our [contributing guide](https://github.com/keras-team/keras-nlp/blob/master/CONTRIBUTING.md) for helpful pointers.

Let's start with #539 since it's a little easier (no task models). Send me a PR when you're ready and let me know if you have questions!

**Comment by ADITYADAS1999** [comment]
> Awesome @ADITYADAS1999, excited to onboard you! See our [contributing guide](https://github.com/keras-team/keras-nlp/blob/master/CONTRIBUTING.md) for helpful pointers.
> 
> Let's start with #539 since it's a little easier (no task models). Send me a PR when you're ready and let me know if you have questions!

Thanks [jbischof](https://github.com/jbischof) for assigning. 😊 I definitely inform you when I stuck any step.

**Comment by mattdangerw** [comment]
Just FYI, I just submitted a large file rename to try to knock that out in one go (and minimize merge conflicts) #548.

The actual symbol rename is still todo though!

**Comment by ADITYADAS1999** [comment]
> Just FYI, I just submitted a large file rename to try to knock that out in one go (and minimize merge conflicts) #548.
> 
> The actual symbol rename is still todo though!

thanks for informing [mattdangerw](https://github.com/mattdangerw) thats great. I just start working with this.

**Comment by ADITYADAS1999** [comment]
Please review this one   https://github.com/keras-team/keras-nlp/pull/558
