### ISSUE TITLE
Add a layer to dynamically generate mask

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#54]
**Is your feature request related to a problem? Please describe.**
Masking is an essential part in LM models, so we need to have a layer to do the work. 

**Describe the solution you'd like**
Create a new layer, which takes in sequence data (could be both RaggedTensor and Tensor), and returns masked sequence, and masked positions and ids.

**Describe alternatives you've considered**
We can directly use tf_text, but the API is not very user-friendly.

**Additional context**
N/A

**Comment by mattdangerw** [comment]
This is done! https://github.com/keras-team/keras-nlp/pull/61
