### ISSUE TITLE
Rendering issue on keras.io for argument lists

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#572]
Opening this to track https://github.com/keras-team/keras-io/issues/1156 as it will affect every `keras_nlp.models.XXPreprocessor` layer.

Work here is to be done on the keras.io side, just adding this to attach to our issue tracking project.

**Comment by ADITYADAS1999** [comment]
hey [mattdangerw](https://github.com/mattdangerw) this issue is still open ?
Can you please share the source file of this docs.

**Comment by mattdangerw** [comment]
@ADITYADAS1999 the fix will likely need to be located in https://github.com/keras-team/keras-io. We should not change the actual docstrings, rather fix the rendering code if possible. You are welcome to take a look at this! Though it may end up being a bit tricky.

**Comment by sahusiddharth** [comment]
@mattdangerw can you please elaborate more on the issue?
