### ISSUE TITLE
Design the KerasNLP section layout on keras-io

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#575]
We need to make a mini design on the layout, a few questions to address:

1. How many tabs do we want? API documentation, Quick Start, Guidance...
2. What's the layout for pretrained model? how do we list out the presets?
3. How do we document offerings in examples/ folder, such as the GLUE script?
4. More...

**Comment by mattdangerw** [comment]
So I think as a first, quick, take we can keep the same structure we have today. Then we can as a follow up rework the overall navigation experience, but we will probably need to do that in tandem with KerasCV and KerasTuner. So for now we may want to stick to something like this:

```
keras.io/
    keras_nlp/
        -> Any markdown we would like.
    api/keras_nlp/
        -> Any structure of "sub-levels" we would like here, e.g. "models". Each with a markdown doc.
        -> Rendered API documentation per symbol.
    guides/keras_nlp/
        -> Any number of official guides from us, in a "colab-like" format.
    examples/keras_nlp/
        -> Any number of examples from us and contributors, in a "colab-like" format.
```

The most "undefined" spot in our current setup is how we group our generated API docs. Seems like we might want to further nest the models section. For example `keras.io/keras_nlp/api/models/` gives an overview of all our model docs, and `keras.io/keras_nlp/api/models/bert/` gives an overview of the bert specific symbols. I can put together a quick demo of this on #497.
