### ISSUE TITLE
Load pretrained models under distribution scope

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#576]
If users want to do distributed training, they need to load pretrained model under the right scope:
```
with strategy.scope():
  model = keras_nlp.models.Bert.from_preset("...")
```

If users forget to do so, it will throw some random error messages. One alternative is in our `from_preset()` method, we arbitrarily get the distribution strategy:
```
strategy = tf.distribute.get_strategy()
with strategy.scope():
  ...
```

We need to call out our user journey before the 0.4 release.

**Comment by mattdangerw** [comment]
IMO let's stick with the default Keras model user journey for now--you need to declare you model inside a strategy scope.

If there is something we can do to improve our error messages when a user gets this wrong, that would be great.

**Comment by mattdangerw** [comment]
Let's close this an open up issues for the new Keras distribution API as we add support.
