### ISSUE TITLE
BertClassifier diagram in Quick Tour somewhat confusing

### ISSUE THREAD

**Issue by hertschuh** [keras-team/keras-nlp#597]
**Is your feature request related to a problem? Please describe.**
In the Quick Tour, early on there is a diagram with the legend:

> Here is the modular hierarchy for BertClassifier (all relationships are compositional):

I was confused when looking at it. Specifically, it wasn't clear to me what the lines connecting the boxes were, and in which direction they were pointing.

**Describe the solution you'd like**
- I think the word **hierarchy** in the legend is misleading because there is no inheritance going on between any of the boxes. So that word should probably be replaced.
- Matt explained to me that the lines express a "has a" relationship, which is consistent with the **(all relationships are compositional)** part of the legend, but maybe this could be made visually clear, especially in which direction it goes (BertClassifier has a BertPreprocessor...). Maybe the solid rhombus from the UML notation could work.
- I was kind of looking for a data flow diagram showing what goes in and out of each box (text goes in Preprocessor then output goes in Backbone, etc.). Maybe this would be a good addition to the relationship diagram.

**Describe alternatives you've considered**
Looking at the code and `PipelineModel` cleared my confusion

**Additional context**
N/A

**Comment by jbischof** [comment]
![Screen Shot 2022-12-21 at 5 18 24 PM](https://user-images.githubusercontent.com/1141045/209034426-c3020501-2d21-42da-aa3e-979c88154873.png)
@hertschuh is this what you're asking for?

**Comment by hertschuh** [comment]
@jbischof Yes.
My understanding is that the rhombuses should go the other way though, like you had them initially.
Thanks!

**Comment by jbischof** [comment]
@hertschuh according to online tutorials like [source1](https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-class-diagram-tutorial/) or [source2](http://websites.umich.edu/~eecs381/handouts/UMLNotationSummary.pdf) the diamond seemed to reside near the enclosing class. Please let me know if I've misinterpreted.

**Comment by hertschuh** [comment]
Oh, you're right!
The [documentation](https://www.gleek.io/blog/class-diagram-arrows.html) I looked at had it wrong.
