### ISSUE TITLE
WordPieceTokenizer inconsistent lowercase behavior

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#599]
`pretokenize` method has `lowercase=True` by default, while `WordPieceTokenizer` has `lowercase=False` by default. The functionality is fine, so this is non-blocking, but shall we make them consistent?

**Comment by mattdangerw** [comment]
Yeah `pretokenize` is not exposed so not blocking, but this would be a good one liner to clean up!

**Comment by ADITYADAS1999** [comment]
> Yeah `pretokenize` is not exposed so not blocking, but this would be a good one liner to clean up!

hey [mattdangerw](https://github.com/mattdangerw) this issue is still open for contributors?

**Comment by mattdangerw** [comment]
yep!
