### ISSUE TITLE
Adding debug instructions incase lint.sh/format.sh fail

### ISSUE THREAD

**Issue by aflah02** [keras-team/keras-nlp#60]
I noticed that when I run lint.sh and format.sh and the file is in CRLF mode it fails to run while in LF mode it does. It feel it could be a helpful addition [here](https://github.com/keras-team/keras-nlp/blob/master/CONTRIBUTING.md#formatting-the-code) and might save people some time
If this seems fine I can raise a PR adding a couple of sentences in this regard

**Comment by mattdangerw** [comment]
Sure! Doc update appreciated. Feel free to open a PR.

Do you know where things are failing on CRLF? Would it be possible to just fixup the scripts?

**Comment by aflah02** [comment]
Hey!
I'm not quite sure what could be the issue, I did try looking it up online but couldn't find anything conclusive as such :(

**Comment by mattdangerw** [comment]
Thanks! I would be surprised if any of the underlying tools (black, isort, flake8) did not support windows style line endings, so seems like there might be something we could do here.

**Comment by aflah02** [comment]
Right I was thinking the same, I've added an image the first run is with CRLF while the second one is with LF

<img width="381" alt="image" src="https://user-images.githubusercontent.com/72096386/160192249-77a00e48-926d-4907-a252-bc6848fba1e3.png">

**Comment by aflah02** [comment]
I think I just might've realized what's wrong, I think it has to do with how wsl works, so when I open up WSL the editor (vscode) in my case doesn't know that so it retains the CRLF endings while WSL now expects LF endings. I'm not sure how many people might have this issue but this seems to be the core idea

**Comment by mattdangerw** [comment]
Thanks. Probably what is happening here is you are cloning with windows git (default clrf line endings), and then running with WSL (where linux style line endings would be assumed). If you re-clone the repo from the git binary inside WSL (or globally reconfigure windows git to force LF line endings before cloning) does that fix the issue?

If that's the case, we should really update your PR to say something more like:

Note that if you are using WSL, make sure you clone the repo with linux style `LF` line endings before running the format or lint scripts.

**Comment by aflah02** [comment]
Hi!
Yup it does!, I'll change the message then as your suggestion would be better

**Comment by aflah02** [comment]
I've updated the PR now
