### ISSUE TITLE
Move text generation utils to `keras_nlp.samplers`

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#601]
We are reworking the text generation utils into `keras_nlp.samplers.XXX` classes, e.g., `keras_nlp.samplers.GreedySampler()`, which has a smoother user journey, and suits text generation for pretrained models better.

**Comment by ADITYADAS1999** [comment]
Hey [chenmoneygithub](https://github.com/chenmoneygithub), can you describe the issue little bit, if the issue is still open.

**Comment by chenmoneygithub** [comment]
@ADITYADAS1999 Thx for your interest! This one is a bit vague actually, we are still going through the design.

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999 Thx for your interest! This one is a bit vague actually, we are still going through the design.

Thanks for the information :)

**Comment by mattdangerw** [comment]
done!
