### ISSUE TITLE
Solutions for multiple text files?

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#603]
### Discussed in https://github.com/keras-team/keras-nlp/discussions/513

<div type='discussions-op-text'>

<sup>Originally posted by **LazurasLong** December  1, 2022</sup>
The default keras preprocessing util “text_dataset_from_directory” doesn’t currently work with the NLP tokenizers.

Any solution beyond brute forcing the issue by calling each txt file individually?</div>

**Comment by jbischof** [comment]
Sorry we missed your question @LazurasLong, are you still having trouble? Could you send us a code snippet or colab to replicate your issue?

We haven't been good about checking discussions so I filed an issue for you.

**Comment by LazurasLong** [comment]
I've been looking to use keras_nlp.tokenizers.compute_word_piece_vocabulary based on the Example .

While the example uses tf.data.TextLineDataset, I have 6000+ txt files I'm attempting to iterate through and I was hoping to be able to use tf.keras.utils.text_dataset_from_directory instead. 


looking at word_piece_tokenizer_trainer.py, I should be able to pass a dataset into compute_word_piece_vocabulary but I'm getting this error:

ValueError: The `data` argument must be either `tf.data.Dataset` or `list`. Received: <class 'str'>.

Here's the code for creating the dataset 


raw_train_ds = tf.keras.utils.text_dataset_from_directory(
    dataset_dir,
    labels=None,
    label_mode=None,
    class_names=None,
    batch_size=BATCH_SIZE,
    max_length=SEQ_LEN,
    shuffle=True,
    seed=SEED,
    validation_split=.02,
    subset="both",
    follow_links=False
)

**Comment by jbischof** [comment]
@chenmoneygithub, can you take a look? It appears that the trainer is interpreting a dataset as a list of files and trying to redo the I/O.

@LazurasLong would it be possible to share a small colab that replicates the issue? You can write a couple of example files to disk at the beginning. It's hard to diagnose the error without the code.

**Comment by jbischof** [comment]
Hey @LazurasLong, now that our Getting Started guide is live on keras.io, you can see an end-to-end example of loading data with `tf.keras.utils.text_dataset_from_directory` and training a tokenizer.

* Loading data: https://keras.io/guides/keras_nlp/getting_started/#data
* Training a tokenizer: https://keras.io/guides/keras_nlp/getting_started/#train-custom-vocabulary-from-imbd-data

Let us know if this helps!

**Comment by LazurasLong** [comment]
Thanks I'll take a look at it. 

After a few trial runs, I think the issue focuses on how I was loading the data. 

In particular it didn't seem to like PosixPath vs Os.path.

**Comment by jbischof** [comment]
Great, if you figure it out please file an issue with core Keras!
