### ISSUE TITLE
Add `from_text` constructor to `Tokenizer` classes

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#623]
Currently the user journey to train and deploy their own tokenizer has some friction. The user must find a separate method to train the vocabulary and then ensure that the arguments match when instantiating the tokenizer:
```python
vocab = keras_nlp.tokenizers.compute_word_piece_vocabulary(
    text_dataset,
    vocabulary_size=20_000,
    lowercase=True,
    strip_accents=True,
    reserved_tokens=["[PAD]", "[START]", "[END]", "[MASK]", "[UNK]"],
)
tokenizer = keras_nlp.tokenizers.WordPieceTokenizer(
    vocabulary=vocab,
    lowercase=True,
    strip_accents=True,
    oov_token="[UNK]",
)
```

It's easy to see how this training process could be folded into the constructor. I propose a non-breaking change where a `from_text` `classmethod` constructor is added to the `Tokenizers` that simply calls the vocab training under the hood. This opens up a simpler user journey:
```python
tokenizer = keras_nlp.tokenizers.WordPieceTokenizer.from_text(
    text_dataset,
    vocabulary_size=20_000,
    lowercase=True,
    strip_accents=True,
    oov_token="[UNK]",
    reserved_tokens=["[PAD]", "[START]", "[END]", "[MASK]", "[UNK]"],
)
```

**Comment by ADITYADAS1999** [comment]
Hey [jbischof](https://github.com/jbischof) this issue is still open😃 ?

**Comment by jbischof** [comment]
Sure take a crack at WordPieceTokenizer to start @ADITYADAS1999

**Comment by ADITYADAS1999** [comment]
> Sure take a crack at WordPieceTokenizer to start @ADITYADAS1999

Thanks [jbischof](https://github.com/jbischof), so all the changes are made on https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/tokenizers/word_piece_tokenizer.py this file right?

**Comment by jbischof** [comment]
Yes! Please note this is an experimental design so there may be some feedback from the team once the code is working but should be pretty straightforward.

**Comment by ADITYADAS1999** [comment]
> Yes! Please note this is an experimental design so there may be some feedback from the team once the code is working but should be pretty straightforward.
> 
> I am starting another experiment myself with #621 😀

thats cool 👍🏻

**Comment by mattdangerw** [comment]
Hey! Actually I do have some feedback here 😬 . This was a spot where we had a decent amount of conversation around 6 months ago, so this is a good place to context dump.

## UX Thoughts

First question for me, is coupling the training of a vocabulary to `tokenizer` API an actual usability improvement? I have tended to think of training a vocab vs using a vocab as one-to-many. Outside of toy examples in guides, vocab training is slow (especially with today's code), and when modeling from scratch it seems like vocabs will almost always be reused very heavily. With the `from_text()` approach proposed here, you might spend hours training your vocab, only to find you know have no good way to save the vocabulary and split out the configuration from the `from_text()` constructor that is required for reusing the vocabulary.

Second, if we do think coupling the training API directly to the tokenizers is a good idea, why not stick with `tokenizer.adapt()`? It’s an established UX pattern that would better link us to the rest of the Keras ecosystem. And subjectively having a constructor that will take multiple passes over a dataset and run for many hours feels somewhat surprising.

## Timing Thoughts

There were also some timing reasons we chose the conservative approach of leaving this "vocab training" API decoupled. 

First, I think it is fair to say that our vocab training “tech” is not that good. Our wordpiece trainer is not only single-machine, but single-process and fully python. It is quite slow in practice. Before we invest too much in our usability, we might want to first invest in a plan for more scalable usage (how do we add multi-threaded support, and do we want to go so far as multi-machine support?), and use that to inform our design.

Second, there might be some improvements that group well with this on the saving side. Supporting `adapt()` with our current saved model format proved to be quite burdensome, but would likely be much easier and more flexible with the `keras_v3` format. This would require more thought, but it might save some effort to punt this until our new saving story is more developed.

**Comment by mattdangerw** [comment]
A simple fix we could do today might be to switch to `SentencePiece` training for all our guides and examples. SentencePiece training should in theory be faster, much more fully featured, and does not have the repeated config issue at all (the trained proto is self contained).

When training from scratch, do we ever have a reason to recommend `WordPiece` over `SentencePiece`?

**Comment by LazurasLong** [comment]
Word piece is generally seen as superior for text generation while sentence
piece is generally an equal or even superior option for summary and
classification.

 The choice of which to use for examples should mostly like come down to
which task do  we want to highlight the most?

**Comment by jbischof** [comment]
@ADITYADAS1999 it seems like there is was **feedback** then I expected so it seems best to shelve this idea for the time being. We will add more "contributions welcome" issues soon. Sorry for the inconvenience.

@LazurasLong do you have a reference for your claim about WordPiece? It is only used in non-generative models like BERT, distilBERT, and Electra while GPT uses BPE and T5 uses SentencePiece.

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999 it seems like there is was more _feedback_ then I expected so it seems best to shelve this idea for the time being. We will add more "contributions welcome" issues soon. Sorry for the inconvenience.
> 
> @LazurasLong do you have a reference for your claim about WordPiece? It is only used in non-generative models like BERT, distilBERT, and Electra while GPT uses BPE and T5 uses SentencePiece.

It's okk [jbischof](https://github.com/jbischof). 😃 looking forward to contribute more issues.
