### ISSUE TITLE
Add BertFeatureExtractor task

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#629]
Task models like BertClassifier offer the convenience of automatic preprocessing, but we will never have a task model for every application. Let's add a generic task model that returns the BertBackbone output only.

**Comment by shivance** [comment]
Can I have a crack at it?

**Comment by jbischof** [comment]
Thanks @shivance! You should be able to copy [`bert_classifier.py`](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_classifier.py) but simplify the constructor logic to

```python
inputs = backbone.input
outputs = backbone(inputs)
```

We are working on a refactor to make this easier in the future, but the rest of the work will be updating the documentation, names, and tests for the simplified functionality. Let me know if you have questions!

**Comment by chenmoneygithub** [comment]
is `BertFeatureExtractor ` an alias to `BertBackbone`? Maybe we can just do the alias import?

**Comment by jbischof** [comment]
@chenmoneygithub not quite! Task models include preprocessing and inherit from `PipelineModel`. I'd recommend checking out the [API quickstart](https://keras.io/guides/keras_nlp/getting_started/#api-quickstart) section of our Getting Started guide for a thorough explanation.

**Comment by chenmoneygithub** [comment]
Ah you are right, I constantly forget `PipelineModel`.
