### ISSUE TITLE
Create `Task` base class

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#635]
This PR would be an replication of #621 for **task** models. Actually there is more to deduplicate in this case!

Steps:
* Create `Task` class in `models/task.py`, which inherits from `PipelineModel`
* Copy over following methods/properties to base class from `BertClassifier`:
    *  `preprocess_samples`
    * `backbone`
    * `preprocessor`
    * `from_config`
    * `presets` (return `{}`)
    * `from_preset` with string formatting params to adapt to preset and class names
* Remove these methods from each subclass and fill in the string params for `from_preset`.

Following #621, simplify the documentation for `from_preset` and move some of the examples to the generic constructor docstring.

**Comment by soma2000-lang** [comment]
@jbischof  Can I work on this if someone is not already into it

**Comment by jbischof** [comment]
@soma2000-lang we're excited for new contributors but this task is taken. We will be adding more soon; we just emptied the queue before 0.4 release unfortunately!
