### ISSUE TITLE
Incorrect `epsilon` (LayerNorm) for the Transformer Layer in `BERTBackbone`

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#642]
The correct `epsilon` value is `1e-12` for BERT. We pass this correct value to the LayerNorm layer after embeddings (https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_backbone.py#L149) but do not pass the correct value to the `TransformerEncoder` layers (https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_backbone.py#L159-L168). The default value for `layer_norm_epsilon` in `TransformerEncoder` is `1e-5`. 

This issue is probably there in other backbone models as well.

https://huggingface.co/bert-base-uncased/blob/main/config.json#L12

**Comment by abheesht17** [comment]
@soma2000-lang, would you like to work on this?

**Comment by ADITYADAS1999** [comment]
> The correct `epsilon` value is `1e-12` for BERT. We pass this correct value to the LayerNorm layer after embeddings (https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_backbone.py#L149) but do not pass the correct value to the `TransformerEncoder` layers (https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_backbone.py#L159-L168). The default value for `layer_norm_epsilon` in `TransformerEncoder` is `1e-5`.
> 
> This issue is probably there in other backbone models as well.
> 
> https://huggingface.co/bert-base-uncased/blob/main/config.json#L12

hey [abheesht17](https://github.com/abheesht17) this issue is still open ?

**Comment by soma2000-lang** [comment]
@abheesht17 yes I would like to work on this

**Comment by abheesht17** [comment]
Hey, @ADITYADAS1999! Since this is a "good first issue", I am assigning it to @soma2000-lang. Hope that's okay?

**Comment by ADITYADAS1999** [comment]
> Hey, @ADITYADAS1999! Since this is a "good first issue", I am assigning it to @soma2000-lang. Hope that's okay?

absolutely, no issue  [abheesht17](https://github.com/abheesht17) 😃

**Comment by ayushksingh28** [comment]
Is this issue still open ?

**Comment by abheesht17** [comment]
@ayushksingh28, unfortunately, this issue has been resolved. Closing it now.

**Comment by ayushksingh28** [comment]
Okay thanks for letting me know
