### ISSUE TITLE
Add a BLEU metric

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#65]
Splitting this issue out from https://github.com/keras-team/keras-nlp/issues/38.

We should add a BLEU metric as `keras_nlp.metrics.Bleu`.

**Comment by abheesht17** [comment]
Linking a comment here which explains the difficulty with BLEU:
https://github.com/keras-team/keras-nlp/issues/38#issuecomment-1066586228

For ROUGE Score, I used a `TensorArray`, which has a `write` operation. Maybe, we can use the same here.

**Comment by arcAman07** [comment]
If this issue is open, I would want to work on implementing the BLEU metric.

**Comment by abheesht17** [comment]
Hello, @arcAman07! I'm currently working on this.

**Comment by arcAman07** [comment]
Cool, wasn't aware of it 👍

**Comment by abheesht17** [comment]
Rough Implementation: https://colab.research.google.com/drive/1uX5V98N1apnNHJTLQAecIz2H8yQfL5fK?usp=sharing

**Comment by abheesht17** [comment]
Rough Implementation: https://colab.research.google.com/drive/1uX5V98N1apnNHJTLQAecIz2H8yQfL5fK?usp=sharing
