### ISSUE TITLE
Rename fnet_encoder.py -> f_net_encoder.py

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#656]
A minor fix to follow along #643 .

According to our [style guide](https://github.com/keras-team/keras-nlp/blob/master/STYLE_GUIDE.md), the filenames for the FNetEncoder layer should really look like f_net.

So we should rename `fnet_encoder.py` -> `f_net_encoder.py` and  `fnet_encoder_test.py` -> `f_net_encoder_test.py`, and fix all imports.

**Comment by abheesht17** [comment]
@mattdangerw, I've made this change in the `FNetBackbone` PR itself: https://github.com/keras-team/keras-nlp/pull/643

**Comment by durganshyadav** [comment]
can i work on this issue
