### ISSUE TITLE
Autogenerate preset tables on keras.io

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#657]
This will be a fairly involved contribution, but one that will help out the project quite a bit!

We are hoping to generate our preset checkpoint [tables on keras.io](https://keras.io/api/keras_nlp/models/#backbone-presets) directly from our library.

There will be two main steps to this.

1) In this repo, we need to update our `xx_presets.py` files so they contain all the metadata they need to generate the documentation tables. We should add a `"metadata"` dictionary for each preset, which can contain the model `"description"` and `"params"` count, with the ability to add more metadata later.
2) On the keras.io [repo](https://github.com/keras-team/keras-io), we need to add code to traverse through our model presets and render the metadata as a markdown table on the models page. I've written a starter commit showing how this could look [here](https://github.com/mattdangerw/keras-io/commit/7f0974db0dfb83eceb35b00851bcefac0d5957cd).

**Comment by mattdangerw** [comment]
Another useful code pointer, [this script](https://github.com/keras-team/keras-nlp/blob/master/tools/count_preset_params.py#L46) shows how you can programmatically walk through our presets. This will be useful for writing the rendering code on keras.io.

**Comment by durganshyadav** [comment]
can i contribute in this

**Comment by mattdangerw** [comment]
Actually @Cyber-Machine is it ok if @durganshyadav take this one on? I referred @durganshyadav over to this issue on http://go/kerasnlp/issues/650, they have been looking for an issue for a bit.

We will continue opening contributions welcome issues regularly!

And thanks everyone for patience as we scale up to more contributors here! We are getting a lot more new contributors which is wonderful but will be a growing process for us 😄

**Comment by mattdangerw** [comment]
Actually apologies, I just saw that @durganshyadav is assigned on #658 

So in the interesting of spreading our new issue around, actually @Cyber-Machine let's leave this one for you!

Sorry about the confusion. @Cyber-Machine if you would like to take this on feel free. And please ping if any questions.

**Comment by mattdangerw** [comment]
Thank you! Looking now!

**Comment by mattdangerw** [comment]
@Cyber-Machine thank you! This is now live on keras.io -> https://keras.io/api/keras_nlp/models/

This will be super useful for every release we do from here on out! it will really speed up our release process.
