### ISSUE TITLE
Add `AlbertClassifier`

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#660]
Similar to `BertClassifier`.

**Comment by shivance** [comment]
Hey, I'll like to work on this issue.

**Comment by jbischof** [comment]
@shivance do you still plan to work on #648?

**Comment by shivance** [comment]
I already am working on it, will push soon.
This issue seems quite easy thoas it's mostly replication of `BertClassifier` please correct me if I am wrong
