### ISSUE TITLE
pypi installation very slow

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-nlp#686]
Using `pip install keras-nlp` is almost as slow as installing from source. The reason seems to be that multiple versions of `tensorflow-text` and `tensorflow` are downloaded to find the best match.

```
Collecting tensorflow
  Downloading tensorflow-2.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 2.2 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of tensorflow-text to determine which version is compatible with other requirements. This could take a while.
Collecting tensorflow-text
  Downloading tensorflow_text-2.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 58.7 MB/s eta 0:00:00
Collecting tensorflow
  Downloading tensorflow-2.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (578.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 578.1/578.1 MB 2.6 MB/s eta 0:00:00
  Downloading tensorflow-2.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (578.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 578.1/578.1 MB 3.1 MB/s eta 0:00:00
```

**Comment by mattdangerw** [comment]
One thing we can play with here is to only depend on tf-text, and transitively depend on tensorflow through tf-text. This will still probably require a download of tensorflow and tf-text, but may avoid the multiple downloads of tf (to figure out a version match) @jbischof is showing above. This is something we could do without needing to block on others.

Other things we could do that would speed up the process precipitously, but would block on others teams...

 - Include tf-text in the default colab runtime.
 - Include keras-nlp in the default colab runtime.

**Comment by jbischof** [comment]
@mattdangerw is there a way to test your new dependency graph without doing a release? Or if so, maybe we make a dev branch and dev release?

**Comment by mattdangerw** [comment]
We can test just be doing a pip install from a git branch as usual! There should be no difference between that and pypi here.

Was starting to play around with this a big, and things look ok. I just want to make sure we do a little background reading and understand everything at play before we rush the solution out. Can put up a PR soonish!

**Comment by mattdangerw** [comment]
Opened https://github.com/keras-team/keras-nlp/pull/697 and left some comments on the issue.

One misconception to clear up in the original issue description. `pip install keras-nlp` should be exactly as slow as installing from source in all cases! What is slow for us is our dependency downloads, and we have no compiled code. So switching from pypi to github in our `pip` line will only be switching our mirror for our "pile of python files." The timing differences between the two methods should be negligible, and that is quite expected!

**Comment by jbischof** [comment]
Interesting @mattdangerw! I must have been thinking about `.par` packages or something.

**Comment by mattdangerw** [comment]
We have switch to just depending on tf-text, which should avoid these multiple download dependency resolution issues
