### ISSUE TITLE
Clean up optional dependencies listed in setup.py

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#687]
We have some optional dependencies listed in our setup.py that have grown a little stale.

The setup.py files are no longer a complete list of dependencies for a development environment (that has moved to our requirements.txt), there are also a lot of dependencies here specific to our BERT pretraining example only.

We might want to pare this list down to just the optional dependencies for the install package itself--which is just `setencepiece` and `rogue-score`.

**Comment by ADITYADAS1999** [comment]
> We have some optional dependencies listed in our setup.py that have grown a little stale.
> 
> The setup.py files are no longer a complete list of dependencies for a development environment (that has moved to our requirements.txt), there are also a lot of dependencies here specific to our BERT pretraining example only.
> 
> We might want to pare this list down to just the optional dependencies for the install package itself--which is just `setencepiece` and `rogue-score`.

hey @mattdangerw this issue is open for contributors ?

**Comment by mattdangerw** [comment]
This is already in flight in https://github.com/keras-team/keras-nlp/pull/697

I will be opening up some more issues early next week, in particular for replicating the changes in https://github.com/keras-team/keras-nlp/pull/653 for other encoder models. I could assign one of those to you if you are on the hunt for more issues!

**Comment by ADITYADAS1999** [comment]
> This is already in flight in #697
> 
> I will be opening up some more issues early next week, in particular for replicating the changes in #653 for other encoder models. I could assign one of those to you if you are on the hunt for more issues!

Thank you @mattdangerw
