### ISSUE TITLE
Segfault on nightly testing

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#694]
https://github.com/keras-team/keras-nlp/actions/runs/4009842978/jobs/6885660111

This does not appear to be tied to a specific change, this is only present with today's nightly pip, not yesterdays.

Also, the test showing the segfault in the logs is not the only one causing this (commenting it out leads to another segfault). It's probably just the first test to hit the issue.

We should investigate further.

**Comment by chenmoneygithub** [comment]
the error comes from this chunk:
```python
sentencepiece.SentencePieceTrainer.train(
    sentence_iterator=vocab_data.as_numpy_iterator(),
    model_writer=bytes_io,
    vocab_size=10,
    model_type="WORD",
    pad_id=0,
    unk_id=1,
    bos_id=2,
    eos_id=3,
    pad_piece="<pad>",
    unk_piece="<unk>",
    bos_piece="[CLS]",
    eos_piece="[SEP]",
)
```

I checked SPE package, and they have not pushed a breaking change in the last week. The problem could be from the TF side.

**Comment by mattdangerw** [comment]
This is temporarily fixes with a workaround, but we should try to fine a long term solution. See lined sentencepiece issue above.
