### ISSUE TITLE
Adding Encoder from TransEvolve

### ISSUE THREAD

**Issue by aflah02** [keras-team/keras-nlp#70]
A recent work present at neurips which can be viewed [here](https://papers.nips.cc/paper/2021/file/2bd388f731f26312bfc0fe30da009595-Paper.pdf) uses temporal evolution scheme which they've named TransEvolve, to bypass costly dot-product attention over multiple stacked layers. Their results after extensive testing have shown that it outperforms the traditional transformer on encoder only tasks and it comparable to original transformer in other tasks. An implementation already exists [here](https://github.com/LCS2-IIITD/TransEvolve) and I feel this would be a worthy addition to the current set of encoders!
If this seems interesting enough I can create a demo colab and also implement this matching the format of existing encoders.
Would love to hear your thoughts

**Comment by aflah02** [comment]
SideNote: It's time complexity is pseudo quadratic and uses much less parameters than a normal transformer

**Comment by aflah02** [comment]
@mattdangerw Any thoughts on this?

**Comment by chenmoneygithub** [comment]
@aflah02 Thank you for reporting this feature request and willingness to contribute! We will need to discuss a bit on if we want to add TransEvolve now, since it has not gained many citations yet (maybe because it is pretty new). Please stay tuned, thanks again!

**Comment by aflah02** [comment]
Thanks for the review @chenmoneygithub! Yeah I guess it being pretty new is probably the reason. Looking forward to the result of the discussion 😁

**Comment by mattdangerw** [comment]
Agreed with @chenmoneygithub. Let's not add it for now; we want to be pretty focused on really the "greatest hits" nlp papers right now. We can circle back if this becomes more widely used in the future.

**Comment by aflah02** [comment]
Thanks for the feedback!!
