### ISSUE TITLE
Add a DistilBertMaskedLM task model

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#710]
In https://github.com/keras-team/keras-nlp/pull/653 we added a masked language modeling task for RoBERTa. We can make a similar change for the `DistilBERT` model.

* [ ] Update `DistilBertTokenizer` to expect a mask token.
* [ ] Add a `DistilBertMaskedLMPreprocessor` preprocessor layer and tests.
* [ ] Add a `DistilBertMaskedLM` task model and tests.
* [ ] Update `keras_nlp/models/__init__.py` to export `DistilBertMaskedLM` and `DistilBertMaskedLMPreprocessor`.

**Comment by mattdangerw** [comment]
@ADITYADAS1999 would you like to take this on?

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999 would you like to take this on?

I take this one. 🧑‍💻 
/assign

**Comment by ADITYADAS1999** [comment]
> * [ ]  Update `DistilBertTokenizer` to expect a mask token.

Hey @mattdangerw can you describe this update little bit or provide some similar references.

**Comment by mattdangerw** [comment]
@ADITYADAS1999 sure just take a look the code changes (not docstring changes) to the tokenizer here https://github.com/keras-team/keras-nlp/pull/653/files#diff-5f511b47f35f0f4a756ed6748c1a6d0feda574b387b81a0be366f3e4e16ea29e

This is basically a two liner, we need to add a `self.mask_token_id` property to the tokenizer base class. The mask token for DistilBert is `[MASK]` I believe (though worth checking!).

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999 sure just take a look the code changes (not docstring changes) to the tokenizer here https://github.com/keras-team/keras-nlp/pull/653/files#diff-5f511b47f35f0f4a756ed6748c1a6d0feda574b387b81a0be366f3e4e16ea29e
> 
> This is basically a two liner, we need to add a `self.mask_token_id` property to the tokenizer base class. The mask token for DistilBert is `[MASK]` I believe (though worth checking!).

thanks @mattdangerw ,  this is very helpful. 👍🏻

**Comment by ADITYADAS1999** [comment]
PR open at #724

**Comment by jayam30** [comment]
Hey!
I would like to take this issue up,

**Comment by ADITYADAS1999** [comment]
> Hey! I would like to take this issue up,

Hello @jayam30 this issue is already assigned.
You can check out contributor welcome issues here 
https://github.com/keras-team/keras-nlp/issues

**Comment by mattdangerw** [comment]
Fixed in https://github.com/keras-team/keras-nlp/pull/724
