### ISSUE TITLE
Add a BertMaskedLM task model

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#719]
In https://github.com/keras-team/keras-nlp/pull/653 we added a masked language modeling task for RoBERTa. We can make a similar change for the `BERT` model.

* [ ] Update `BertTokenizer` to expect a mask token.
* [ ] Add a `BertMaskedLMPreprocessor` preprocessor layer and tests.
* [ ] Add a `BertMaskedLM` task model and tests.
* [ ] Update `keras_nlp/models/__init__.py` to export `BertMaskedLM` and `BertMaskedLMPreprocessor`.

**Comment by shivance** [comment]
@Cyber-Machine are you still working on it ?

**Comment by jayam30** [comment]
Hey!
I would like to take this issue up, if others are not @Cyber-Machine
