### ISSUE TITLE
Add an XLMRobertaMaskedLM task model

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#720]
In https://github.com/keras-team/keras-nlp/pull/653 we added a masked language modeling task for RoBERTa. We can make a similar change for the `XLMRoberta` model.

* [ ] Update `XLMRobertaTokenizer` to expect a mask token.
* [ ] Add a `XLMRobertaMaskedLMPreprocessor` preprocessor layer and tests.
* [ ] Add a `XLMRobertaMaskedLM` task model and tests.
* [ ] Update `keras_nlp/models/__init__.py` to export `XLMRobertaMaskedLM` and `XLMRobertaMaskedLMPreprocessor`.

**Comment by shivance** [comment]
I believe it's similar to #718 , so I can take on this one as well!

**Comment by soma2000-lang** [comment]
I would love to work on this issue!

**Comment by shivance** [comment]
Hi @soma2000-lang are you still working on it? if not then I would take this one up !

**Comment by soma2000-lang** [comment]
@shivance yes ,I had also opened a pr for it,but had to close it for some reason.Will reopen another one.

**Comment by jayam30** [comment]
Hey!
I would like to take this issue up, if others are not @soma2000-lang

**Comment by soma2000-lang** [comment]
@jayam30 already opened a pr

**Comment by shivance** [comment]
Hi @mattdangerw , it's already been 1month+ since this issue has gone stale. Please assign me this issue, I'm already having a crack at it to see how challenging it is. So far the tests pass in local.

If you allow, I could open a PR. Thanks !

**Comment by soma2000-lang** [comment]
@shivance I am working on it but the tests are failing currently ,working on that.
