### ISSUE TITLE
Add an FNetMaskedLM task model

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#722]
In https://github.com/keras-team/keras-nlp/pull/653 we added a masked language modeling task for RoBERTa. We can make a similar change for the `FNet` model.

* [ ] Update `FNetTokenizer` to expect a mask token.
* [ ] Add a `FNetMaskedLMPreprocessor` preprocessor layer and tests.
* [ ] Add a `FNetMaskedLM` task model and tests.
* [ ] Update `keras_nlp/models/__init__.py` to export `FNetMaskedLM` and `FNetMaskedLMPreprocessor`.

**Comment by apupneja** [comment]
I would like to take up this issue. Thanks.

**Comment by Samarendra109** [comment]
I would like to contribute to this issue.

**Comment by jayam30** [comment]
Hey!
I would like to take this issue up

**Comment by mattdangerw** [comment]
Fixed in https://github.com/keras-team/keras-nlp/pull/740
