### ISSUE TITLE
Candidate metric: MAUVE

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#73]
**Is your feature request related to a problem? Please describe.**
This idea is from one best paper in NeurIPS 2021: [MAUVE: Measuring the Gap Between Neural Text and Human Text using Divergence Frontiers](https://arxiv.org/abs/2102.01454). Basically it proposes a new metric that measures how close machine generated text is like human text. This metric is specifically useful for open-end text generation.

**Describe the solution you'd like**
Write a Keras metric class that implements MAUVE. 

**Describe alternatives you've considered**
Probably... we should actually delete this section?

**Additional context**
MAUVE is not very easy to implement, because it does sampling, and requires an external model, so by nature it is not a light-weight metric. On the other hand, MAUVE is very successful at evaluating machine generated text in a human-like way. We will need to discuss a bit more about it.

**Comment by mattdangerw** [comment]
we are not focusing heavily on metrics like this right now, given that they are difficult to implement efficiently in a multi-backend context. can reopen if we shift priorities here
