### ISSUE TITLE
MaskLMMaskGenerator has wrong masked weight when there is no mask

### ISSUE THREAD

**Issue by jasonzhang2022** [keras-team/keras-nlp#746]
```
masker = nlp.layers.MaskedLMMaskGenerator(
    vocabulary_size=10, mask_selection_rate=0.5, mask_token_id=1,
    mask_selection_length=1)
masked_output= masker(tf.ragged.constant([[2, 3, 3,3,3,3], [5, 2, 3, 4,  4, 4,4]]))

print(masked_output)
```
Here is one output

```
{'token_ids': <tf.RaggedTensor [[2, 3, 3, 3, 3, 3], [5, 2, 3, 4, 4, 4, 1]]>, 'mask_positions': <tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[0],
       [6]])>, 'mask_ids': <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [4]], dtype=int32)>, 'mask_weights': <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>}
```

For the first sequence, no token is masked since output token_ids has no '1'.  The '0' in masked_positions should be padding.  But its masked_weight  is 1. Shouldn't it 0?

**Comment by chenmoneygithub** [comment]
Sorry, actually I forgot the context - the `MaskedLMMaskGenerator ` has a certain rate to use random token to do the mask, as proposed by the BERT paper. It also has certain rate to keep the original token. Please see [this arg docstring](https://github.com/keras-team/keras-nlp/blob/10d451ea555289acdc04fc8432a09646f36128d8/keras_nlp/layers/masked_lm_mask_generator.py#L54)

If you want to always generate mask with the `mask_token_id`, you can set `mask_token_rate=1` and `random_token_rate=0`. Hope this helps!

**Comment by jasonzhang2022** [comment]
I see. The masked_weight is the token is selected for mask. The actual mask can be mask_token, random token or **unchanged**.
