### ISSUE TITLE
Streamline Your Code Copying Experience: Add a One-Click Copy Button for Code Segments

### ISSUE THREAD

**Issue by Neeshamraghav012** [keras-team/keras-nlp#748]
I kindly request the implementation of a button that can be clicked and automatically copies the entire code to the clipboard. This feature has become a common practice among many websites and would greatly improve the user experience by eliminating the frustration of manually selecting code through a trackpad or mouse. Thank you.

**Example**

![Example Image](https://res.cloudinary.com/hire-easy/image/upload/v1676203733/Screenshot_2023-02-12_at_5.35.19_PM_wrhg5c.png)

**Comment by abheesht17** [comment]
@Neeshamraghav012, did you mean to open this on the keras.io repo: https://github.com/keras-team/keras-io?

**Comment by Neeshamraghav012** [comment]
@abheesht17 yeah I mean it should be included in all of Keras documentation.

**Comment by abheesht17** [comment]
@Neeshamraghav012 - ah, I see. Could you please open it on the keras.io repo? That is where all the documentation is present.
