### ISSUE TITLE
beam_search(keras_nlp.utils.beam_search) is not working,it's getting error in english to spanish translation while decoding it

### ISSUE THREAD

**Issue by Alwaysadil** [keras-team/keras-nlp#750]
**Describe the bug**

**Expected behavior**

**Additional context**

**Would you like to help us fix it?**

**Comment by Alwaysadil** [comment]
@jbischof sir check this link
 https://colab.research.google.com/drive/1JgVMEqQIsMGVE3ZvMhgBQApSJM2bT8cD?usp=sharing

**Comment by Alwaysadil** [comment]
@jbischof  sir, check this colab link 
https://colab.research.google.com/drive/1JgVMEqQIsMGVE3ZvMhgBQApSJM2bT8cD#scrollTo=c-jZRJv7-CsL

**Comment by abheesht17** [comment]
@Alwaysadil - this is a potential fix for your issue. Replace your `token_probability_fn()` function with the one below:

```
    def token_probability_fn(decoder_input_tokens):
        num_samples = tf.shape(decoder_input_tokens)[0]
        repeats = num_samples // batch_size
        encoder_input_tokens_repeated = tf.repeat(
            encoder_input_tokens,
            repeats=repeats,
            axis=0
        )
        return transformer(
            [encoder_input_tokens_repeated, decoder_input_tokens]
        )[:, -1, :]
```

The logic for doing this is as follows:
In beam search, we don't pass the the prompt to the `token_probability_fn` as is. We repeat the prompt `num_beams` times (because that's how beam search works). This causes a mismatch between `encoder_input_tokens` and `decoder_input_tokens` on `axis=0`. If we make the axis=0 dimension equal for both, things work fine!

@jbischof - should we document this?

**Comment by abheesht17** [comment]
Here is the link of the working Colab: https://colab.research.google.com/drive/1jtIRbIt0xqN-yqlfNUwlKAeavg4OO0WT?usp=sharing.

**Comment by Alwaysadil** [comment]
@abheesht17 sir, now its working like a "greedy search " not like the "beam search".It's only predicting only one spanish sentence when i gave num_beams=2.Check this link https://colab.research.google.com/drive/1YpB8935sFtUIB4tBP5DFmva4U0RHJvTp?usp=share_link   
and see the decode_sequences function

**Comment by abheesht17** [comment]
@Alwaysadil - it is not working like greedy search. The convention for beam search is to return one sequence at the end, the one with the highest overall probability. Check this: https://towardsdatascience.com/foundations-of-nlp-explained-visually-beam-search-how-it-works-1586b9849a24. In particular, these lines:

```
It repeats this process till it generates two best sequences that end with an “<END>” token.

It then chooses the sequence that has the highest combined probability to make its final prediction.
```

KerasNLP follows the same thing - it returns the sequence with the highest overall probability (although at every step, it keeps `num_beams` threads running forward).

Code reference for returning sequence with highest overall probability: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/utils/text_generation.py#L389-L393.

If you want `num_beams` number of sequences at the end, you can hack the code and return `beams`: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/utils/text_generation.py#L383. Let me know if you want some help with this, and I'll do it for you!

Currently, KerasNLP doesn't support outputting the top "num_beams" sequences, although we might want to do this. @mattdangerw, @jbischof - what do you think? Should be a simple enough tweak.

**Comment by abheesht17** [comment]
@Alwaysadil - here is the notebook: https://colab.research.google.com/drive/1jtIRbIt0xqN-yqlfNUwlKAeavg4OO0WT?usp=sharing. This returns `num_beams` number of sequences.

@mattdangerw, @jbischof , I have made the change here: https://github.com/abheesht17/keras-nlp/blob/beam_search_return_all_seqs/keras_nlp/utils/text_generation.py#L400-L414. Let me know if this is worth opening a PR for.

**Comment by mattdangerw** [comment]
Yeah, I think this could be worth adding and option to output all the beams. It's unclear to me what the ideal return type is though... Can we just return one sequence with shape `(batch_size, num_beams, length)`? Do you need to return log probs as well for the beams? It might be worth an attempt to survey how other libraries handle this (and how often this feature is used).

**Comment by Alwaysadil** [comment]
@abheesht17 thank you sir,it's working now.

**Comment by abheesht17** [comment]
@mattdangerw, HF returns tensor of shape `(batch_size * num_beams, length)`: https://huggingface.co/docs/transformers/internal/generation_utils#transformers.generation.BeamSearchDecoderOnlyOutput.sequences. They also return the scores: https://huggingface.co/docs/transformers/internal/generation_utils#transformers.generation.BeamSearchDecoderOnlyOutput.sequences_scores.

**Comment by abheesht17** [comment]
Closing this issue as this isn't exactly a bug. Will open a new issue for returning all beams.
