### ISSUE TITLE
Explore Ways to Make Models More Efficient

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#752]
How can we make KerasNLP's models more efficient? These changes can be simple to start off with - for example, something as simple having a vocabulary size which is a multiple of 64. We can track all potential changes here in this thread.

I'll be starting with experimenting with vocabulary sizes and checking whether we get substantial gains in speed/efficiency.

Feel free to give other suggestions, or start working on a few suggestions yourself :)

**Comment by shivance** [comment]
I think in this case, deep learning best practices books might be very helpful.

**Comment by jbischof** [comment]
@abheesht17 unlike CV most of our models are trained by others. Do we have a lot of flexibility here?

**Comment by xihajun** [comment]
- Maybe things like packedBERT would be interesting? (paper<sup>[2]</sup>, and some implementation<sup>[1]</sup>)? 
  > it tries to pack a few short Q&A data together to increase the efficiency

[2]: https://github.com/graphcore/tutorials/tree/master/blogs_code/packedBERT
[1]: https://arxiv.org/pdf/2107.02027.pdf
