### ISSUE TITLE
Return All Beams from Beam Search Utility

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#770]
Follow-up to https://github.com/keras-team/keras-nlp/issues/750#issuecomment-1439963933

- Return all beams (tensor of shape `(batch_size, num_beams, sequence_length)`).
- Return the beam scores as well (tensor of shape `(batch_size, num_beams)`).

The changes are to be made to this utility function: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/utils/text_generation.py#L213.

@mattdangerw, do we want to sort the outputs based on log prob and return? Or is that unnecessary overhead?

Some basic tinkering done because a user wanted a quick fix: https://github.com/abheesht17/keras-nlp/blob/beam_search_return_all_seqs/keras_nlp/utils/text_generation.py#L400-L414

**Comment by TheAthleticCoder** [comment]
Hey! 
I would like to take this issue up

**Comment by jayam30** [comment]
Hey i want to contribute, with this issue, please assign me

**Comment by mattdangerw** [comment]
@chenmoneygithub any thoughts on how we would want to add this?

**Comment by chenmoneygithub** [comment]
The user request is valid to me. 

We may want to directly contribute to [`keras_nlp.samplers.BeamSampler`](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/samplers/beam_sampler.py), as we are going to use this to replace the utility, and the utility will be deleted in the future.
