### ISSUE TITLE
Add `BartClassifier`

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#777]
Should be similar to `BertClassifier`

**Comment by shivance** [comment]
cc: @mattdangerw if this is needed, i would love to contribute!

**Comment by jbischof** [comment]
@shivance it's a bit different actually. Check out the BART paper for details on classification

**Comment by mattdangerw** [comment]
@shivance we will want this eventually, but need to do a little scoping here first. E.g. we are still lacking a preprocessing layer for this class, and need to plan how this will work in both classification and seq2seq contexts.

I can update with some more details of what we would want here in the next couple weeks and assign you when it is ready for work.

**Comment by shivance** [comment]
Sounds good Matt.

**Comment by shivance** [comment]
Hey @mattdangerw !
`BartPreprocessor` has already been merged, do you think that it is good time to move to tasks like classifier now?

**Comment by jbischof** [comment]
Don't forget to attached the PR if this was actually done. If it was abandoned, we should close as not completed.
