### ISSUE TITLE
Add a UnicodeCharacterTokenizer

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#78]
This would be a simple tokenizer which has no vocabulary, and simply converts text to unicode codepoints.

## Potential docstring and usage

```python
"""
Unicode character codepoint tokenizer.
 
This tokenizer is a vocabulary free tokenizer which will tokenize text as
unicode character codepoints.
 
Args:
   lowercase: if true, lowercase text before tokenizing.
   sequence_length: If set, the output will be converted to a dense
     tensor and padded/trimmed so all outputs are of sequence_length.
   normalization_form: One of the following string values (None, 'NFC',
     'NFKC', 'NFD', 'NFKD'). If set will normalize unicode to the given form
     before tokenizing.
   errors: One of ('replace', 'remove', 'strict'). Specifies the `detokenize()`
     behavior when an invalid codepoint is encountered. (same behavior as
     https://www.tensorflow.org/api_docs/python/tf/strings/unicode_transcode)
"""

tokenizer = keras_nlp.tokenizers.UnicodeCharacterTokenizer()

inputs = ["▀▁▂▃▄", "hello"]
tokens = tokenizer.tokenize(inputs)
>>> <tf.RaggedTensor [
      [9600, 9601, 9602, 9603, 9604],
      [104, 101, 108, 108, 111]]>

outputs = tokenizer.detokenize(tokens)
outputs = [x.decode("utf-8") for x in strings.numpy().tolist()]
>>> ['▀▁▂▃▄', 'hello']
```

## Colab demonstrating basic functionality:

https://colab.sandbox.google.com/gist/mattdangerw/9d9dcb8b640d8183a614ddd6f92fe368/unicodecharactertokenizer.ipynb

**Comment by aflah02** [comment]
Hey
I can take this up, I'm also working on the other rank issue as well and will probably get that done by the weekend
I need one clarification though in the last example on colab there are invalid codepoints so for those kinds of things should we still parse it? or raise an error of some sort?

**Comment by aflah02** [comment]
Hey @mattdangerw 
If the input is something like `["a b c", "b c", "a b", "b a"]` is the expected output like this - 
```tf.Tensor([97 32 98 32 99], shape=(5,), dtype=int32)
tf.Tensor([98 32 99], shape=(3,), dtype=int32)
tf.Tensor([97 32 98], shape=(3,), dtype=int32)
tf.Tensor([98 32 97], shape=(3,), dtype=int32)
```
or the whitespace character shouldn't appear?

The code sample I ran to print this output is:

```
tokenizer = keras_nlp.tokenizers.UnicodeCharacterTokenizer()
unbatched = tf.data.Dataset.from_tensor_slices(["a b c", "b c", "a b", "b a"])
unbatched = unbatched.map(tokenizer)
for element in unbatched:
  print(element)
```

**Comment by mattdangerw** [comment]
@aflah02 we should definitely preserve whitespace here! The codepoint for the space character should be included, which will make this fully reversible.

Users could strip whitespace before this layer if they want, but in general I would think character based models will want to include whitespace in the model input.

**Comment by aflah02** [comment]
Thanks for the clarification!

**Comment by aflah02** [comment]
I think it's worth keeping an input_encoding and output_encoding parameter as well which we can default to "UTF-8" but optionally can take in either of "UTF-8", "UTF-16-BE", or "UTF-32-BE"

**Comment by mattdangerw** [comment]
Yeah, accepting other encodings would be fine, though I don't think it's a requirement for the initial version.

In that case, maybe rename the `normalization_form` arg to `utf8_normalization_form` and throw an error if that arg is set and the encoding != utf8.

**Comment by aflah02** [comment]
Hey @mattdangerw 
When we pad the input sequence should the element used to pad by be customizable? As during detokenization it will become a part of the string

**Comment by mattdangerw** [comment]
I think we can just assume a value of 0 to pad for now. And strip 0 values during `detokenize`. I made a comment about this on https://github.com/keras-team/keras-nlp/pull/80. The line `tf.ragged.boolean_mask(inputs, inputs != 0)` might be useful.

Overall, I would encourage being conservative in what we offer in this initial version--it's easier to add more functionality down the road then remove it. So maybe only support utf-8, fix the padding token, and see what users ask for.

**Comment by aflah02** [comment]
Makes sense, I'll get this done quickly
