### ISSUE TITLE
Fix Fenced Doc-strings

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#782]
Ran the fenced doc-string tests, and bumped into some test failures: https://p.ip.fi/JWSr.

To fix this issue, do the following:
- Add `keras_nlp.tokenizers.byte_pair_tokenizer`, `keras_nlp.tokenizers.sentence_piece_tokenizer`, `keras_nlp.tokenizers.word_piece_tokenizer` to the list here: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/tests/doc_tests/docstring_test.py#L106-L117.
- Import from the root of the library: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/albert/albert_masked_lm_preprocessor.py#L121-L123. For example, `keras_nlp.models.AlbertTokenizer` instead of just `AlbertTokenizer`.
- Fix typo here: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/f_net/f_net_classifier.py#L81. Should not "FNet" not "Fnet". Make the same change everywhere in this file.

After you are done making these changes, run this Colab to check whether the tests pass: https://colab.research.google.com/drive/1JGxvuqga-uT7dYFggmzIoB12nrWO4xYv?usp=sharing.

**Comment by abheesht17** [comment]
@atharvapurdue, would you like to take this up?

**Comment by abheesht17** [comment]
@mattdangerw, can we set this up as a weekly cron job? Won't have to manually run tests again and again.

**Comment by atharvapurdue** [comment]
Sure @abheesht17 , I would like to take this up if it is available. Looks like a good first issue! Thanks a lot!

**Comment by abheesht17** [comment]
Great, assigned the issue to you!

**Comment by mattdangerw** [comment]
@abheesht17 yeah we absolutely do need to set up some sort of regularly scheduled testing that is not on each PR.

I would prefer a nightly test that runs every "extra large" test. Issue is that would probably need to be setup by me or @chenmoneygithub and we are both pretty swamped! But we should soon. Let me file an issue.
