### ISSUE TITLE
Add a ByteTokenizer

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#79]
This would be a simple tokenizer which has no vocabulary, and simply converts text to raw bytes.

## Potential docstring and usage

```python
"""
Raw byte tokenizer.

This tokenizer is a vocabulary free tokenizer which will tokenize text as
as raw bytes from [0, 256).
 
Args:
   lowercase: if true, lowercase text before tokenizing.
   sequence_length: If set, the output will be converted to a dense
     tensor and padded/trimmed so all outputs are of sequence_length.
   normalization_form: One of the following string values (None, 'NFC',
     'NFKC', 'NFD', 'NFKD'). If set will normalize unicode to the given form
     before tokenizing.
   errors: One of ('replace', 'remove', 'strict'). Specifies the `detokenize()`
     behavior when an invalid byte sequence is encountered. (same behavior as
     https://www.tensorflow.org/api_docs/python/tf/strings/unicode_transcode)
"""

tokenizer = keras_nlp.tokenizers.ByteTokenizer()

inputs = ["▀▁▂▃▄", "hello"]
tokens = tokenizer.tokenize(inputs)
>>> <tf.RaggedTensor [
      [226, 150, 128, 226, 150, 129, 226, 150, 130, 226, 150, 131, 226, 150, 132],
      [104, 101, 108, 108, 111]]>


outputs = tokenizer.detokenize(tokens)
outputs = [x.decode("utf-8") for x in strings.numpy().tolist()]
>>> ['▀▁▂▃▄', 'hello']
```

## Colab demonstrating basic functionality:

https://colab.sandbox.google.com/gist/mattdangerw/99e8f3795e37fe539731dcbfc1c09d47/bytetokenizer.ipynb

**Comment by abheesht17** [comment]
Hey, @mattdangerw! I'd like to take this up

**Comment by abheesht17** [comment]
Do we also have to define the `get_vocabulary()`, `vocabulary_size()`, `id_to_token()` and `token_to_id()` functions?

Of course, the vocabulary will just be a list of 256 characters. And vocabulary size will be 256. And `id_to_token()` is simply `tf.constant([i.tobytes() for i in np.arange(256, dtype=np.uint8)])`. So, do we want these functions?

**Comment by mattdangerw** [comment]
Re: replacement char, makes sense to have that arg.

Re: vocabulary_size, let's add that, returning 256. It will be helpful for code examples. I am less convinced token_to_id and id_to_token make sense, let's hold off there.

Re: raw bytes instead of ints of some form, what is the use case? I'm not sure that we need it.

**Comment by abheesht17** [comment]
Thanks! Noted, will make changes in the PR :)

**Comment by abheesht17** [comment]
Thank you for all the help, @mattdangerw! :D
