### ISSUE TITLE
Generate documentation for keras-nlp

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#81]
We need to generate symbol documentation and host them keras.io (and tensorflow.org?).

**Comment by mattdangerw** [comment]
Assigning myself as a placeholder; this will need to be done by someone on the keras team.

**Comment by adhadse** [comment]
Do the keras-team have any plan/tool in mind to generate documentation?

**Comment by mattdangerw** [comment]
For sure we would symbol documentation and guides on keras.io, and possibly in the future on tensorflow.org as well.

So we will use the tooling for documentation generation for [keras-io](https://github.com/keras-team/keras-io), but if you have ideas on how we could improve there you could definitely open an issue on that repo.

**Comment by mattdangerw** [comment]
This is done!
