### ISSUE TITLE
Add public API export statements

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras-nlp#812]
We're switching to a packaging system that uses an allowlist for public API symbols. All public API symbols (classes, functions) should be decorated with `@keras_nlp_export` as follows:

```python
from keras_nlp.api_export import keras_nlp_export

@keras_nlp_export("keras_nlp.layers.FNetEncoder")
class FNetEncoder(keras.layers.Layer):
    ...
```

Note that these statements include serialization, so you don't need any `register_keras_serializable` decorator calls anymore.

For an example PR, see https://github.com/keras-team/keras-nlp/pull/811/files

We need to do this for all symbols listed on keras.io: https://keras.io/api/keras_nlp/

**Comment by shivance** [comment]
I would like to take up this issue !

**Comment by fchollet** [comment]
@shivance awesome -- please open a PR (or multiple PRs for different sections of the API...)

**Comment by fchollet** [comment]
@shivance with the outstanding PRs, we have everything covered (I think?). Thanks a lot for the help with this!

**Comment by shivance** [comment]
> @shivance with the outstanding PRs, we have everything covered (I think?). Thanks a lot for the help with this!

Cheers !
