### ISSUE TITLE
Call `super.config()` in `BartBackbone`'s `get_config()`

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#813]
We should call `super().config()` here: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bart/bart_backbone.py#L238, update the config with `BARTBackbone`-specific keys and return the config. Check this for reference: https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_backbone.py#L204.

**Comment by abheesht17** [comment]
@Rayquaza6102, would you like to take up this issue?

**Comment by shivance** [comment]
Hi @abheesht17 can I take this issue?

**Comment by mattdangerw** [comment]
@shivance all looks good and let's land this!

In the future, these "good first issue" tags may be best left to contributors who are making there first couple contributions to the library. We want these as simple places to get started.
