### ISSUE TITLE
Remove API export decorator from base classes

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#823]
We should remove the API export decorator from base classes like [`Backbone`](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/backbone.py#L26-L27), [`Preprocessor`](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/preprocessor.py#L22-L23), [`Task`](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/task.py#L26-L27) and [`Tokenizer`](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/tokenizers/tokenizer.py#L22-L23). These classes are meant to be used internally.

**Comment by abheesht17** [comment]
@shivance, would you like to take this up?

**Comment by shivance** [comment]
Sure, piece of cake.

**Comment by shivance** [comment]
btw @abheesht17 , if that's the case we should remove it from `Sampler` as well.
