### ISSUE TITLE
Adding `XXBackboneTPUTests` 

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#838]
I observed that currently we have unit tests for TPU for `BertBackbone` and `WhisperBackbone` .

Are we planning to add TPUTests for other models too ? If yes, then please assign me the issue.

cc : @mattdangerw @chenmoneygithub

**Comment by abheesht17** [comment]
Except for DeBERTa, I guess we can add TPU tests for all models.

**Comment by shivance** [comment]
Sounds good @abheesht17 , Please assign me this issue.
Thanks

**Comment by mattdangerw** [comment]
Yeah I am pretty sure this will be useful, thanks! @chenmoneygithub would be the best person to ask though.
