### ISSUE TITLE
Modify `generate()` method in `GPT2CausalLM` to support chatbot

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#844]
The gap we have is about the `end_token_id`. In a chatbot system like DialoGPT , the user prompt needs to be concatenated by an `end_token` before generation, otherwise it will just generate `end_token` and stop. One simple fix is to add an argument to `generate()` method, e.g., `append_end_token=False`, when which is `True` the prompt will be appended by an `end_token` before calling our `sampler`. 

@mattdangerw This should be an easy fix, but we need to make a call on the arg name and if we want to solve it at `generate()` level.

**Comment by shivance** [comment]
Sounds interesting!

**Comment by TheAthleticCoder** [comment]
Hey! 
According to the [paper](https://arxiv.org/pdf/1911.00536.pdf), the input training data is segmented and joined by an end-of-sentence token.
![image](https://user-images.githubusercontent.com/55716761/228679046-ac11442d-8fb9-4f1a-8005-fabe8a133ff6.png)

I think something which can be even more helpful to understand their data flow is in their official code, this example [here](https://github.com/microsoft/DialoGPT/blob/master/gradiodemo.py#L13) which I tested out [here](https://colab.research.google.com/drive/1c37DWamYJXnm0Zko8F3P0KyGrGqtnoXl?usp=sharing). The colab link shared shows an example conversation of three turns where after every input given and generated sequence, an `<eos>` token is passed(in the code `50256`).

**Comment by mattdangerw** [comment]
Thinking about this more, we need to take it on more broadly. It isn't really enough to cover handling `generation()` well for seq2seq to seek case, we should really be covering an entire fine-tuning and inference flow.

In some ways, this would be easiest if we could do the special token packing in string space, because we know that in some cases that is what people will want to do...

```python
imdb_ds = load_imdb()
causal_lm = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en")
causal_lm.fit(imdb_ds)
causal_lm.predict("That movie was")

cnn_dailymail_ds = load_cnn_dailymail()
combined_ds = cnn_dailymail_ds.map(
    lambda s: tf.strings.join(s["article"], "TL;DR", s["highlights"]),
)
causal_lm = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en")
causal_lm.fit(combined_ds)
causal_lm.predict("The situation in Congress [...entire paragraph...] TL;DR")

chat_response_ds = load_chat_response()
combined_ds = chat_response_ds.map(
    lambda s: tf.strings.join(s["context"], "<|endoftext|>", s["reply"]),
)
causal_lm = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en")
causal_lm.fit(combined_ds)
causal_lm.predict("What is the capital of Argentina?")
```

**Comment by chenmoneygithub** [comment]
@mattdangerw I agree, it's also possible that users want to convert dialogue training data to something like "<dialogue1><|endoftext|><dialogue2><|endoftext|><dialogue3><|endoftext|>", doing which on string space is much easier.

**Comment by mattdangerw** [comment]
Worth testing out, but I believe the workflows above https://github.com/keras-team/keras-nlp/issues/844#issuecomment-1489460480 should now be working. Tentatively closing this, but we can reopen if needed.
