### ISSUE TITLE
Support all-MiniLM-L6-v2 model

### ISSUE THREAD

**Issue by innat** [keras-team/keras-nlp#851]
**Is your feature request related to a problem? Please describe.**

The [sentence transformer](https://github.com/UKPLab/sentence-transformers) provides an easy method to compute dense vector representations for sentences, paragraphs, and images. It is written in pytorch. Using transformer-huggingface it is possible to build tensorflow layer. **all-MiniLM-L6-v2** is one the most popular model.  https://www.sbert.net/docs/pretrained_models.html

- https://github.com/UKPLab/sentence-transformers
- https://www.sbert.net/index.html

**Describe the solution you'd like**

Huggingface implementation: https://www.philschmid.de/tensorflow-sentence-transformers

**Additional context**

This requests is motivated from recent kaggle competition, [here](https://www.kaggle.com/competitions/stable-diffusion-image-to-prompts). Where the ground truth embedding is generated from `SentenceTransformer(all-MiniLM-L6-v2')` model [link](https://www.kaggle.com/code/inversion/calculating-stable-diffusion-prompt-embeddings). What is the task about ([check](https://www.kaggle.com/competitions/stable-diffusion-image-to-prompts/discussion/393805))?

More request 
- https://github.com/UKPLab/sentence-transformers/issues/1460
- https://github.com/UKPLab/sentence-transformers/issues/1132

**Comment by Warlord-K** [comment]
Hi, I wish to work on this if this has not been assigned to anyone currently and if this feature is required. I am looking forward to contribute to KerasNLP.

**Comment by antonin-primordial** [comment]
Was that included @innat?
