### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ADITYADAS1999** [keras-team/keras-nlp#854]
ModuleNotFoundError: No module named 'keras_nlp.models.t5'

![buggg](https://user-images.githubusercontent.com/58718316/225496329-7c987e2f-e436-42db-b93c-e6000fc78cf3.PNG)

cc: @mattdangerw

**Comment by TheAthleticCoder** [comment]
Hey! You can use this command to get the latest stable release running:
```
!pip install -q --upgrade keras-nlp 
import keras_nlp
keras_nlp.__version__
```
I believe that the command used in the image installs the library directly from the master branch which contains unreleased features.

**Comment by ADITYADAS1999** [comment]
> Hey! You can use this command to get the latest stable release running:
> 
> ```
> !pip install -q --upgrade keras-nlp 
> import keras_nlp
> keras_nlp.__version__
> ```
> 
> I believe that the command used in the image installs the library directly from the master branch which contains unreleased features.
![buggg](https://user-images.githubusercontent.com/58718316/225508130-2ba85d09-7df2-43c6-9d21-c712777b4362.PNG)

still throw errors

**Comment by ADITYADAS1999** [comment]
> Hey! You can use this command to get the latest stable release running:
> 
> ```
> !pip install -q --upgrade keras-nlp 
> import keras_nlp
> keras_nlp.__version__
> ```
> 
> I believe that the command used in the image installs the library directly from the master branch which contains unreleased features.

![bugg1](https://user-images.githubusercontent.com/58718316/225510938-8ef6de2f-ada7-4644-b745-0ff30c7f2c85.PNG)

Now it's working fine, thanks @TheAthleticCoder
