### ISSUE TITLE
Mirror BERT testing speedups for other models

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#866]
We can imitate the changes in https://github.com/keras-team/keras-nlp/pull/859/ for all other models in repo.

Let's do this one model at a time, to keep things granular.

You can run a single models test with `pytest keras_nlp/models/XX` and should see a noticeable improvement in time elapsed if all things go well.

Checklist for a given model:
 - [ ] Add a serialization test for all classes.
 - [ ] Mark the saved model testing as "large" for all classes.
 - [ ] Make the backbone sizes as small as possible while still testing all logic (e.g. num_layers=2).
 - [ ] Only run a single `jit_compile=False` test per model class. E.g. `test_classifier_fit_no_xla`.
 - [ ] Other minor readability and efficiency improvements (check the original PR carefully).

**Comment by mattdangerw** [comment]
Also, we are getting a lot of contributor interest right now! Let's all try to..

 - Use this issue to communicate.
 - Only work on a single model at a time. E.g. wait till you have a PR ready for one model before starting on the next.
 - Be patient with each other as we all self organize here :)

Thanks!

**Comment by shivance** [comment]
Can take this up for Roberta. Thanks.

**Comment by TheAthleticCoder** [comment]
Can take this up for Debert_v3. Thanks!

**Comment by soma2000-lang** [comment]
Will take this up for Distill_bert and Albert

**Comment by ADITYADAS1999** [comment]
I go through bert, thanks

**Comment by susnato** [comment]
I would like to take this up for `xlm_roberta`.

**Comment by abuelnasr0** [comment]
I will take GPT2

**Comment by susnato** [comment]
I would like to take OPT.
