### ISSUE TITLE
Rework model docstrings for progressive disclosure of complexity

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#867]
We need to simplify our model docstring so they are more easily understandable, and we can start by porting the changes in https://github.com/keras-team/keras-nlp/pull/843 to all other models.

Let's do this one model at a time, to keep things granular.

Checklist:

 - [ ] Make sure to update any "custom vocabulary" examples to match the model actual vocabulary type and special token requirements (varies per model).
 - [ ] Test out all docstring snippets!
 - [ ] Make sure to follow our code style guidelines re indentation etc.

**Comment by mattdangerw** [comment]
Also, we are getting a lot of contributor interest right now! Let's all try to..

Use this issue to communicate.
Only work on a single model at a time. E.g. wait till you have a PR ready for one model before starting on the next.
Be patient with each other as we all self organize here :)
Thanks!

**Comment by shivance** [comment]
I can take this up for Roberta. Thanks.

**Comment by ADITYADAS1999** [comment]
Thanks for this issues & guideline, I want to work with f_net model.

**Comment by soma2000-lang** [comment]
I am taking for fnet

**Comment by soma2000-lang** [comment]
@mattdangerw I am working on bert

**Comment by TheAthleticCoder** [comment]
I shall take this up for deberta_v3 then

**Comment by abuelnasr0** [comment]
I'd like to work with GPT2

**Comment by Warlord-K** [comment]
@mattdangerw I'd like to take up opt.

**Comment by abuelnasr0** [comment]
I will take XLMRoberta instead of GPT-2 for now as it is not exported to keras_nlp library to be used in colab to test docsting snippets. I will continue my work with GPT-2 after installing dependencies in my local machine soon, if no one take it.

**Comment by soma2000-lang** [comment]
I am taking up T5

**Comment by susnato** [comment]
I am taking this up for `Whisper`.

**Comment by shivance** [comment]
@mattdangerw & @chenmoneygithub  RoBERTa is still pending.
@abuelnasr0 is a new contributor interested in contributing to KerasNLP. As the issue is mostly good first issue, it can be good start for him.
Abu you can start working on this issue for RoBERTa, good luck !

**Comment by mattdangerw** [comment]
Yeah, sorry this issue might keep getting marked as close due to thing like `"Partially fixes #867"` in the PR description. Will keep reopening for now.

**Comment by mattdangerw** [comment]
Also thanks everyone for the work on this issue!
