### ISSUE TITLE
Add a GenerativeTask base class

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#868]
With https://github.com/keras-team/keras-nlp/pull/804, we are moving generative compilation into the task model.

We should add a base class for all generative tasks models that can pull out some of the common compilation code for tasks with a `generate` method.

**Comment by jbischof** [comment]
Is the idea `Task` -> `GenerativeTask` -> `GPTCausalLM`?

**Comment by mattdangerw** [comment]
> Is the idea `Task` -> `GenerativeTask` -> `GPTCausalLM`?

Yeah probably! I don't think it makes sense to put this stuff on the task base class. So as you say, it's that or mixins.

**Comment by mattdangerw** [comment]
This is fixed!
