### ISSUE TITLE
[Query] Implementing Models

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#87]
Is the KerasNLP team also looking to implement entire models or are we restricting ourselves to building blocks?

For example, if we take FNet, we currently have its encoder block in KerasNLP. So, will we stack these encoder blocks and implement the entire FNet model in `keras_nlp.models`, and at the same time, will we upload pretrained models weights to TFHub? Or will we leave that to the main TensorFlow repository (since many models are already present in the TF Model Garden)?

Thanks!

**Comment by mattdangerw** [comment]
This is actively under discussion. We definitely do want a way to use our components here in pretrained models, but that may not be done in this repo. So for now at least, the correct mental model for keras-nlp is a library of components, not models.

We will definitely be giving more guidance here going forward.

**Comment by abheesht17** [comment]
Nice!

Also, can I get my GSoC application pre-reviewed by the KerasNLP team before submission on the portal?

**Comment by chenmoneygithub** [comment]
@abheesht17 Sorry we won't provide any feedback on GSoC proposals at this time.

**Comment by mattdangerw** [comment]
@abheesht17 wanted to add more here re-GSOC. If you have a proposal in a google doc or somewhere sharable, you could send that to us a keras-nlp@google.com, that's a good way to flag the whole group. I can't guarantee we will have time/bandwidth for feedback though! In general, contributing here is probably the best way to show fit.

As for news, we won't even know how many applications we have until the 19th. So we won't have much to share until the week of the 25th at the earliest. So please be patient until then!

Thanks!

**Comment by abheesht17** [comment]
Great, thank you, @mattdangerw! :)
