### ISSUE TITLE
Natural Language Tasks 

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#878]
While [#1253](https://github.com/keras-team/keras-io/pull/1253) : Semantic similarity tutorial using KerasNLP is flowing good, (and Is close to be merged on keras-io). I have also been working on Token Classification guide, then there is also a text generation guide issue #683. which makes me think how can we add a feature to make KerasNLP easy to use while still being modular and easy to build transformers from scratch.

Will we support Natural Language tasks like  `BERTSemanticSimilarityClassifier` or `BERTTokenClassifier` like Huggingface? 

Edit : Are we still planning on supporting #624 and #625 ?

cc: @chenmoneygithub @mattdangerw

**Comment by TheAthleticCoder** [comment]
Yes, would we also support tasks such as `BERTQuestionAnswering` and `BERTSpanLabelling` in the forms of complete natural language tasks or would we have a shared pre-trained encoder architecture for all the tasks along with maybe separate files of task-specific output layers for each task?

**Comment by mattdangerw** [comment]
Yeah! I think we can keep looking at https://github.com/keras-team/keras-nlp/issues/754, really try to produce a good example of what token classification would look like with our lower-level API, and then use that to start thinking about an end-to-end, task level object here.

**Comment by shivance** [comment]
Sounds good ! I'm working on Token Classification, but current major focus is towards merging Semantic Similarity keras-io example in !
