### ISSUE TITLE
 Add training script for generating model like GPT2 

### ISSUE THREAD

**Issue by ADITYADAS1999** [keras-team/keras-nlp#891]
There are still no issues for generating tasks for training scripts. The team do have training script for separate training, Bert and stuffs but the team do not have training script for generating tasks like GPT2. 
Is our team interested for looking for add this things to the library ? 

cc : @mattdangerw  @chenmoneygithub

**Comment by shivance** [comment]
I think @chenmoneygithub is already working on something similar.

**Comment by ADITYADAS1999** [comment]
> I think @chenmoneygithub is already working on something similar.
> 
> #447 #689

👨‍💻 sounds great

**Comment by chenmoneygithub** [comment]
Yea, I will open more contributor-welcome issues after wrapping up our stuff.
