### ISSUE TITLE
kerasNLP assisted StableDiffusion?

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#892]
Today I was going through KerasCV's implementation of StableDiffusion, (haven't read paper yet).

Model Architecture :
![image](https://user-images.githubusercontent.com/51750587/226410424-087c8d41-8f42-43ce-8bef-9c456b1bc37b.png)

[text_encoder.py](https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/stable_diffusion/text_encoder.py) represents kerasCV's implementation of text encoder (it uses CLIP embedding, attention) . 

This thought immediately cross my mind. What if we use classical knowledge rich transformer like BERT family in place of CLIP encoder. How will results look like ? Can KerasNLP and KerasCV come together to build a new modular pipeline for stable diffusion?

**Comment by shivance** [comment]
cc: @jbischof @mattdangerw @fchollet

**Comment by mattdangerw** [comment]
My thoughts (without being close to an expert on stable diffusion).

I think overall these models are expensive to train, and changing your text encoder would essentially require retraining your whole model from scratch. Definitely an interesting research idea to experiment with different encoders, but probably a bit out of scope for us right now.

However there might be some collaboration still to do between the projects. `BytePairTokenizer` in KerasNLP is roughly (maybe exactly?) the same as the stable diffusion tokenizer, with support for `tf.data` and `TFLite`. So long term I believe the plan is to have KerasCV's stable diffusion implementation depend on text preprocessing components for the KerasNLP library.

**Comment by TheAthleticCoder** [comment]
> This thought immediately cross my mind. What if we use classical knowledge rich transformer like BERT family in place of CLIP encoder. How will results look like ?

@shivance So from what I have read, while the stable diffusion paper used BERT, the released stable diffusion model uses ClipText. I found a really interesting [article](https://jalammar.github.io/illustrated-stable-diffusion/) explaining ClipText as well. 
There could be many reasons for this switch and replacement in favour of ClipText.

**Comment by shivance** [comment]
> > This thought immediately cross my mind. What if we use classical knowledge rich transformer like BERT family in place of CLIP encoder. How will results look like ?
> 
> @shivance So from what I have read, while the stable diffusion paper used BERT, the released stable diffusion model uses ClipText. I found a really interesting [article](https://jalammar.github.io/illustrated-stable-diffusion/) explaining ClipText as well. There could be many reasons for this switch and replacement in favour of ClipText.

![image](https://user-images.githubusercontent.com/51750587/227708450-03fc9921-29f5-4d04-a79c-b6cbd75ec342.png)

This is interesting. 

@ianstenbit and @LukeWood are authors of KerasCV  stable diffusion, tagging them

**Comment by ianstenbit** [comment]
+1 to @mattdangerw's comments here.

We should depend on a KerasNLP tokenizer+encoder for KerasCV's StableDiffusion model, and KerasCV is certainly open to a contribution to add this dependency.

Training new diffusion models with different encoders is an interesting topic, and one that can potentially leverage KerasCV/NLP's model offerings, but it's not something that the Keras team is planning to take up right now.
