### ISSUE TITLE
model.summary() for classifiers errors out

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#898]
Reference : [Comment](https://github.com/keras-team/keras-io/pull/1253#discussion_r1128314423)  (cc : @mattdangerw )

Steps to reproduce : 

```
bert_classifier = keras_nlp.models.BertClassifier.from_preset(
    "bert_tiny_en_uncased", 
    num_classes=3)

bert_classifier.summary()
```

**Calling summary() results in **
<details> <summary>ValueError </summary>
```   
 ValueError : Traceback (most recent call last)
[<ipython-input-12-8848456c616d>](https://localhost:8080/#) in <module>
      3     num_classes=3)
      4 
----> 5 bert_classifier.summary()

4 frames
[/usr/local/lib/python3.9/dist-packages/keras/engine/training.py](https://localhost:8080/#) in summary(self, line_length, positions, print_fn, expand_nested, show_trainable, layer_range)
   3295                 "the model on a batch of data."
   3296             )
-> 3297         layer_utils.print_summary(
   3298             self,
   3299             line_length=line_length,

[/usr/local/lib/python3.9/dist-packages/keras/utils/layer_utils.py](https://localhost:8080/#) in print_summary(model, line_length, positions, print_fn, expand_nested, show_trainable, layer_range)
    428 
    429     for layer in model.layers[layer_range[0] : layer_range[1]]:
--> 430         print_layer(layer)
    431     print_fn("=" * line_length)
    432 

[/usr/local/lib/python3.9/dist-packages/keras/utils/layer_utils.py](https://localhost:8080/#) in print_layer(layer, nested_level, is_nested_last)
    398             print_layer_summary(layer, nested_level)
    399         else:
--> 400             print_layer_summary_with_connections(layer, nested_level)
    401 
    402         if expand_nested and hasattr(layer, "layers") and layer.layers:

[/usr/local/lib/python3.9/dist-packages/keras/utils/layer_utils.py](https://localhost:8080/#) in print_layer_summary_with_connections(layer, nested_level)
    385             name + " (" + cls_name + ")",
    386             output_shape,
--> 387             layer.count_params(),
    388             connections,
    389         ]

[/usr/local/lib/python3.9/dist-packages/keras/engine/base_layer.py](https://localhost:8080/#) in count_params(self)
   2141                     self._maybe_build(self.inputs)
   2142             else:
-> 2143                 raise ValueError(
   2144                     "You tried to call `count_params` "
   2145                     f"on layer {self.name}"

ValueError: You tried to call `count_params` on layer bert_preprocessor_1, but the layer isn't built. You can build it manually via: `bert_preprocessor_1.build(batch_input_shape)`.

</details>

## Bypass error
However, setting `preprocessor=None` and calling summary() raises no error.

Irrespective of either, model works fine.

## Potential Fix

I think adding a build call in preprocessor layers should solve the bug. But how do we pass `input_batch_shape`?

**Comment by shivance** [comment]
Tagging @chenmoneygithub as well !

**Comment by chenmoneygithub** [comment]
@mattdangerw I remember we discussed this like months ago, and we did not reach a conclusion how we should plot the preprocessor. Having an isolated layer is a bit confusing to our users (Martin pointed that out IIRC), while not showing it at all does not reflect the design of our Task model.

**Comment by shivance** [comment]
> Long term, we should figure out a get representation of the preprocessing layer (which is disconnected from the model graph), in the printed model summary.

@mattdangerw If we develop a decoupled preprocessor layer, then we can probably ship #631 too. Because keras.Model as of now is not recognizing preprocessor layer attached to the model. I have a hunch that the reason is the same as this issue. The preprocessor layer is not built.

I agree to what @chenmoneygithub said, a seperate layer wouldn't be user friendly.

**Comment by shivance** [comment]
> Good find!
> 
> Short term, we need a way for model summary to not error out when a preprocessor is set on the layer. (We could disable tracking on the layer, though I am not sure that is the best solution).
>

The possible solution can be overriding the `summary() method in our Task and Preprocessor (whichever works), add a try except block, and pass the error.

**Comment by mattdangerw** [comment]
I guess here's my overall take.

I think it would be a bad idea to show the preprocessing as regular layers. The preprocessing is separable, and will run asynchronously on a separate processing unit. We need to visually indicate that is different than the core model graph.

Another challenge is our contract with core Keras. We want to avoid depending on private implementation details of core Keras if we can, so we can work across tensorflow versions. We would also like to avoid replicating the entirety of `model.summary()`, which is fairly involved.

So all that said, here was the best I could come up with...

 - We leave the underlying `model.summary()` as is, no changes.
 - We copy some printing utilities over from core Keras, and add an additional top section if a preprocessos is set on the task.

Here's a [demo](https://colab.research.google.com/gist/mattdangerw/0b24ef4548e86c2872e9c21bd4d106ea/task-summaries.ipynb) of this in action, and a [pull request](https://github.com/keras-team/keras-nlp/issues/898). It's not perfect visually, but relies only on public contracts with core Keras.

@fchollet any thoughts on this overall?

**Comment by jbischof** [comment]
When did this break? I thought @martin-gorner was originally complaining that the preprocessor shows up as an unconnected layer but now `summary` throws?

**Comment by mattdangerw** [comment]
I think it depend on when you call the task model, which we missed last time we talked on this.

- If you call summary after running some data through the model, you see an unconnected preprocessing layer. Not great, but not end of the world.
- If you call summary before any other calls, you get the inscrutable error above. Pretty bad!

Talked with @fchollet and we think https://github.com/keras-team/keras-nlp/pull/901 is probably worth landing. Will address both the issues above.
