### ISSUE TITLE
`.generate()` should support input datasets

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#911]
It would be a good idea to add support for passing a dataset to `generate()` for a few reasons.

 - In the seq2seq case, summarizing/translating an entire dataset is a real use case. We should in theory see the same performance gains using `tf.data.Dataset.prefetch` setup as with `fit()` and `predict()`.
 - We want `generate()` to have a similar UX to `fit()` and `predict()`.

**Comment by amangupta201** [comment]
This can be done like:
Splitting words with text_to_word sequence:
from keras.preprocessing.text import text_to_word_sequence
# define the document
text = 'Today is a wonderful day'
# tokenize the document
result = text_to_word_sequence(text)
print(result)
