### ISSUE TITLE
Ship a generative example using GPT2 on keras.io

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#920]
We should show a complete generative example with GPT2 on keras.io.

**Comment by Neeshamraghav012** [comment]
Hi @mattdangerw, I have experimented with gpt2 a lot, and I can help with this.

**Comment by mattdangerw** [comment]
Thanks for this interest, but this particular issue is already being worked on by @chenmoneygithub, that's why he is assigned. We will try to add the Contributions Welcome tag for issues we are looking for assistance with!

We may have more need for generative style examples after @chenmoneygithub's initial example goes up, so stay tuned!

**Comment by NiharJani2002** [comment]
Okay 👍.

**Comment by mattdangerw** [comment]
This is done!
