### ISSUE TITLE
Add OPTCausalLM task model

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#921]
We should follow the template of GPT2CausalLM, and add a generative task model for OPT.

**Comment by shivance** [comment]
Hey @mattdangerw , can I help with this?

**Comment by mattdangerw** [comment]
@ADITYADAS1999 ah sorry missed this. Generally speaking--these issues that we are leaving assigned to a maintainer of the library, and not marked as "Contributions Welcome" are issue the assignee is working on in some form.

This one will be handled by @chenmoneygithub . But thanks for the interest!

**Comment by ADITYADAS1999** [comment]
Thanks @mattdangerw  for informing 👍
