### ISSUE TITLE
Update keras.io API documentation for 0.5 release

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#922]
We should update our API page with all symbols, properties and methods added since 0.4.1.

**Comment by pavansai26** [comment]
@mattdangerw I am interested to take this can you please help me

**Comment by mattdangerw** [comment]
@pavansai26 thanks for the interest! But I was just logging this for myself, this is routine maintenance we do each release and not something for contributors.

Generally speaking when an issues is already assigned to a maintainer of the project, it is work that is actively being addressed by the assignee!

**Comment by mattdangerw** [comment]
Example PR: https://github.com/keras-team/keras-io/pull/1244

**Comment by mattdangerw** [comment]
Done!
