### ISSUE TITLE
First class support for RLHF in KerasNLP

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#933]
While first [implementation](https://github.com/openai/lm-human-preferences) for RLHF was released by OpenAI in 2019, over the year it has gained popularity, and it's taking over LLMs.

ChatGPT, GPT4, Bard ...

I did some research and found that currently we don't have any reliable framework (atleast I didn't find one) for RLHF in tensorflow.
For PyTorch [RL4LMs](https://github.com/allenai/RL4LMs) , [TRLx](https://github.com/CarperAI/trlx) are actively being maintained.

While KerasNLP offers modular building blocks to develop models, what are our thoughts on RLHF training support as an offering ?

**Comment by mattdangerw** [comment]
I think the very short version is yes we are very much interested in offering stuff for RLHF, and is with a lot in our library, the general flow might be guides and example first, stable APIs second.

I don't think this is super ready for contributions compared to the other issues flagged here, as we are still working on the "more basic" generative flows (solid examples for GPT2 and T5 fine-tuning and autoregressive inference), but more on this soon!

**Comment by jbischof** [comment]
@shivance I really appreciate your contributions but I would suggest filing feature requests only if you are specifically interested in that functionality. We are constantly working on our prioritization and all these issues are adding a lot of noise. Thank you!

**Comment by jbischof** [comment]
Also @shivance there is zero reason to be tagging all the package maintainers in every issue! We all check the issue queue; please be respectful.

**Comment by shivance** [comment]
Thanks @jbischof got the point here
