### ISSUE TITLE
`BertMaskedLMPreprocessor` - confusing behavior on padding_mask and mask_weights

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras-nlp#935]
This code is concerning to me:
```
x = super().call(x)

token_ids, padding_mask, segment_ids = (
    x["token_ids"],
    x["padding_mask"],
    x["segment_ids"],
)
masker_outputs = self.masker(token_ids)
x = {
    "token_ids": masker_outputs["token_ids"],
    "padding_mask": padding_mask,
    "segment_ids": segment_ids,
    "mask_positions": masker_outputs["mask_positions"],
}
y = masker_outputs["mask_ids"]
sample_weight = masker_outputs["mask_weights"]
```

The code appears to generate mask on padded inputs, and it relies on [this line](https://github.com/keras-team/keras-nlp/blob/a5b6c45620380019508b231a376267cbb3a02e46/keras_nlp/layers/masked_lm_mask_generator.py#L149) to convert padded inputs to the ragged inputs so that masked token is not generated on padding position. This is correct for BERT because `0` is the reserved padding token for BERT, but could easily go wrong for other models using other padding tokens. The more robust way is to passing `padding_mask` to `MaskedLMMaskGenerator` to do the right ragged tensor conversion. 

@mattdangerw Thoughts on this?

**Comment by abuelnasr0** [comment]
I think there is a variable called unselectable_token_ids Is being passed to the masker.

**Comment by mattdangerw** [comment]
Yep I think all set https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_masked_lm_preprocessor.py#L145-L149

Closing the issue, but re-open if I missed something

**Comment by chenmoneygithub** [comment]
@mattdangerw Thanks! For `BERT` we should be fine, what's concerning me is there is case that `pad_token` is not reserved, and we are skipping all `pad_token` from being masked. We can fix it by passing `padding_mask` to mask generator, so when we are generating masks on the ragged tensor (padding tokens removed).

**Comment by chenmoneygithub** [comment]
discussed offline, not fixing it now
