### ISSUE TITLE
Add a RandomSampler class

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#946]
We should add a `RandomSampler` class, you can use [TopKSampler](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/samplers/greedy_sampler.py) as a reference for this.

This sampler should be almost the same as `TopKSampler` except instead of doing `tf.random.categorical` on the top k predictions, we sample the entire probability distribution.

Checklist:
 - [ ] `random_sampler.py` class
 - [ ] `random_sampler_test.py` class with passing unit tests

**Comment by abuelnasr0** [comment]
Can I take this ?

**Comment by mattdangerw** [comment]
Please and thank you!

**Comment by mattdangerw** [comment]
This is now fixed!
