### ISSUE TITLE
Mixed precision errors for GPT2 and other models

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#959]
Already have a pull request, just opening this to track! https://github.com/keras-team/keras-nlp/pull/958

**Comment by ADITYADAS1999** [comment]
> Already have a pull request, just opening this to track! #958

hey @mattdangerw  can you explain this a bit !

**Comment by mattdangerw** [comment]
Sure thing! Basically Keras supports a mixed precision mode that is a substantial boost in performance for GPU training. https://www.tensorflow.org/guide/mixed_precision

But supporting it requires making sure our tensorflow ops do not assume an float32 computation type (we will use 16 bit floating point numbers instead). This PR that landed just removed a few places we were making too many assumptions about dtype, and breaking the "mixed precision" workflow.
