### ISSUE TITLE
Clean up sampler indexing

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#962]
Currently we have two different ways of referring to our loop index for sampling. The sampler `"index"` refers to the index of the token being generated, and the model `"cache_index"` refers to the index of the token being fed in (the previous index).

I think we can simplify things by always having our variables refer to the index of the token being fed in. This will be particular clarifying for contrastive search.

Here's a commit showing the rough idea -> https://github.com/mattdangerw/keras-nlp/commit/3b079b7f30d876e5e99da146e0090ec33e39ca30

**Comment by chenmoneygithub** [comment]
let's go for it! may wait for contrastive search PR to be submitted.
