### ISSUE TITLE
Consider an `early_stopping=True` flag for `generate()`

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#965]
Currently our generate function always ceases when all sequences contain a new `endoftext` token. We might instead want to make this configurable, so that generation can continue past end of document markers.

**Comment by chenmoneygithub** [comment]
I am not sure if we need this, is it a valid/common use case to generate passing the end token?

**Comment by mattdangerw** [comment]
This is now configurable via `stop_token_ids`, closing.
