### ISSUE TITLE
starter doc for huggingface-transformer user

### ISSUE THREAD

**Issue by pure-rgb** [keras-team/keras-nlp#977]
**Is your feature request related to a problem? Please describe.**

huggingface transformer is the de facto tools for nlp/cv task. A vast majority models live there and easy to train and inference. keras-nlp (not sure if it is the alternative of huggingface-transformer) emeges with great potential. Now user like me who is confortable in hf-transformer, how should I get started in keras-nlp?

**Describe the solution you'd like**

I know there is great example, https://keras.io/guides/keras_nlp/ But I like you to demonstrate modeling approach in kerass-nlp as hf-transformer-nlp view point. For example, In hf-transformer the input token is referred to as `input_ids` whereas in keras-nlp, I think it is referred to as `token_id`. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Neeshamraghav012** [comment]
hi @pure-rgb ,

I have written a [post ](https://www.kaggle.com/discussions/getting-started/400880)on Kaggle. It will help you!

**Comment by chenmoneygithub** [comment]
@pure-rgb Thanks for reporting the issue! Yes, it could be helpful to have a guide on the comparison. 

@Neeshamraghav012 Thank you for the writeup! 🍹

**Comment by pure-rgb** [comment]
@Neeshamraghav012 that is really a good starting point. But I think if there is any official stuff, written by keras-nlp team member, that would be more resourceful.
