### ISSUE TITLE
Rename the Classes in `keras_nlp/layers` to "EncoderBlock"?

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#99]
In `keras_nlp/layers`, we have classes like `TransformerEncoder`, `TransformerDecoder`, `FNetEncoder`. Should we rename these to `TransformerEncoderBlock`, `TransformerDecoderBlock` and `FNetEncoderBlock`, respectively?

TensorFlow Reference: https://github.com/tensorflow/models/tree/master/official/projects/longformer
Here, the `LongformerEncoder` is a stack of `LongformerEncoderBlock`s. This is the case for other models as well.

Hugging Face: [BertEncoder](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_bert.py#L530) is a stack of [BertLayer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_bert.py#L445)s.

**Comment by chenmoneygithub** [comment]
Thanks for reporting the issue!

We had this discussion before, and we decided to omit the block/layer suffix to keep it simple.
